// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminFieldNames          = builder.RawFieldNames(&Admin{})
	adminRows                = strings.Join(adminFieldNames, ",")
	adminRowsExpectAutoSet   = strings.Join(stringx.Remove(adminFieldNames, "`admin_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminRowsWithPlaceHolder = strings.Join(stringx.Remove(adminFieldNames, "`admin_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAmigoAdminAdminIdPrefix  = "cache:amigo:admin:adminId:"
	cacheAmigoAdminMobilePrefix   = "cache:amigo:admin:mobile:"
	cacheAmigoAdminUsernamePrefix = "cache:amigo:admin:username:"
)

type (
	adminModel interface {
		Insert(ctx context.Context, data *Admin) (sql.Result, error)
		FindOne(ctx context.Context, adminId uint64) (*Admin, error)
		FindOneByMobile(ctx context.Context, mobile string) (*Admin, error)
		FindOneByUsername(ctx context.Context, username string) (*Admin, error)
		Update(ctx context.Context, data *Admin) error
		Delete(ctx context.Context, adminId uint64) error
	}

	defaultAdminModel struct {
		sqlc.CachedConn
		table string
	}

	Admin struct {
		AdminId    uint64 `db:"admin_id"`
		Mobile     string `db:"mobile"`
		Avatar     string `db:"avatar"`
		Username   string `db:"username"`
		Password   string `db:"password"`
		IsDelete   int64  `db:"is_delete"`
		CreateTime uint64 `db:"create_time"`
		UpdateTime uint64 `db:"update_time"`
	}
)

func newAdminModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAdminModel {
	return &defaultAdminModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`admin`",
	}
}

func (m *defaultAdminModel) Delete(ctx context.Context, adminId uint64) error {
	data, err := m.FindOne(ctx, adminId)
	if err != nil {
		return err
	}

	amigoAdminAdminIdKey := fmt.Sprintf("%s%v", cacheAmigoAdminAdminIdPrefix, adminId)
	amigoAdminMobileKey := fmt.Sprintf("%s%v", cacheAmigoAdminMobilePrefix, data.Mobile)
	amigoAdminUsernameKey := fmt.Sprintf("%s%v", cacheAmigoAdminUsernamePrefix, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `admin_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, adminId)
	}, amigoAdminAdminIdKey, amigoAdminMobileKey, amigoAdminUsernameKey)
	return err
}

func (m *defaultAdminModel) FindOne(ctx context.Context, adminId uint64) (*Admin, error) {
	amigoAdminAdminIdKey := fmt.Sprintf("%s%v", cacheAmigoAdminAdminIdPrefix, adminId)
	var resp Admin
	err := m.QueryRowCtx(ctx, &resp, amigoAdminAdminIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `admin_id` = ? limit 1", adminRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, adminId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminModel) FindOneByMobile(ctx context.Context, mobile string) (*Admin, error) {
	amigoAdminMobileKey := fmt.Sprintf("%s%v", cacheAmigoAdminMobilePrefix, mobile)
	var resp Admin
	err := m.QueryRowIndexCtx(ctx, &resp, amigoAdminMobileKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `mobile` = ? limit 1", adminRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, mobile); err != nil {
			return nil, err
		}
		return resp.AdminId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminModel) FindOneByUsername(ctx context.Context, username string) (*Admin, error) {
	amigoAdminUsernameKey := fmt.Sprintf("%s%v", cacheAmigoAdminUsernamePrefix, username)
	var resp Admin
	err := m.QueryRowIndexCtx(ctx, &resp, amigoAdminUsernameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", adminRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, username); err != nil {
			return nil, err
		}
		return resp.AdminId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminModel) Insert(ctx context.Context, data *Admin) (sql.Result, error) {
	amigoAdminAdminIdKey := fmt.Sprintf("%s%v", cacheAmigoAdminAdminIdPrefix, data.AdminId)
	amigoAdminMobileKey := fmt.Sprintf("%s%v", cacheAmigoAdminMobilePrefix, data.Mobile)
	amigoAdminUsernameKey := fmt.Sprintf("%s%v", cacheAmigoAdminUsernamePrefix, data.Username)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, adminRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Mobile, data.Avatar, data.Username, data.Password, data.IsDelete)
	}, amigoAdminAdminIdKey, amigoAdminMobileKey, amigoAdminUsernameKey)
	return ret, err
}

func (m *defaultAdminModel) Update(ctx context.Context, newData *Admin) error {
	data, err := m.FindOne(ctx, newData.AdminId)
	if err != nil {
		return err
	}

	amigoAdminAdminIdKey := fmt.Sprintf("%s%v", cacheAmigoAdminAdminIdPrefix, data.AdminId)
	amigoAdminMobileKey := fmt.Sprintf("%s%v", cacheAmigoAdminMobilePrefix, data.Mobile)
	amigoAdminUsernameKey := fmt.Sprintf("%s%v", cacheAmigoAdminUsernamePrefix, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `admin_id` = ?", m.table, adminRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Mobile, newData.Avatar, newData.Username, newData.Password, newData.IsDelete, newData.AdminId)
	}, amigoAdminAdminIdKey, amigoAdminMobileKey, amigoAdminUsernameKey)
	return err
}

func (m *defaultAdminModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAmigoAdminAdminIdPrefix, primary)
}

func (m *defaultAdminModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `admin_id` = ? limit 1", adminRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAdminModel) tableName() string {
	return m.table
}
