// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userThirdPartyFieldNames          = builder.RawFieldNames(&UserThirdParty{})
	userThirdPartyRows                = strings.Join(userThirdPartyFieldNames, ",")
	userThirdPartyRowsExpectAutoSet   = strings.Join(stringx.Remove(userThirdPartyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userThirdPartyRowsWithPlaceHolder = strings.Join(stringx.Remove(userThirdPartyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAmigoUserThirdPartyIdPrefix            = "cache:amigo:userThirdParty:id:"
	cacheAmigoUserThirdPartyAppTypeOpenidPrefix = "cache:amigo:userThirdParty:appType:openid:"
)

type (
	userThirdPartyModel interface {
		Insert(ctx context.Context, data *UserThirdParty) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserThirdParty, error)
		FindOneByAppTypeOpenid(ctx context.Context, appType string, openid string) (*UserThirdParty, error)
		Update(ctx context.Context, data *UserThirdParty) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserThirdPartyModel struct {
		sqlc.CachedConn
		table string
	}

	UserThirdParty struct {
		Id           uint64 `db:"id"`            // 主键ID
		UserId       uint64 `db:"user_id"`       // 用户ID
		Platform     string `db:"platform"`      // 平台: wechat, qq, alipay, weibo, apple, github, google, facebook
		PlatformType string `db:"platform_type"` // 平台类型: mini_program(小程序), official_account(公众号), web, app
		AppType      string `db:"app_type"`      // 第三方应用类型
		Openid       string `db:"openid"`        // 第三方用户OpenID
		Unionid      string `db:"unionid"`       // 第三方UnionID
		ThirdUserId  string `db:"third_user_id"` // 第三方用户ID(通用)
		IsBound      int64  `db:"is_bound"`      // 是否绑定: 0-解绑, 1-绑定
		CreatedAt    uint64 `db:"created_at"`    // 创建时间
		UpdatedAt    uint64 `db:"updated_at"`    // 更新时间
		DeletedAt    uint64 `db:"deleted_at"`    // 软删除时间
	}
)

func newUserThirdPartyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserThirdPartyModel {
	return &defaultUserThirdPartyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_third_party`",
	}
}

func (m *defaultUserThirdPartyModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	amigoUserThirdPartyAppTypeOpenidKey := fmt.Sprintf("%s%v:%v", cacheAmigoUserThirdPartyAppTypeOpenidPrefix, data.AppType, data.Openid)
	amigoUserThirdPartyIdKey := fmt.Sprintf("%s%v", cacheAmigoUserThirdPartyIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, amigoUserThirdPartyAppTypeOpenidKey, amigoUserThirdPartyIdKey)
	return err
}

func (m *defaultUserThirdPartyModel) FindOne(ctx context.Context, id uint64) (*UserThirdParty, error) {
	amigoUserThirdPartyIdKey := fmt.Sprintf("%s%v", cacheAmigoUserThirdPartyIdPrefix, id)
	var resp UserThirdParty
	err := m.QueryRowCtx(ctx, &resp, amigoUserThirdPartyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userThirdPartyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserThirdPartyModel) FindOneByAppTypeOpenid(ctx context.Context, appType string, openid string) (*UserThirdParty, error) {
	amigoUserThirdPartyAppTypeOpenidKey := fmt.Sprintf("%s%v:%v", cacheAmigoUserThirdPartyAppTypeOpenidPrefix, appType, openid)
	var resp UserThirdParty
	err := m.QueryRowIndexCtx(ctx, &resp, amigoUserThirdPartyAppTypeOpenidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `app_type` = ? and `openid` = ? limit 1", userThirdPartyRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, appType, openid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserThirdPartyModel) Insert(ctx context.Context, data *UserThirdParty) (sql.Result, error) {
	amigoUserThirdPartyAppTypeOpenidKey := fmt.Sprintf("%s%v:%v", cacheAmigoUserThirdPartyAppTypeOpenidPrefix, data.AppType, data.Openid)
	amigoUserThirdPartyIdKey := fmt.Sprintf("%s%v", cacheAmigoUserThirdPartyIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userThirdPartyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Platform, data.PlatformType, data.AppType, data.Openid, data.Unionid, data.ThirdUserId, data.IsBound, data.DeletedAt)
	}, amigoUserThirdPartyAppTypeOpenidKey, amigoUserThirdPartyIdKey)
	return ret, err
}

func (m *defaultUserThirdPartyModel) Update(ctx context.Context, newData *UserThirdParty) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	amigoUserThirdPartyAppTypeOpenidKey := fmt.Sprintf("%s%v:%v", cacheAmigoUserThirdPartyAppTypeOpenidPrefix, data.AppType, data.Openid)
	amigoUserThirdPartyIdKey := fmt.Sprintf("%s%v", cacheAmigoUserThirdPartyIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userThirdPartyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.Platform, newData.PlatformType, newData.AppType, newData.Openid, newData.Unionid, newData.ThirdUserId, newData.IsBound, newData.DeletedAt, newData.Id)
	}, amigoUserThirdPartyAppTypeOpenidKey, amigoUserThirdPartyIdKey)
	return err
}

func (m *defaultUserThirdPartyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAmigoUserThirdPartyIdPrefix, primary)
}

func (m *defaultUserThirdPartyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userThirdPartyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserThirdPartyModel) tableName() string {
	return m.table
}
