// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type CommonResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type EmptyResp struct {
}

type GetTaskReq struct {
	Id int64 `path:"id"`
}

type GetTaskResp struct {
	Id        int64  `json:"id"`
	TaskId    string `json:"task_id"`
	TaskType  string `json:"task_type"`
	Prompt    string `json:"prompt"`
	Status    int    `json:"status"`
	ResultUrl string `json:"result_url"`
	ErrorMsg  string `json:"error_msg"`
	CreatedAt int64  `json:"created_at"`
}

type SubmitTaskReq struct {
	TaskType string `json:"task_type"`
	Prompt   string `json:"prompt"`
	Params   string `json:"params,optional"`
}

type SubmitTaskResp struct {
	Id     int64  `json:"id"`
	TaskId string `json:"task_id"`
}

type TaskListReq struct {
	Page     int    `json:"page,optional,default=1"`
	PageSize int    `json:"page_size,optional,default=10"`
	TaskId   string `json:"task_id,optional"`
	TaskType string `json:"task_type,optional"`
	Status   int    `json:"status,optional"`
}

type TaskListResp struct {
	Total int64         `json:"total"`
	List  []GetTaskResp `json:"list"`
}
