// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	admin "amigo-api/app/user/api/internal/handler/admin"
	user "amigo-api/app/user/api/internal/handler/user"
	"amigo-api/app/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: admin.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: admin.AddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: admin.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/domain/list",
				Handler: admin.DomainListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: admin.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/policy/add",
				Handler: admin.PolicyAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/policy/delete",
				Handler: admin.PolicyDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/policy/list",
				Handler: admin.PolicyListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/add",
				Handler: admin.RoleAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/delete",
				Handler: admin.RoleDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/list",
				Handler: admin.RoleListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: admin.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update_mobile",
				Handler: admin.UpdateMobileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update_password",
				Handler: admin.UpdatePasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/third_login",
				Handler: user.ThirdLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: user.UserAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: user.UserDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: user.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: user.UserUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update_mobile",
				Handler: user.UserUpdateMobileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update_password",
				Handler: user.UserUpdatePasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/user"),
	)
}
