// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	appFieldNames          = builder.RawFieldNames(&App{})
	appRows                = strings.Join(appFieldNames, ",")
	appRowsExpectAutoSet   = strings.Join(stringx.Remove(appFieldNames, "`app_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	appRowsWithPlaceHolder = strings.Join(stringx.Remove(appFieldNames, "`app_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAmigoAppAppIdPrefix  = "cache:amigo:app:appId:"
	cacheAmigoAppAppKeyPrefix = "cache:amigo:app:appKey:"
)

type (
	appModel interface {
		Insert(ctx context.Context, data *App) (sql.Result, error)
		FindOne(ctx context.Context, appId uint64) (*App, error)
		FindOneByAppKey(ctx context.Context, appKey string) (*App, error)
		Update(ctx context.Context, data *App) error
		Delete(ctx context.Context, appId uint64) error
	}

	defaultAppModel struct {
		sqlc.CachedConn
		table string
	}

	App struct {
		AppId       uint64         `db:"app_id"`
		Name        string         `db:"name"`        // 应用名称
		AppKey      string         `db:"app_key"`     // 应用唯一标识
		Category    string         `db:"category"`    // 分类(sensor/automation/integration/analytics)
		Version     string         `db:"version"`     // 版本号
		Vendor      string         `db:"vendor"`      // 厂商
		IconBg      string         `db:"icon_bg"`     // 图标背景色
		IconColor   string         `db:"icon_color"`  // 图标颜色
		IconLabel   string         `db:"icon_label"`  // 图标文字
		Description sql.NullString `db:"description"` // 应用描述
		SensorType  string         `db:"sensor_type"` // 传感器类型
		ExtraData   sql.NullString `db:"extra_data"`  // JSON扩展数据(如data_points等)
		IsDelete    int64          `db:"is_delete"`   // 1删除2未删除
		CreateTime  uint64         `db:"create_time"`
		UpdateTime  uint64         `db:"update_time"`
	}
)

func newAppModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAppModel {
	return &defaultAppModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`app`",
	}
}

func (m *defaultAppModel) Delete(ctx context.Context, appId uint64) error {
	data, err := m.FindOne(ctx, appId)
	if err != nil {
		return err
	}

	amigoAppAppIdKey := fmt.Sprintf("%s%v", cacheAmigoAppAppIdPrefix, appId)
	amigoAppAppKeyKey := fmt.Sprintf("%s%v", cacheAmigoAppAppKeyPrefix, data.AppKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `app_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, appId)
	}, amigoAppAppIdKey, amigoAppAppKeyKey)
	return err
}

func (m *defaultAppModel) FindOne(ctx context.Context, appId uint64) (*App, error) {
	amigoAppAppIdKey := fmt.Sprintf("%s%v", cacheAmigoAppAppIdPrefix, appId)
	var resp App
	err := m.QueryRowCtx(ctx, &resp, amigoAppAppIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `app_id` = ? limit 1", appRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, appId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAppModel) FindOneByAppKey(ctx context.Context, appKey string) (*App, error) {
	amigoAppAppKeyKey := fmt.Sprintf("%s%v", cacheAmigoAppAppKeyPrefix, appKey)
	var resp App
	err := m.QueryRowIndexCtx(ctx, &resp, amigoAppAppKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `app_key` = ? limit 1", appRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, appKey); err != nil {
			return nil, err
		}
		return resp.AppId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAppModel) Insert(ctx context.Context, data *App) (sql.Result, error) {
	amigoAppAppIdKey := fmt.Sprintf("%s%v", cacheAmigoAppAppIdPrefix, data.AppId)
	amigoAppAppKeyKey := fmt.Sprintf("%s%v", cacheAmigoAppAppKeyPrefix, data.AppKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, appRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.AppKey, data.Category, data.Version, data.Vendor, data.IconBg, data.IconColor, data.IconLabel, data.Description, data.SensorType, data.ExtraData, data.IsDelete)
	}, amigoAppAppIdKey, amigoAppAppKeyKey)
	return ret, err
}

func (m *defaultAppModel) Update(ctx context.Context, newData *App) error {
	data, err := m.FindOne(ctx, newData.AppId)
	if err != nil {
		return err
	}

	amigoAppAppIdKey := fmt.Sprintf("%s%v", cacheAmigoAppAppIdPrefix, data.AppId)
	amigoAppAppKeyKey := fmt.Sprintf("%s%v", cacheAmigoAppAppKeyPrefix, data.AppKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `app_id` = ?", m.table, appRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.AppKey, newData.Category, newData.Version, newData.Vendor, newData.IconBg, newData.IconColor, newData.IconLabel, newData.Description, newData.SensorType, newData.ExtraData, newData.IsDelete, newData.AppId)
	}, amigoAppAppIdKey, amigoAppAppKeyKey)
	return err
}

func (m *defaultAppModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAmigoAppAppIdPrefix, primary)
}

func (m *defaultAppModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `app_id` = ? limit 1", appRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAppModel) tableName() string {
	return m.table
}
