// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	deviceFieldNames          = builder.RawFieldNames(&Device{})
	deviceRows                = strings.Join(deviceFieldNames, ",")
	deviceRowsExpectAutoSet   = strings.Join(stringx.Remove(deviceFieldNames, "`device_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	deviceRowsWithPlaceHolder = strings.Join(stringx.Remove(deviceFieldNames, "`device_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAmigoDeviceDeviceIdPrefix   = "cache:amigo:device:deviceId:"
	cacheAmigoDeviceMacAddressPrefix = "cache:amigo:device:macAddress:"
)

type (
	deviceModel interface {
		Insert(ctx context.Context, data *Device) (sql.Result, error)
		FindOne(ctx context.Context, deviceId uint64) (*Device, error)
		FindOneByMacAddress(ctx context.Context, macAddress string) (*Device, error)
		Update(ctx context.Context, data *Device) error
		Delete(ctx context.Context, deviceId uint64) error
	}

	defaultDeviceModel struct {
		sqlc.CachedConn
		table string
	}

	Device struct {
		DeviceId   uint64 `db:"device_id"`
		Name       string `db:"name"`        // 设备名
		UserId     uint64 `db:"user_id"`     // 用户id
		MacAddress string `db:"mac_address"` // mac地址
		InternalIp string `db:"internal_ip"` // 内网ip
		BmpImage   string `db:"bmp_image"`   // 展示的bmp图片
		IsRunning  int64  `db:"is_running"`  // 1运行中2未运行
		ExtraData  string `db:"extra_data"`  // 额外的json数据
		IsDelete   int64  `db:"is_delete"`   // 1删除2未删除
		CreateTime uint64 `db:"create_time"`
		UpdateTime uint64 `db:"update_time"`
	}
)

func newDeviceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDeviceModel {
	return &defaultDeviceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`device`",
	}
}

func (m *defaultDeviceModel) Delete(ctx context.Context, deviceId uint64) error {
	data, err := m.FindOne(ctx, deviceId)
	if err != nil {
		return err
	}

	amigoDeviceDeviceIdKey := fmt.Sprintf("%s%v", cacheAmigoDeviceDeviceIdPrefix, deviceId)
	amigoDeviceMacAddressKey := fmt.Sprintf("%s%v", cacheAmigoDeviceMacAddressPrefix, data.MacAddress)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `device_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, deviceId)
	}, amigoDeviceDeviceIdKey, amigoDeviceMacAddressKey)
	return err
}

func (m *defaultDeviceModel) FindOne(ctx context.Context, deviceId uint64) (*Device, error) {
	amigoDeviceDeviceIdKey := fmt.Sprintf("%s%v", cacheAmigoDeviceDeviceIdPrefix, deviceId)
	var resp Device
	err := m.QueryRowCtx(ctx, &resp, amigoDeviceDeviceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `device_id` = ? limit 1", deviceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, deviceId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDeviceModel) FindOneByMacAddress(ctx context.Context, macAddress string) (*Device, error) {
	amigoDeviceMacAddressKey := fmt.Sprintf("%s%v", cacheAmigoDeviceMacAddressPrefix, macAddress)
	var resp Device
	err := m.QueryRowIndexCtx(ctx, &resp, amigoDeviceMacAddressKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `mac_address` = ? limit 1", deviceRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, macAddress); err != nil {
			return nil, err
		}
		return resp.DeviceId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDeviceModel) Insert(ctx context.Context, data *Device) (sql.Result, error) {
	amigoDeviceDeviceIdKey := fmt.Sprintf("%s%v", cacheAmigoDeviceDeviceIdPrefix, data.DeviceId)
	amigoDeviceMacAddressKey := fmt.Sprintf("%s%v", cacheAmigoDeviceMacAddressPrefix, data.MacAddress)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, deviceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.UserId, data.MacAddress, data.InternalIp, data.BmpImage, data.IsRunning, data.ExtraData, data.IsDelete)
	}, amigoDeviceDeviceIdKey, amigoDeviceMacAddressKey)
	return ret, err
}

func (m *defaultDeviceModel) Update(ctx context.Context, newData *Device) error {
	data, err := m.FindOne(ctx, newData.DeviceId)
	if err != nil {
		return err
	}

	amigoDeviceDeviceIdKey := fmt.Sprintf("%s%v", cacheAmigoDeviceDeviceIdPrefix, data.DeviceId)
	amigoDeviceMacAddressKey := fmt.Sprintf("%s%v", cacheAmigoDeviceMacAddressPrefix, data.MacAddress)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `device_id` = ?", m.table, deviceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.UserId, newData.MacAddress, newData.InternalIp, newData.BmpImage, newData.IsRunning, newData.ExtraData, newData.IsDelete, newData.DeviceId)
	}, amigoDeviceDeviceIdKey, amigoDeviceMacAddressKey)
	return err
}

func (m *defaultDeviceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAmigoDeviceDeviceIdPrefix, primary)
}

func (m *defaultDeviceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `device_id` = ? limit 1", deviceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDeviceModel) tableName() string {
	return m.table
}
