// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	deviceEventFieldNames          = builder.RawFieldNames(&DeviceEvent{})
	deviceEventRows                = strings.Join(deviceEventFieldNames, ",")
	deviceEventRowsExpectAutoSet   = strings.Join(stringx.Remove(deviceEventFieldNames, "`device_event_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	deviceEventRowsWithPlaceHolder = strings.Join(stringx.Remove(deviceEventFieldNames, "`device_event_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAmigoDeviceEventDeviceEventIdPrefix = "cache:amigo:deviceEvent:deviceEventId:"
)

type (
	deviceEventModel interface {
		Insert(ctx context.Context, data *DeviceEvent) (sql.Result, error)
		FindOne(ctx context.Context, deviceEventId uint64) (*DeviceEvent, error)
		Update(ctx context.Context, data *DeviceEvent) error
		Delete(ctx context.Context, deviceEventId uint64) error
	}

	defaultDeviceEventModel struct {
		sqlc.CachedConn
		table string
	}

	DeviceEvent struct {
		DeviceEventId uint64         `db:"device_event_id"`
		DeviceId      uint64         `db:"device_id"`   // 设备id
		EventType     string         `db:"event_type"`  // 事件类型(heartbeat/info/warning/error/success)
		EventLevel    string         `db:"event_level"` // 事件等级(info/warning/error/success)
		Title         string         `db:"title"`       // 事件标题
		Description   sql.NullString `db:"description"` // 事件描述
		Source        string         `db:"source"`      // 事件来源(device/ota/app/automation)
		ExtraData     sql.NullString `db:"extra_data"`  // JSON扩展数据
		IsDelete      int64          `db:"is_delete"`   // 1删除2未删除
		CreateTime    uint64         `db:"create_time"` // 创建时间
	}
)

func newDeviceEventModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDeviceEventModel {
	return &defaultDeviceEventModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`device_event`",
	}
}

func (m *defaultDeviceEventModel) Delete(ctx context.Context, deviceEventId uint64) error {
	amigoDeviceEventDeviceEventIdKey := fmt.Sprintf("%s%v", cacheAmigoDeviceEventDeviceEventIdPrefix, deviceEventId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `device_event_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, deviceEventId)
	}, amigoDeviceEventDeviceEventIdKey)
	return err
}

func (m *defaultDeviceEventModel) FindOne(ctx context.Context, deviceEventId uint64) (*DeviceEvent, error) {
	amigoDeviceEventDeviceEventIdKey := fmt.Sprintf("%s%v", cacheAmigoDeviceEventDeviceEventIdPrefix, deviceEventId)
	var resp DeviceEvent
	err := m.QueryRowCtx(ctx, &resp, amigoDeviceEventDeviceEventIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `device_event_id` = ? limit 1", deviceEventRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, deviceEventId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDeviceEventModel) Insert(ctx context.Context, data *DeviceEvent) (sql.Result, error) {
	amigoDeviceEventDeviceEventIdKey := fmt.Sprintf("%s%v", cacheAmigoDeviceEventDeviceEventIdPrefix, data.DeviceEventId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, deviceEventRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeviceId, data.EventType, data.EventLevel, data.Title, data.Description, data.Source, data.ExtraData, data.IsDelete)
	}, amigoDeviceEventDeviceEventIdKey)
	return ret, err
}

func (m *defaultDeviceEventModel) Update(ctx context.Context, data *DeviceEvent) error {
	amigoDeviceEventDeviceEventIdKey := fmt.Sprintf("%s%v", cacheAmigoDeviceEventDeviceEventIdPrefix, data.DeviceEventId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `device_event_id` = ?", m.table, deviceEventRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeviceId, data.EventType, data.EventLevel, data.Title, data.Description, data.Source, data.ExtraData, data.IsDelete, data.DeviceEventId)
	}, amigoDeviceEventDeviceEventIdKey)
	return err
}

func (m *defaultDeviceEventModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAmigoDeviceEventDeviceEventIdPrefix, primary)
}

func (m *defaultDeviceEventModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `device_event_id` = ? limit 1", deviceEventRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDeviceEventModel) tableName() string {
	return m.table
}
