// Code generated by goctl. DO NOT EDIT.

package types

type EnqueueReq struct {
	Handler string                 `json:"handler"`
	Data    map[string]interface{} `json:"data"`
	Queue   string                 `json:"queue,optional"`
	Delay   string                 `json:"delay,optional"`
}

type TaskInfoResp struct {
	TaskID string `json:"task_id"`
}

type TaskResultReq struct {
	TaskID string `path:"task_id"`
}

type TaskResultResp struct {
	TaskID     string `json:"task_id"`
	Status     string `json:"status"`
	Error      string `json:"error,omitempty"`
	Duration   int64  `json:"duration"`
	FinishedAt int64  `json:"finished_at"`
}

type CommonResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type EmptyResp struct{}
