// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: device.proto

package server

import (
	"context"

	"amigo-api/app/device/rpc/internal/logic"
	"amigo-api/app/device/rpc/internal/svc"
	"amigo-api/common/pb"
)

type DeviceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDeviceServer
}

func NewDeviceServer(svcCtx *svc.ServiceContext) *DeviceServer {
	return &DeviceServer{
		svcCtx: svcCtx,
	}
}

func (s *DeviceServer) AddDevice(ctx context.Context, in *pb.AddDeviceReq) (*pb.DeviceResp, error) {
	l := logic.NewAddDeviceLogic(ctx, s.svcCtx)
	return l.AddDevice(in)
}

func (s *DeviceServer) UpdateDevice(ctx context.Context, in *pb.DeviceResp) (*pb.DeviceResp, error) {
	l := logic.NewUpdateDeviceLogic(ctx, s.svcCtx)
	return l.UpdateDevice(in)
}

func (s *DeviceServer) GetDevice(ctx context.Context, in *pb.GetDeviceReq) (*pb.DeviceResp, error) {
	l := logic.NewGetDeviceLogic(ctx, s.svcCtx)
	return l.GetDevice(in)
}

func (s *DeviceServer) DeleteDevice(ctx context.Context, in *pb.DeleteDeviceReq) (*pb.DeleteDeviceResp, error) {
	l := logic.NewDeleteDeviceLogic(ctx, s.svcCtx)
	return l.DeleteDevice(in)
}

func (s *DeviceServer) ListDevice(ctx context.Context, in *pb.ListDeviceReq) (*pb.ListDeviceResp, error) {
	l := logic.NewListDeviceLogic(ctx, s.svcCtx)
	return l.ListDevice(in)
}
