// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: device.proto

package server

import (
	"context"

	"amigo-api/app/device/rpc/internal/logic"
	"amigo-api/app/device/rpc/internal/svc"
	"amigo-api/common/pb"
)

type DeviceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDeviceServer
}

func NewDeviceServer(svcCtx *svc.ServiceContext) *DeviceServer {
	return &DeviceServer{
		svcCtx: svcCtx,
	}
}

func (s *DeviceServer) AddDevice(ctx context.Context, in *pb.AddDeviceReq) (*pb.DeviceResp, error) {
	l := logic.NewAddDeviceLogic(ctx, s.svcCtx)
	return l.AddDevice(in)
}

func (s *DeviceServer) UpdateDevice(ctx context.Context, in *pb.DeviceResp) (*pb.DeviceResp, error) {
	l := logic.NewUpdateDeviceLogic(ctx, s.svcCtx)
	return l.UpdateDevice(in)
}

func (s *DeviceServer) GetDevice(ctx context.Context, in *pb.GetDeviceReq) (*pb.DeviceResp, error) {
	l := logic.NewGetDeviceLogic(ctx, s.svcCtx)
	return l.GetDevice(in)
}

func (s *DeviceServer) DeleteDevice(ctx context.Context, in *pb.DeleteDeviceReq) (*pb.DeleteDeviceResp, error) {
	l := logic.NewDeleteDeviceLogic(ctx, s.svcCtx)
	return l.DeleteDevice(in)
}

func (s *DeviceServer) ListDevice(ctx context.Context, in *pb.ListDeviceReq) (*pb.ListDeviceResp, error) {
	l := logic.NewListDeviceLogic(ctx, s.svcCtx)
	return l.ListDevice(in)
}

func (s *DeviceServer) AddApp(ctx context.Context, in *pb.AddAppReq) (*pb.AppResp, error) {
	l := logic.NewAddAppLogic(ctx, s.svcCtx)
	return l.AddApp(in)
}

func (s *DeviceServer) UpdateApp(ctx context.Context, in *pb.AppResp) (*pb.AppResp, error) {
	l := logic.NewUpdateAppLogic(ctx, s.svcCtx)
	return l.UpdateApp(in)
}

func (s *DeviceServer) GetApp(ctx context.Context, in *pb.GetAppReq) (*pb.AppResp, error) {
	l := logic.NewGetAppLogic(ctx, s.svcCtx)
	return l.GetApp(in)
}

func (s *DeviceServer) DeleteApp(ctx context.Context, in *pb.DeleteAppReq) (*pb.DeleteAppResp, error) {
	l := logic.NewDeleteAppLogic(ctx, s.svcCtx)
	return l.DeleteApp(in)
}

func (s *DeviceServer) ListApp(ctx context.Context, in *pb.ListAppReq) (*pb.ListAppResp, error) {
	l := logic.NewListAppLogic(ctx, s.svcCtx)
	return l.ListApp(in)
}

func (s *DeviceServer) AddDeviceEvent(ctx context.Context, in *pb.AddDeviceEventReq) (*pb.DeviceEventResp, error) {
	l := logic.NewAddDeviceEventLogic(ctx, s.svcCtx)
	return l.AddDeviceEvent(in)
}

func (s *DeviceServer) DeleteDeviceEvent(ctx context.Context, in *pb.DeleteDeviceEventReq) (*pb.DeleteDeviceEventResp, error) {
	l := logic.NewDeleteDeviceEventLogic(ctx, s.svcCtx)
	return l.DeleteDeviceEvent(in)
}

func (s *DeviceServer) GetDeviceEvent(ctx context.Context, in *pb.GetDeviceEventReq) (*pb.DeviceEventResp, error) {
	l := logic.NewGetDeviceEventLogic(ctx, s.svcCtx)
	return l.GetDeviceEvent(in)
}

func (s *DeviceServer) ListDeviceEvent(ctx context.Context, in *pb.ListDeviceEventReq) (*pb.ListDeviceEventResp, error) {
	l := logic.NewListDeviceEventLogic(ctx, s.svcCtx)
	return l.ListDeviceEvent(in)
}

func (s *DeviceServer) GetDeviceStats(ctx context.Context, in *pb.GetDeviceStatsReq) (*pb.DeviceStatsResp, error) {
	l := logic.NewGetDeviceStatsLogic(ctx, s.svcCtx)
	return l.GetDeviceStats(in)
}
