// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: device.proto

package device

import (
	"context"

	"amigo-api/common/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAppReq                = pb.AddAppReq
	AddDeviceEventReq        = pb.AddDeviceEventReq
	AddDeviceReq             = pb.AddDeviceReq
	AddFirmwareReq           = pb.AddFirmwareReq
	AddWorkOrderReq          = pb.AddWorkOrderReq
	AppResp                  = pb.AppResp
	DeleteAppReq             = pb.DeleteAppReq
	DeleteAppResp            = pb.DeleteAppResp
	DeleteDeviceEventReq     = pb.DeleteDeviceEventReq
	DeleteDeviceEventResp    = pb.DeleteDeviceEventResp
	DeleteDeviceReq          = pb.DeleteDeviceReq
	DeleteDeviceResp         = pb.DeleteDeviceResp
	DeleteFirmwareReq        = pb.DeleteFirmwareReq
	DeleteFirmwareResp       = pb.DeleteFirmwareResp
	DeviceEventResp          = pb.DeviceEventResp
	DeviceResp               = pb.DeviceResp
	DeviceStatsResp          = pb.DeviceStatsResp
	FirmwareResp             = pb.FirmwareResp
	FirmwareTaskResp         = pb.FirmwareTaskResp
	GetAppReq                = pb.GetAppReq
	GetDeviceEventReq        = pb.GetDeviceEventReq
	GetDeviceReq             = pb.GetDeviceReq
	GetDeviceStatsReq        = pb.GetDeviceStatsReq
	GetFirmwareReq           = pb.GetFirmwareReq
	GetFirmwareTaskReq       = pb.GetFirmwareTaskReq
	GetMqttMessagesReq       = pb.GetMqttMessagesReq
	GetMqttMessagesResp      = pb.GetMqttMessagesResp
	GetWorkOrderReq          = pb.GetWorkOrderReq
	GetWorkOrderResp         = pb.GetWorkOrderResp
	ListAppReq               = pb.ListAppReq
	ListAppResp              = pb.ListAppResp
	ListDeviceEventReq       = pb.ListDeviceEventReq
	ListDeviceEventResp      = pb.ListDeviceEventResp
	ListDeviceReq            = pb.ListDeviceReq
	ListDeviceResp           = pb.ListDeviceResp
	ListFirmwareReq          = pb.ListFirmwareReq
	ListFirmwareResp         = pb.ListFirmwareResp
	ListFirmwareTaskReq      = pb.ListFirmwareTaskReq
	ListFirmwareTaskResp     = pb.ListFirmwareTaskResp
	ListWorkOrderReq         = pb.ListWorkOrderReq
	ListWorkOrderResp        = pb.ListWorkOrderResp
	MqttMsg                  = pb.MqttMsg
	PushFirmwareTaskReq      = pb.PushFirmwareTaskReq
	ReplyItem                = pb.ReplyItem
	ReplyWorkOrderReq        = pb.ReplyWorkOrderReq
	UpdateWorkOrderStatusReq = pb.UpdateWorkOrderStatusReq
	WorkOrderItem            = pb.WorkOrderItem
	WorkOrderStatusResp      = pb.WorkOrderStatusResp

	Device interface {
		AddDevice(ctx context.Context, in *AddDeviceReq, opts ...grpc.CallOption) (*DeviceResp, error)
		UpdateDevice(ctx context.Context, in *DeviceResp, opts ...grpc.CallOption) (*DeviceResp, error)
		GetDevice(ctx context.Context, in *GetDeviceReq, opts ...grpc.CallOption) (*DeviceResp, error)
		DeleteDevice(ctx context.Context, in *DeleteDeviceReq, opts ...grpc.CallOption) (*DeleteDeviceResp, error)
		ListDevice(ctx context.Context, in *ListDeviceReq, opts ...grpc.CallOption) (*ListDeviceResp, error)
		AddApp(ctx context.Context, in *AddAppReq, opts ...grpc.CallOption) (*AppResp, error)
		UpdateApp(ctx context.Context, in *AppResp, opts ...grpc.CallOption) (*AppResp, error)
		GetApp(ctx context.Context, in *GetAppReq, opts ...grpc.CallOption) (*AppResp, error)
		DeleteApp(ctx context.Context, in *DeleteAppReq, opts ...grpc.CallOption) (*DeleteAppResp, error)
		ListApp(ctx context.Context, in *ListAppReq, opts ...grpc.CallOption) (*ListAppResp, error)
		AddDeviceEvent(ctx context.Context, in *AddDeviceEventReq, opts ...grpc.CallOption) (*DeviceEventResp, error)
		DeleteDeviceEvent(ctx context.Context, in *DeleteDeviceEventReq, opts ...grpc.CallOption) (*DeleteDeviceEventResp, error)
		GetDeviceEvent(ctx context.Context, in *GetDeviceEventReq, opts ...grpc.CallOption) (*DeviceEventResp, error)
		ListDeviceEvent(ctx context.Context, in *ListDeviceEventReq, opts ...grpc.CallOption) (*ListDeviceEventResp, error)
		GetDeviceStats(ctx context.Context, in *GetDeviceStatsReq, opts ...grpc.CallOption) (*DeviceStatsResp, error)
		AddFirmware(ctx context.Context, in *AddFirmwareReq, opts ...grpc.CallOption) (*FirmwareResp, error)
		UpdateFirmware(ctx context.Context, in *FirmwareResp, opts ...grpc.CallOption) (*FirmwareResp, error)
		GetFirmware(ctx context.Context, in *GetFirmwareReq, opts ...grpc.CallOption) (*FirmwareResp, error)
		DeleteFirmware(ctx context.Context, in *DeleteFirmwareReq, opts ...grpc.CallOption) (*DeleteFirmwareResp, error)
		ListFirmware(ctx context.Context, in *ListFirmwareReq, opts ...grpc.CallOption) (*ListFirmwareResp, error)
		PushFirmwareTask(ctx context.Context, in *PushFirmwareTaskReq, opts ...grpc.CallOption) (*FirmwareTaskResp, error)
		GetFirmwareTask(ctx context.Context, in *GetFirmwareTaskReq, opts ...grpc.CallOption) (*FirmwareTaskResp, error)
		ListFirmwareTask(ctx context.Context, in *ListFirmwareTaskReq, opts ...grpc.CallOption) (*ListFirmwareTaskResp, error)
		AddWorkOrder(ctx context.Context, in *AddWorkOrderReq, opts ...grpc.CallOption) (*WorkOrderItem, error)
		GetWorkOrder(ctx context.Context, in *GetWorkOrderReq, opts ...grpc.CallOption) (*GetWorkOrderResp, error)
		ListWorkOrder(ctx context.Context, in *ListWorkOrderReq, opts ...grpc.CallOption) (*ListWorkOrderResp, error)
		ReplyWorkOrder(ctx context.Context, in *ReplyWorkOrderReq, opts ...grpc.CallOption) (*ReplyItem, error)
		UpdateWorkOrderStatus(ctx context.Context, in *UpdateWorkOrderStatusReq, opts ...grpc.CallOption) (*WorkOrderStatusResp, error)
		GetMqttMessages(ctx context.Context, in *GetMqttMessagesReq, opts ...grpc.CallOption) (*GetMqttMessagesResp, error)
	}

	defaultDevice struct {
		cli zrpc.Client
	}
)

func NewDevice(cli zrpc.Client) Device {
	return &defaultDevice{
		cli: cli,
	}
}

func (m *defaultDevice) AddDevice(ctx context.Context, in *AddDeviceReq, opts ...grpc.CallOption) (*DeviceResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.AddDevice(ctx, in, opts...)
}

func (m *defaultDevice) UpdateDevice(ctx context.Context, in *DeviceResp, opts ...grpc.CallOption) (*DeviceResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.UpdateDevice(ctx, in, opts...)
}

func (m *defaultDevice) GetDevice(ctx context.Context, in *GetDeviceReq, opts ...grpc.CallOption) (*DeviceResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.GetDevice(ctx, in, opts...)
}

func (m *defaultDevice) DeleteDevice(ctx context.Context, in *DeleteDeviceReq, opts ...grpc.CallOption) (*DeleteDeviceResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.DeleteDevice(ctx, in, opts...)
}

func (m *defaultDevice) ListDevice(ctx context.Context, in *ListDeviceReq, opts ...grpc.CallOption) (*ListDeviceResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.ListDevice(ctx, in, opts...)
}

func (m *defaultDevice) AddApp(ctx context.Context, in *AddAppReq, opts ...grpc.CallOption) (*AppResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.AddApp(ctx, in, opts...)
}

func (m *defaultDevice) UpdateApp(ctx context.Context, in *AppResp, opts ...grpc.CallOption) (*AppResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.UpdateApp(ctx, in, opts...)
}

func (m *defaultDevice) GetApp(ctx context.Context, in *GetAppReq, opts ...grpc.CallOption) (*AppResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.GetApp(ctx, in, opts...)
}

func (m *defaultDevice) DeleteApp(ctx context.Context, in *DeleteAppReq, opts ...grpc.CallOption) (*DeleteAppResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.DeleteApp(ctx, in, opts...)
}

func (m *defaultDevice) ListApp(ctx context.Context, in *ListAppReq, opts ...grpc.CallOption) (*ListAppResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.ListApp(ctx, in, opts...)
}

func (m *defaultDevice) AddDeviceEvent(ctx context.Context, in *AddDeviceEventReq, opts ...grpc.CallOption) (*DeviceEventResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.AddDeviceEvent(ctx, in, opts...)
}

func (m *defaultDevice) DeleteDeviceEvent(ctx context.Context, in *DeleteDeviceEventReq, opts ...grpc.CallOption) (*DeleteDeviceEventResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.DeleteDeviceEvent(ctx, in, opts...)
}

func (m *defaultDevice) GetDeviceEvent(ctx context.Context, in *GetDeviceEventReq, opts ...grpc.CallOption) (*DeviceEventResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.GetDeviceEvent(ctx, in, opts...)
}

func (m *defaultDevice) ListDeviceEvent(ctx context.Context, in *ListDeviceEventReq, opts ...grpc.CallOption) (*ListDeviceEventResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.ListDeviceEvent(ctx, in, opts...)
}

func (m *defaultDevice) GetDeviceStats(ctx context.Context, in *GetDeviceStatsReq, opts ...grpc.CallOption) (*DeviceStatsResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.GetDeviceStats(ctx, in, opts...)
}

func (m *defaultDevice) AddFirmware(ctx context.Context, in *AddFirmwareReq, opts ...grpc.CallOption) (*FirmwareResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.AddFirmware(ctx, in, opts...)
}

func (m *defaultDevice) UpdateFirmware(ctx context.Context, in *FirmwareResp, opts ...grpc.CallOption) (*FirmwareResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.UpdateFirmware(ctx, in, opts...)
}

func (m *defaultDevice) GetFirmware(ctx context.Context, in *GetFirmwareReq, opts ...grpc.CallOption) (*FirmwareResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.GetFirmware(ctx, in, opts...)
}

func (m *defaultDevice) DeleteFirmware(ctx context.Context, in *DeleteFirmwareReq, opts ...grpc.CallOption) (*DeleteFirmwareResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.DeleteFirmware(ctx, in, opts...)
}

func (m *defaultDevice) ListFirmware(ctx context.Context, in *ListFirmwareReq, opts ...grpc.CallOption) (*ListFirmwareResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.ListFirmware(ctx, in, opts...)
}

func (m *defaultDevice) PushFirmwareTask(ctx context.Context, in *PushFirmwareTaskReq, opts ...grpc.CallOption) (*FirmwareTaskResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.PushFirmwareTask(ctx, in, opts...)
}

func (m *defaultDevice) GetFirmwareTask(ctx context.Context, in *GetFirmwareTaskReq, opts ...grpc.CallOption) (*FirmwareTaskResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.GetFirmwareTask(ctx, in, opts...)
}

func (m *defaultDevice) ListFirmwareTask(ctx context.Context, in *ListFirmwareTaskReq, opts ...grpc.CallOption) (*ListFirmwareTaskResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.ListFirmwareTask(ctx, in, opts...)
}

func (m *defaultDevice) AddWorkOrder(ctx context.Context, in *AddWorkOrderReq, opts ...grpc.CallOption) (*WorkOrderItem, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.AddWorkOrder(ctx, in, opts...)
}

func (m *defaultDevice) GetWorkOrder(ctx context.Context, in *GetWorkOrderReq, opts ...grpc.CallOption) (*GetWorkOrderResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.GetWorkOrder(ctx, in, opts...)
}

func (m *defaultDevice) ListWorkOrder(ctx context.Context, in *ListWorkOrderReq, opts ...grpc.CallOption) (*ListWorkOrderResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.ListWorkOrder(ctx, in, opts...)
}

func (m *defaultDevice) ReplyWorkOrder(ctx context.Context, in *ReplyWorkOrderReq, opts ...grpc.CallOption) (*ReplyItem, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.ReplyWorkOrder(ctx, in, opts...)
}

func (m *defaultDevice) UpdateWorkOrderStatus(ctx context.Context, in *UpdateWorkOrderStatusReq, opts ...grpc.CallOption) (*WorkOrderStatusResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.UpdateWorkOrderStatus(ctx, in, opts...)
}

func (m *defaultDevice) GetMqttMessages(ctx context.Context, in *GetMqttMessagesReq, opts ...grpc.CallOption) (*GetMqttMessagesResp, error) {
	client := pb.NewDeviceClient(m.cli.Conn())
	return client.GetMqttMessages(ctx, in, opts...)
}
