// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: ai.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TEXT_TO_IMAGE TaskType = 0
	TaskType_VIDEO         TaskType = 1
	TaskType_AUDIO         TaskType = 2
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TEXT_TO_IMAGE",
		1: "VIDEO",
		2: "AUDIO",
	}
	TaskType_value = map[string]int32{
		"TEXT_TO_IMAGE": 0,
		"VIDEO":         1,
		"AUDIO":         2,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_ai_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

type SubmitTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      TaskType               `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3,enum=ai.TaskType" json:"task_type,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Params        string                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskReq) Reset() {
	*x = SubmitTaskReq{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskReq) ProtoMessage() {}

func (x *SubmitTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskReq.ProtoReflect.Descriptor instead.
func (*SubmitTaskReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTaskReq) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TEXT_TO_IMAGE
}

func (x *SubmitTaskReq) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SubmitTaskReq) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *SubmitTaskReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SubmitTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResp) Reset() {
	*x = SubmitTaskResp{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResp) ProtoMessage() {}

func (x *SubmitTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResp.ProtoReflect.Descriptor instead.
func (*SubmitTaskResp) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTaskResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubmitTaskResp) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskReq) Reset() {
	*x = GetTaskReq{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReq) ProtoMessage() {}

func (x *GetTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReq.ProtoReflect.Descriptor instead.
func (*GetTaskReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTaskReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType      TaskType               `protobuf:"varint,4,opt,name=task_type,json=taskType,proto3,enum=ai.TaskType" json:"task_type,omitempty"`
	Prompt        string                 `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`
	RequestInfo   string                 `protobuf:"bytes,6,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	ResponseInfo  string                 `protobuf:"bytes,7,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	ResultUrl     string                 `protobuf:"bytes,8,opt,name=result_url,json=resultUrl,proto3" json:"result_url,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,10,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResp) Reset() {
	*x = GetTaskResp{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResp) ProtoMessage() {}

func (x *GetTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResp.ProtoReflect.Descriptor instead.
func (*GetTaskResp) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTaskResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTaskResp) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskResp) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TEXT_TO_IMAGE
}

func (x *GetTaskResp) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GetTaskResp) GetRequestInfo() string {
	if x != nil {
		return x.RequestInfo
	}
	return ""
}

func (x *GetTaskResp) GetResponseInfo() string {
	if x != nil {
		return x.ResponseInfo
	}
	return ""
}

func (x *GetTaskResp) GetResultUrl() string {
	if x != nil {
		return x.ResultUrl
	}
	return ""
}

func (x *GetTaskResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTaskResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *GetTaskResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetTaskResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type UpdateTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ResponseInfo  string                 `protobuf:"bytes,3,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	ResultUrl     string                 `protobuf:"bytes,4,opt,name=result_url,json=resultUrl,proto3" json:"result_url,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskReq) Reset() {
	*x = UpdateTaskReq{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskReq) ProtoMessage() {}

func (x *UpdateTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskReq.ProtoReflect.Descriptor instead.
func (*UpdateTaskReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTaskReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTaskReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateTaskReq) GetResponseInfo() string {
	if x != nil {
		return x.ResponseInfo
	}
	return ""
}

func (x *UpdateTaskReq) GetResultUrl() string {
	if x != nil {
		return x.ResultUrl
	}
	return ""
}

func (x *UpdateTaskReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateTaskReq) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type UpdateTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResp) Reset() {
	*x = UpdateTaskResp{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResp) ProtoMessage() {}

func (x *UpdateTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResp.ProtoReflect.Descriptor instead.
func (*UpdateTaskResp) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTaskResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType      TaskType               `protobuf:"varint,4,opt,name=task_type,json=taskType,proto3,enum=ai.TaskType" json:"task_type,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	UserId        int64                  `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksReq) Reset() {
	*x = ListTasksReq{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksReq) ProtoMessage() {}

func (x *ListTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksReq.ProtoReflect.Descriptor instead.
func (*ListTasksReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListTasksReq) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TEXT_TO_IMAGE
}

func (x *ListTasksReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListTasksReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListTasksResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*GetTaskResp         `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResp) Reset() {
	*x = ListTasksResp{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResp) ProtoMessage() {}

func (x *ListTasksResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResp.ProtoReflect.Descriptor instead.
func (*ListTasksResp) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

func (x *ListTasksResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTasksResp) GetList() []*GetTaskResp {
	if x != nil {
		return x.List
	}
	return nil
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"\x83\x01\n" +
	"\rSubmitTaskReq\x12)\n" +
	"\ttask_type\x18\x01 \x01(\x0e2\f.ai.TaskTypeR\btaskType\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06params\x18\x03 \x01(\tR\x06params\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"9\n" +
	"\x0eSubmitTaskResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"5\n" +
	"\n" +
	"GetTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xec\x02\n" +
	"\vGetTaskResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12)\n" +
	"\ttask_type\x18\x04 \x01(\x0e2\f.ai.TaskTypeR\btaskType\x12\x16\n" +
	"\x06prompt\x18\x05 \x01(\tR\x06prompt\x12!\n" +
	"\frequest_info\x18\x06 \x01(\tR\vrequestInfo\x12#\n" +
	"\rresponse_info\x18\a \x01(\tR\fresponseInfo\x12\x1d\n" +
	"\n" +
	"result_url\x18\b \x01(\tR\tresultUrl\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1b\n" +
	"\terror_msg\x18\n" +
	" \x01(\tR\berrorMsg\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\"\xb1\x01\n" +
	"\rUpdateTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12#\n" +
	"\rresponse_info\x18\x03 \x01(\tR\fresponseInfo\x12\x1d\n" +
	"\n" +
	"result_url\x18\x04 \x01(\tR\tresultUrl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1b\n" +
	"\terror_msg\x18\x06 \x01(\tR\berrorMsg\"*\n" +
	"\x0eUpdateTaskResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb4\x01\n" +
	"\fListTasksReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12)\n" +
	"\ttask_type\x18\x04 \x01(\x0e2\f.ai.TaskTypeR\btaskType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\x03R\x06userId\"J\n" +
	"\rListTasksResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12#\n" +
	"\x04list\x18\x02 \x03(\v2\x0f.ai.GetTaskRespR\x04list*3\n" +
	"\bTaskType\x12\x11\n" +
	"\rTEXT_TO_IMAGE\x10\x00\x12\t\n" +
	"\x05VIDEO\x10\x01\x12\t\n" +
	"\x05AUDIO\x10\x022\xcf\x01\n" +
	"\x05AiRpc\x123\n" +
	"\n" +
	"SubmitTask\x12\x11.ai.SubmitTaskReq\x1a\x12.ai.SubmitTaskResp\x12*\n" +
	"\aGetTask\x12\x0e.ai.GetTaskReq\x1a\x0f.ai.GetTaskResp\x123\n" +
	"\n" +
	"UpdateTask\x12\x11.ai.UpdateTaskReq\x1a\x12.ai.UpdateTaskResp\x120\n" +
	"\tListTasks\x12\x10.ai.ListTasksReq\x1a\x11.ai.ListTasksRespB\x06Z\x04./pbb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ai_proto_goTypes = []any{
	(TaskType)(0),          // 0: ai.TaskType
	(*SubmitTaskReq)(nil),  // 1: ai.SubmitTaskReq
	(*SubmitTaskResp)(nil), // 2: ai.SubmitTaskResp
	(*GetTaskReq)(nil),     // 3: ai.GetTaskReq
	(*GetTaskResp)(nil),    // 4: ai.GetTaskResp
	(*UpdateTaskReq)(nil),  // 5: ai.UpdateTaskReq
	(*UpdateTaskResp)(nil), // 6: ai.UpdateTaskResp
	(*ListTasksReq)(nil),   // 7: ai.ListTasksReq
	(*ListTasksResp)(nil),  // 8: ai.ListTasksResp
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: ai.SubmitTaskReq.task_type:type_name -> ai.TaskType
	0, // 1: ai.GetTaskResp.task_type:type_name -> ai.TaskType
	0, // 2: ai.ListTasksReq.task_type:type_name -> ai.TaskType
	4, // 3: ai.ListTasksResp.list:type_name -> ai.GetTaskResp
	1, // 4: ai.AiRpc.SubmitTask:input_type -> ai.SubmitTaskReq
	3, // 5: ai.AiRpc.GetTask:input_type -> ai.GetTaskReq
	5, // 6: ai.AiRpc.UpdateTask:input_type -> ai.UpdateTaskReq
	7, // 7: ai.AiRpc.ListTasks:input_type -> ai.ListTasksReq
	2, // 8: ai.AiRpc.SubmitTask:output_type -> ai.SubmitTaskResp
	4, // 9: ai.AiRpc.GetTask:output_type -> ai.GetTaskResp
	6, // 10: ai.AiRpc.UpdateTask:output_type -> ai.UpdateTaskResp
	8, // 11: ai.AiRpc.ListTasks:output_type -> ai.ListTasksResp
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		EnumInfos:         file_ai_proto_enumTypes,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
