// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: baseCode.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseCode_AddBaseCodeSort_FullMethodName    = "/base_code.BaseCode/AddBaseCodeSort"
	BaseCode_UpdateBaseCodeSort_FullMethodName = "/base_code.BaseCode/UpdateBaseCodeSort"
	BaseCode_GetBaseCodeSort_FullMethodName    = "/base_code.BaseCode/GetBaseCodeSort"
	BaseCode_DeleteBaseCodeSort_FullMethodName = "/base_code.BaseCode/DeleteBaseCodeSort"
	BaseCode_ListBaseCodeSort_FullMethodName   = "/base_code.BaseCode/ListBaseCodeSort"
	BaseCode_AddBaseCode_FullMethodName        = "/base_code.BaseCode/AddBaseCode"
	BaseCode_GetBaseCode_FullMethodName        = "/base_code.BaseCode/GetBaseCode"
	BaseCode_UpdateBaseCode_FullMethodName     = "/base_code.BaseCode/UpdateBaseCode"
	BaseCode_DeleteBaseCode_FullMethodName     = "/base_code.BaseCode/DeleteBaseCode"
	BaseCode_ListBaseCode_FullMethodName       = "/base_code.BaseCode/ListBaseCode"
	BaseCode_AddBaseCodeItem_FullMethodName    = "/base_code.BaseCode/AddBaseCodeItem"
	BaseCode_GetBaseCodeItem_FullMethodName    = "/base_code.BaseCode/GetBaseCodeItem"
	BaseCode_UpdateBaseCodeItem_FullMethodName = "/base_code.BaseCode/UpdateBaseCodeItem"
	BaseCode_DeleteBaseCodeItem_FullMethodName = "/base_code.BaseCode/DeleteBaseCodeItem"
	BaseCode_ListBaseCodeItem_FullMethodName   = "/base_code.BaseCode/ListBaseCodeItem"
)

// BaseCodeClient is the client API for BaseCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseCodeClient interface {
	AddBaseCodeSort(ctx context.Context, in *AddBaseCodeSortReq, opts ...grpc.CallOption) (*BaseCodeSortResp, error)
	UpdateBaseCodeSort(ctx context.Context, in *BaseCodeSortResp, opts ...grpc.CallOption) (*BaseCodeSortResp, error)
	GetBaseCodeSort(ctx context.Context, in *GetBaseCodeSortReq, opts ...grpc.CallOption) (*BaseCodeSortResp, error)
	DeleteBaseCodeSort(ctx context.Context, in *DeleteBaseCodeSortReq, opts ...grpc.CallOption) (*DeleteBaseCodeSortResp, error)
	ListBaseCodeSort(ctx context.Context, in *ListBaseCodeSortReq, opts ...grpc.CallOption) (*ListBaseCodeSortResp, error)
	AddBaseCode(ctx context.Context, in *AddBaseCodeReq, opts ...grpc.CallOption) (*BaseCodeResp, error)
	GetBaseCode(ctx context.Context, in *GetBaseCodeReq, opts ...grpc.CallOption) (*BaseCodeResp, error)
	UpdateBaseCode(ctx context.Context, in *BaseCodeResp, opts ...grpc.CallOption) (*BaseCodeResp, error)
	DeleteBaseCode(ctx context.Context, in *DeleteBaseCodeReq, opts ...grpc.CallOption) (*DeleteBaseCodeResp, error)
	ListBaseCode(ctx context.Context, in *ListBaseCodeReq, opts ...grpc.CallOption) (*ListBaseCodeResp, error)
	AddBaseCodeItem(ctx context.Context, in *AddBaseCodeItemReq, opts ...grpc.CallOption) (*BaseCodeItemResp, error)
	GetBaseCodeItem(ctx context.Context, in *GetBaseCodeItemReq, opts ...grpc.CallOption) (*BaseCodeItemResp, error)
	UpdateBaseCodeItem(ctx context.Context, in *BaseCodeItemResp, opts ...grpc.CallOption) (*BaseCodeItemResp, error)
	DeleteBaseCodeItem(ctx context.Context, in *DeleteBaseCodeItemReq, opts ...grpc.CallOption) (*DeleteBaseCodeItemResp, error)
	ListBaseCodeItem(ctx context.Context, in *ListBaseCodeItemReq, opts ...grpc.CallOption) (*ListBaseCodeItemResp, error)
}

type baseCodeClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseCodeClient(cc grpc.ClientConnInterface) BaseCodeClient {
	return &baseCodeClient{cc}
}

func (c *baseCodeClient) AddBaseCodeSort(ctx context.Context, in *AddBaseCodeSortReq, opts ...grpc.CallOption) (*BaseCodeSortResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseCodeSortResp)
	err := c.cc.Invoke(ctx, BaseCode_AddBaseCodeSort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) UpdateBaseCodeSort(ctx context.Context, in *BaseCodeSortResp, opts ...grpc.CallOption) (*BaseCodeSortResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseCodeSortResp)
	err := c.cc.Invoke(ctx, BaseCode_UpdateBaseCodeSort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) GetBaseCodeSort(ctx context.Context, in *GetBaseCodeSortReq, opts ...grpc.CallOption) (*BaseCodeSortResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseCodeSortResp)
	err := c.cc.Invoke(ctx, BaseCode_GetBaseCodeSort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) DeleteBaseCodeSort(ctx context.Context, in *DeleteBaseCodeSortReq, opts ...grpc.CallOption) (*DeleteBaseCodeSortResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBaseCodeSortResp)
	err := c.cc.Invoke(ctx, BaseCode_DeleteBaseCodeSort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) ListBaseCodeSort(ctx context.Context, in *ListBaseCodeSortReq, opts ...grpc.CallOption) (*ListBaseCodeSortResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBaseCodeSortResp)
	err := c.cc.Invoke(ctx, BaseCode_ListBaseCodeSort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) AddBaseCode(ctx context.Context, in *AddBaseCodeReq, opts ...grpc.CallOption) (*BaseCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseCodeResp)
	err := c.cc.Invoke(ctx, BaseCode_AddBaseCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) GetBaseCode(ctx context.Context, in *GetBaseCodeReq, opts ...grpc.CallOption) (*BaseCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseCodeResp)
	err := c.cc.Invoke(ctx, BaseCode_GetBaseCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) UpdateBaseCode(ctx context.Context, in *BaseCodeResp, opts ...grpc.CallOption) (*BaseCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseCodeResp)
	err := c.cc.Invoke(ctx, BaseCode_UpdateBaseCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) DeleteBaseCode(ctx context.Context, in *DeleteBaseCodeReq, opts ...grpc.CallOption) (*DeleteBaseCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBaseCodeResp)
	err := c.cc.Invoke(ctx, BaseCode_DeleteBaseCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) ListBaseCode(ctx context.Context, in *ListBaseCodeReq, opts ...grpc.CallOption) (*ListBaseCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBaseCodeResp)
	err := c.cc.Invoke(ctx, BaseCode_ListBaseCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) AddBaseCodeItem(ctx context.Context, in *AddBaseCodeItemReq, opts ...grpc.CallOption) (*BaseCodeItemResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseCodeItemResp)
	err := c.cc.Invoke(ctx, BaseCode_AddBaseCodeItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) GetBaseCodeItem(ctx context.Context, in *GetBaseCodeItemReq, opts ...grpc.CallOption) (*BaseCodeItemResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseCodeItemResp)
	err := c.cc.Invoke(ctx, BaseCode_GetBaseCodeItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) UpdateBaseCodeItem(ctx context.Context, in *BaseCodeItemResp, opts ...grpc.CallOption) (*BaseCodeItemResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseCodeItemResp)
	err := c.cc.Invoke(ctx, BaseCode_UpdateBaseCodeItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) DeleteBaseCodeItem(ctx context.Context, in *DeleteBaseCodeItemReq, opts ...grpc.CallOption) (*DeleteBaseCodeItemResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBaseCodeItemResp)
	err := c.cc.Invoke(ctx, BaseCode_DeleteBaseCodeItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCodeClient) ListBaseCodeItem(ctx context.Context, in *ListBaseCodeItemReq, opts ...grpc.CallOption) (*ListBaseCodeItemResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBaseCodeItemResp)
	err := c.cc.Invoke(ctx, BaseCode_ListBaseCodeItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseCodeServer is the server API for BaseCode service.
// All implementations must embed UnimplementedBaseCodeServer
// for forward compatibility.
type BaseCodeServer interface {
	AddBaseCodeSort(context.Context, *AddBaseCodeSortReq) (*BaseCodeSortResp, error)
	UpdateBaseCodeSort(context.Context, *BaseCodeSortResp) (*BaseCodeSortResp, error)
	GetBaseCodeSort(context.Context, *GetBaseCodeSortReq) (*BaseCodeSortResp, error)
	DeleteBaseCodeSort(context.Context, *DeleteBaseCodeSortReq) (*DeleteBaseCodeSortResp, error)
	ListBaseCodeSort(context.Context, *ListBaseCodeSortReq) (*ListBaseCodeSortResp, error)
	AddBaseCode(context.Context, *AddBaseCodeReq) (*BaseCodeResp, error)
	GetBaseCode(context.Context, *GetBaseCodeReq) (*BaseCodeResp, error)
	UpdateBaseCode(context.Context, *BaseCodeResp) (*BaseCodeResp, error)
	DeleteBaseCode(context.Context, *DeleteBaseCodeReq) (*DeleteBaseCodeResp, error)
	ListBaseCode(context.Context, *ListBaseCodeReq) (*ListBaseCodeResp, error)
	AddBaseCodeItem(context.Context, *AddBaseCodeItemReq) (*BaseCodeItemResp, error)
	GetBaseCodeItem(context.Context, *GetBaseCodeItemReq) (*BaseCodeItemResp, error)
	UpdateBaseCodeItem(context.Context, *BaseCodeItemResp) (*BaseCodeItemResp, error)
	DeleteBaseCodeItem(context.Context, *DeleteBaseCodeItemReq) (*DeleteBaseCodeItemResp, error)
	ListBaseCodeItem(context.Context, *ListBaseCodeItemReq) (*ListBaseCodeItemResp, error)
	mustEmbedUnimplementedBaseCodeServer()
}

// UnimplementedBaseCodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseCodeServer struct{}

func (UnimplementedBaseCodeServer) AddBaseCodeSort(context.Context, *AddBaseCodeSortReq) (*BaseCodeSortResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBaseCodeSort not implemented")
}
func (UnimplementedBaseCodeServer) UpdateBaseCodeSort(context.Context, *BaseCodeSortResp) (*BaseCodeSortResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBaseCodeSort not implemented")
}
func (UnimplementedBaseCodeServer) GetBaseCodeSort(context.Context, *GetBaseCodeSortReq) (*BaseCodeSortResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaseCodeSort not implemented")
}
func (UnimplementedBaseCodeServer) DeleteBaseCodeSort(context.Context, *DeleteBaseCodeSortReq) (*DeleteBaseCodeSortResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBaseCodeSort not implemented")
}
func (UnimplementedBaseCodeServer) ListBaseCodeSort(context.Context, *ListBaseCodeSortReq) (*ListBaseCodeSortResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBaseCodeSort not implemented")
}
func (UnimplementedBaseCodeServer) AddBaseCode(context.Context, *AddBaseCodeReq) (*BaseCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBaseCode not implemented")
}
func (UnimplementedBaseCodeServer) GetBaseCode(context.Context, *GetBaseCodeReq) (*BaseCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaseCode not implemented")
}
func (UnimplementedBaseCodeServer) UpdateBaseCode(context.Context, *BaseCodeResp) (*BaseCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBaseCode not implemented")
}
func (UnimplementedBaseCodeServer) DeleteBaseCode(context.Context, *DeleteBaseCodeReq) (*DeleteBaseCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBaseCode not implemented")
}
func (UnimplementedBaseCodeServer) ListBaseCode(context.Context, *ListBaseCodeReq) (*ListBaseCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBaseCode not implemented")
}
func (UnimplementedBaseCodeServer) AddBaseCodeItem(context.Context, *AddBaseCodeItemReq) (*BaseCodeItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBaseCodeItem not implemented")
}
func (UnimplementedBaseCodeServer) GetBaseCodeItem(context.Context, *GetBaseCodeItemReq) (*BaseCodeItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaseCodeItem not implemented")
}
func (UnimplementedBaseCodeServer) UpdateBaseCodeItem(context.Context, *BaseCodeItemResp) (*BaseCodeItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBaseCodeItem not implemented")
}
func (UnimplementedBaseCodeServer) DeleteBaseCodeItem(context.Context, *DeleteBaseCodeItemReq) (*DeleteBaseCodeItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBaseCodeItem not implemented")
}
func (UnimplementedBaseCodeServer) ListBaseCodeItem(context.Context, *ListBaseCodeItemReq) (*ListBaseCodeItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBaseCodeItem not implemented")
}
func (UnimplementedBaseCodeServer) mustEmbedUnimplementedBaseCodeServer() {}
func (UnimplementedBaseCodeServer) testEmbeddedByValue()                  {}

// UnsafeBaseCodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseCodeServer will
// result in compilation errors.
type UnsafeBaseCodeServer interface {
	mustEmbedUnimplementedBaseCodeServer()
}

func RegisterBaseCodeServer(s grpc.ServiceRegistrar, srv BaseCodeServer) {
	// If the following call pancis, it indicates UnimplementedBaseCodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseCode_ServiceDesc, srv)
}

func _BaseCode_AddBaseCodeSort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBaseCodeSortReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).AddBaseCodeSort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_AddBaseCodeSort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).AddBaseCodeSort(ctx, req.(*AddBaseCodeSortReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_UpdateBaseCodeSort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseCodeSortResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).UpdateBaseCodeSort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_UpdateBaseCodeSort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).UpdateBaseCodeSort(ctx, req.(*BaseCodeSortResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_GetBaseCodeSort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBaseCodeSortReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).GetBaseCodeSort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_GetBaseCodeSort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).GetBaseCodeSort(ctx, req.(*GetBaseCodeSortReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_DeleteBaseCodeSort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBaseCodeSortReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).DeleteBaseCodeSort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_DeleteBaseCodeSort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).DeleteBaseCodeSort(ctx, req.(*DeleteBaseCodeSortReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_ListBaseCodeSort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBaseCodeSortReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).ListBaseCodeSort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_ListBaseCodeSort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).ListBaseCodeSort(ctx, req.(*ListBaseCodeSortReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_AddBaseCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBaseCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).AddBaseCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_AddBaseCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).AddBaseCode(ctx, req.(*AddBaseCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_GetBaseCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBaseCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).GetBaseCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_GetBaseCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).GetBaseCode(ctx, req.(*GetBaseCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_UpdateBaseCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseCodeResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).UpdateBaseCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_UpdateBaseCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).UpdateBaseCode(ctx, req.(*BaseCodeResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_DeleteBaseCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBaseCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).DeleteBaseCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_DeleteBaseCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).DeleteBaseCode(ctx, req.(*DeleteBaseCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_ListBaseCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBaseCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).ListBaseCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_ListBaseCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).ListBaseCode(ctx, req.(*ListBaseCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_AddBaseCodeItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBaseCodeItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).AddBaseCodeItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_AddBaseCodeItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).AddBaseCodeItem(ctx, req.(*AddBaseCodeItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_GetBaseCodeItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBaseCodeItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).GetBaseCodeItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_GetBaseCodeItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).GetBaseCodeItem(ctx, req.(*GetBaseCodeItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_UpdateBaseCodeItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseCodeItemResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).UpdateBaseCodeItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_UpdateBaseCodeItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).UpdateBaseCodeItem(ctx, req.(*BaseCodeItemResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_DeleteBaseCodeItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBaseCodeItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).DeleteBaseCodeItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_DeleteBaseCodeItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).DeleteBaseCodeItem(ctx, req.(*DeleteBaseCodeItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseCode_ListBaseCodeItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBaseCodeItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCodeServer).ListBaseCodeItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseCode_ListBaseCodeItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCodeServer).ListBaseCodeItem(ctx, req.(*ListBaseCodeItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseCode_ServiceDesc is the grpc.ServiceDesc for BaseCode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseCode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "base_code.BaseCode",
	HandlerType: (*BaseCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBaseCodeSort",
			Handler:    _BaseCode_AddBaseCodeSort_Handler,
		},
		{
			MethodName: "UpdateBaseCodeSort",
			Handler:    _BaseCode_UpdateBaseCodeSort_Handler,
		},
		{
			MethodName: "GetBaseCodeSort",
			Handler:    _BaseCode_GetBaseCodeSort_Handler,
		},
		{
			MethodName: "DeleteBaseCodeSort",
			Handler:    _BaseCode_DeleteBaseCodeSort_Handler,
		},
		{
			MethodName: "ListBaseCodeSort",
			Handler:    _BaseCode_ListBaseCodeSort_Handler,
		},
		{
			MethodName: "AddBaseCode",
			Handler:    _BaseCode_AddBaseCode_Handler,
		},
		{
			MethodName: "GetBaseCode",
			Handler:    _BaseCode_GetBaseCode_Handler,
		},
		{
			MethodName: "UpdateBaseCode",
			Handler:    _BaseCode_UpdateBaseCode_Handler,
		},
		{
			MethodName: "DeleteBaseCode",
			Handler:    _BaseCode_DeleteBaseCode_Handler,
		},
		{
			MethodName: "ListBaseCode",
			Handler:    _BaseCode_ListBaseCode_Handler,
		},
		{
			MethodName: "AddBaseCodeItem",
			Handler:    _BaseCode_AddBaseCodeItem_Handler,
		},
		{
			MethodName: "GetBaseCodeItem",
			Handler:    _BaseCode_GetBaseCodeItem_Handler,
		},
		{
			MethodName: "UpdateBaseCodeItem",
			Handler:    _BaseCode_UpdateBaseCodeItem_Handler,
		},
		{
			MethodName: "DeleteBaseCodeItem",
			Handler:    _BaseCode_DeleteBaseCodeItem_Handler,
		},
		{
			MethodName: "ListBaseCodeItem",
			Handler:    _BaseCode_ListBaseCodeItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baseCode.proto",
}
