// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: device.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MacAddress    string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	InternalIp    string                 `protobuf:"bytes,4,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	BmpImage      string                 `protobuf:"bytes,5,opt,name=bmp_image,json=bmpImage,proto3" json:"bmp_image,omitempty"`
	IsRunning     int64                  `protobuf:"varint,6,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	ExtraData     string                 `protobuf:"bytes,7,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	Firmware      string                 `protobuf:"bytes,8,opt,name=firmware,proto3" json:"firmware,omitempty"`
	DeviceGroup   string                 `protobuf:"bytes,9,opt,name=device_group,json=deviceGroup,proto3" json:"device_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDeviceReq) Reset() {
	*x = AddDeviceReq{}
	mi := &file_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceReq) ProtoMessage() {}

func (x *AddDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeviceReq.ProtoReflect.Descriptor instead.
func (*AddDeviceReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{0}
}

func (x *AddDeviceReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddDeviceReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddDeviceReq) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *AddDeviceReq) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *AddDeviceReq) GetBmpImage() string {
	if x != nil {
		return x.BmpImage
	}
	return ""
}

func (x *AddDeviceReq) GetIsRunning() int64 {
	if x != nil {
		return x.IsRunning
	}
	return 0
}

func (x *AddDeviceReq) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

func (x *AddDeviceReq) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *AddDeviceReq) GetDeviceGroup() string {
	if x != nil {
		return x.DeviceGroup
	}
	return ""
}

type DeviceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint64                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MacAddress    string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	InternalIp    string                 `protobuf:"bytes,5,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	BmpImage      string                 `protobuf:"bytes,6,opt,name=bmp_image,json=bmpImage,proto3" json:"bmp_image,omitempty"`
	IsRunning     int64                  `protobuf:"varint,7,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	ExtraData     string                 `protobuf:"bytes,8,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	IsDelete      int64                  `protobuf:"varint,9,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	CreateTime    uint64                 `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    uint64                 `protobuf:"varint,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Firmware      string                 `protobuf:"bytes,12,opt,name=firmware,proto3" json:"firmware,omitempty"`
	DeviceGroup   string                 `protobuf:"bytes,13,opt,name=device_group,json=deviceGroup,proto3" json:"device_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceResp) Reset() {
	*x = DeviceResp{}
	mi := &file_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceResp) ProtoMessage() {}

func (x *DeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceResp.ProtoReflect.Descriptor instead.
func (*DeviceResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceResp) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeviceResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeviceResp) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *DeviceResp) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *DeviceResp) GetBmpImage() string {
	if x != nil {
		return x.BmpImage
	}
	return ""
}

func (x *DeviceResp) GetIsRunning() int64 {
	if x != nil {
		return x.IsRunning
	}
	return 0
}

func (x *DeviceResp) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

func (x *DeviceResp) GetIsDelete() int64 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

func (x *DeviceResp) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *DeviceResp) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *DeviceResp) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *DeviceResp) GetDeviceGroup() string {
	if x != nil {
		return x.DeviceGroup
	}
	return ""
}

type GetDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint64                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceReq) Reset() {
	*x = GetDeviceReq{}
	mi := &file_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceReq) ProtoMessage() {}

func (x *GetDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceReq.ProtoReflect.Descriptor instead.
func (*GetDeviceReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeviceReq) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *GetDeviceReq) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type DeleteDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint64                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceReq) Reset() {
	*x = DeleteDeviceReq{}
	mi := &file_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceReq) ProtoMessage() {}

func (x *DeleteDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceReq.ProtoReflect.Descriptor instead.
func (*DeleteDeviceReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteDeviceReq) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeleteDeviceReq) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type DeleteDeviceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceResp) Reset() {
	*x = DeleteDeviceResp{}
	mi := &file_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceResp) ProtoMessage() {}

func (x *DeleteDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceResp.ProtoReflect.Descriptor instead.
func (*DeleteDeviceResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDeviceResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MacAddress    string                 `protobuf:"bytes,5,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	InternalIp    string                 `protobuf:"bytes,6,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	IsRunning     int64                  `protobuf:"varint,7,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	IsDelete      int64                  `protobuf:"varint,8,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	Firmware      string                 `protobuf:"bytes,9,opt,name=firmware,proto3" json:"firmware,omitempty"`
	DeviceGroup   string                 `protobuf:"bytes,10,opt,name=device_group,json=deviceGroup,proto3" json:"device_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceReq) Reset() {
	*x = ListDeviceReq{}
	mi := &file_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceReq) ProtoMessage() {}

func (x *ListDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceReq.ProtoReflect.Descriptor instead.
func (*ListDeviceReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{5}
}

func (x *ListDeviceReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDeviceReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDeviceReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListDeviceReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListDeviceReq) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *ListDeviceReq) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *ListDeviceReq) GetIsRunning() int64 {
	if x != nil {
		return x.IsRunning
	}
	return 0
}

func (x *ListDeviceReq) GetIsDelete() int64 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

func (x *ListDeviceReq) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *ListDeviceReq) GetDeviceGroup() string {
	if x != nil {
		return x.DeviceGroup
	}
	return ""
}

type ListDeviceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*DeviceResp          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceResp) Reset() {
	*x = ListDeviceResp{}
	mi := &file_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceResp) ProtoMessage() {}

func (x *ListDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceResp.ProtoReflect.Descriptor instead.
func (*ListDeviceResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{6}
}

func (x *ListDeviceResp) GetList() []*DeviceResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListDeviceResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ==================== App ====================
type AddAppReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AppKey        string                 `protobuf:"bytes,2,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Vendor        string                 `protobuf:"bytes,5,opt,name=vendor,proto3" json:"vendor,omitempty"`
	IconBg        string                 `protobuf:"bytes,6,opt,name=icon_bg,json=iconBg,proto3" json:"icon_bg,omitempty"`
	IconColor     string                 `protobuf:"bytes,7,opt,name=icon_color,json=iconColor,proto3" json:"icon_color,omitempty"`
	IconLabel     string                 `protobuf:"bytes,8,opt,name=icon_label,json=iconLabel,proto3" json:"icon_label,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	SensorType    string                 `protobuf:"bytes,10,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	ExtraData     string                 `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAppReq) Reset() {
	*x = AddAppReq{}
	mi := &file_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppReq) ProtoMessage() {}

func (x *AddAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppReq.ProtoReflect.Descriptor instead.
func (*AddAppReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{7}
}

func (x *AddAppReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddAppReq) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *AddAppReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AddAppReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AddAppReq) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *AddAppReq) GetIconBg() string {
	if x != nil {
		return x.IconBg
	}
	return ""
}

func (x *AddAppReq) GetIconColor() string {
	if x != nil {
		return x.IconColor
	}
	return ""
}

func (x *AddAppReq) GetIconLabel() string {
	if x != nil {
		return x.IconLabel
	}
	return ""
}

func (x *AddAppReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddAppReq) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *AddAppReq) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

type AppResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         uint64                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AppKey        string                 `protobuf:"bytes,3,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Vendor        string                 `protobuf:"bytes,6,opt,name=vendor,proto3" json:"vendor,omitempty"`
	IconBg        string                 `protobuf:"bytes,7,opt,name=icon_bg,json=iconBg,proto3" json:"icon_bg,omitempty"`
	IconColor     string                 `protobuf:"bytes,8,opt,name=icon_color,json=iconColor,proto3" json:"icon_color,omitempty"`
	IconLabel     string                 `protobuf:"bytes,9,opt,name=icon_label,json=iconLabel,proto3" json:"icon_label,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	SensorType    string                 `protobuf:"bytes,11,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	ExtraData     string                 `protobuf:"bytes,12,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	IsDelete      int64                  `protobuf:"varint,13,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	CreateTime    uint64                 `protobuf:"varint,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    uint64                 `protobuf:"varint,15,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppResp) Reset() {
	*x = AppResp{}
	mi := &file_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppResp) ProtoMessage() {}

func (x *AppResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppResp.ProtoReflect.Descriptor instead.
func (*AppResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{8}
}

func (x *AppResp) GetAppId() uint64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AppResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppResp) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *AppResp) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AppResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AppResp) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *AppResp) GetIconBg() string {
	if x != nil {
		return x.IconBg
	}
	return ""
}

func (x *AppResp) GetIconColor() string {
	if x != nil {
		return x.IconColor
	}
	return ""
}

func (x *AppResp) GetIconLabel() string {
	if x != nil {
		return x.IconLabel
	}
	return ""
}

func (x *AppResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AppResp) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *AppResp) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

func (x *AppResp) GetIsDelete() int64 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

func (x *AppResp) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AppResp) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type GetAppReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         uint64                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppKey        string                 `protobuf:"bytes,2,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppReq) Reset() {
	*x = GetAppReq{}
	mi := &file_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppReq) ProtoMessage() {}

func (x *GetAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppReq.ProtoReflect.Descriptor instead.
func (*GetAppReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{9}
}

func (x *GetAppReq) GetAppId() uint64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetAppReq) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

type DeleteAppReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         uint64                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppKey        string                 `protobuf:"bytes,2,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppReq) Reset() {
	*x = DeleteAppReq{}
	mi := &file_device_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppReq) ProtoMessage() {}

func (x *DeleteAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppReq.ProtoReflect.Descriptor instead.
func (*DeleteAppReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAppReq) GetAppId() uint64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *DeleteAppReq) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

type DeleteAppResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppResp) Reset() {
	*x = DeleteAppResp{}
	mi := &file_device_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppResp) ProtoMessage() {}

func (x *DeleteAppResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppResp.ProtoReflect.Descriptor instead.
func (*DeleteAppResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAppResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListAppReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AppKey        string                 `protobuf:"bytes,4,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	SensorType    string                 `protobuf:"bytes,6,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	IsDelete      int64                  `protobuf:"varint,7,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppReq) Reset() {
	*x = ListAppReq{}
	mi := &file_device_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppReq) ProtoMessage() {}

func (x *ListAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppReq.ProtoReflect.Descriptor instead.
func (*ListAppReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{12}
}

func (x *ListAppReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAppReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAppReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListAppReq) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *ListAppReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListAppReq) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *ListAppReq) GetIsDelete() int64 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

type ListAppResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AppResp             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppResp) Reset() {
	*x = ListAppResp{}
	mi := &file_device_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppResp) ProtoMessage() {}

func (x *ListAppResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppResp.ProtoReflect.Descriptor instead.
func (*ListAppResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{13}
}

func (x *ListAppResp) GetList() []*AppResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListAppResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ==================== Event ====================
type DeviceEventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceEventId uint64                 `protobuf:"varint,1,opt,name=device_event_id,json=deviceEventId,proto3" json:"device_event_id,omitempty"`
	DeviceId      uint64                 `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventLevel    string                 `protobuf:"bytes,4,opt,name=event_level,json=eventLevel,proto3" json:"event_level,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	ExtraData     string                 `protobuf:"bytes,8,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	IsDelete      int64                  `protobuf:"varint,9,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	CreateTime    uint64                 `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceEventResp) Reset() {
	*x = DeviceEventResp{}
	mi := &file_device_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceEventResp) ProtoMessage() {}

func (x *DeviceEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceEventResp.ProtoReflect.Descriptor instead.
func (*DeviceEventResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{14}
}

func (x *DeviceEventResp) GetDeviceEventId() uint64 {
	if x != nil {
		return x.DeviceEventId
	}
	return 0
}

func (x *DeviceEventResp) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeviceEventResp) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *DeviceEventResp) GetEventLevel() string {
	if x != nil {
		return x.EventLevel
	}
	return ""
}

func (x *DeviceEventResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DeviceEventResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeviceEventResp) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DeviceEventResp) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

func (x *DeviceEventResp) GetIsDelete() int64 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

func (x *DeviceEventResp) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type GetDeviceEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceEventId uint64                 `protobuf:"varint,1,opt,name=device_event_id,json=deviceEventId,proto3" json:"device_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceEventReq) Reset() {
	*x = GetDeviceEventReq{}
	mi := &file_device_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceEventReq) ProtoMessage() {}

func (x *GetDeviceEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceEventReq.ProtoReflect.Descriptor instead.
func (*GetDeviceEventReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{15}
}

func (x *GetDeviceEventReq) GetDeviceEventId() uint64 {
	if x != nil {
		return x.DeviceEventId
	}
	return 0
}

type DeleteDeviceEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceEventId uint64                 `protobuf:"varint,1,opt,name=device_event_id,json=deviceEventId,proto3" json:"device_event_id,omitempty"`
	DeviceId      uint64                 `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceEventReq) Reset() {
	*x = DeleteDeviceEventReq{}
	mi := &file_device_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceEventReq) ProtoMessage() {}

func (x *DeleteDeviceEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceEventReq.ProtoReflect.Descriptor instead.
func (*DeleteDeviceEventReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteDeviceEventReq) GetDeviceEventId() uint64 {
	if x != nil {
		return x.DeviceEventId
	}
	return 0
}

func (x *DeleteDeviceEventReq) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type DeleteDeviceEventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceEventResp) Reset() {
	*x = DeleteDeviceEventResp{}
	mi := &file_device_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceEventResp) ProtoMessage() {}

func (x *DeleteDeviceEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceEventResp.ProtoReflect.Descriptor instead.
func (*DeleteDeviceEventResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteDeviceEventResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListDeviceEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	DeviceId      uint64                 `protobuf:"varint,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventLevel    string                 `protobuf:"bytes,5,opt,name=event_level,json=eventLevel,proto3" json:"event_level,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	IsDelete      int64                  `protobuf:"varint,7,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceEventReq) Reset() {
	*x = ListDeviceEventReq{}
	mi := &file_device_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceEventReq) ProtoMessage() {}

func (x *ListDeviceEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceEventReq.ProtoReflect.Descriptor instead.
func (*ListDeviceEventReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{18}
}

func (x *ListDeviceEventReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDeviceEventReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDeviceEventReq) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ListDeviceEventReq) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ListDeviceEventReq) GetEventLevel() string {
	if x != nil {
		return x.EventLevel
	}
	return ""
}

func (x *ListDeviceEventReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListDeviceEventReq) GetIsDelete() int64 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

type ListDeviceEventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*DeviceEventResp     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceEventResp) Reset() {
	*x = ListDeviceEventResp{}
	mi := &file_device_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceEventResp) ProtoMessage() {}

func (x *ListDeviceEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceEventResp.ProtoReflect.Descriptor instead.
func (*ListDeviceEventResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{19}
}

func (x *ListDeviceEventResp) GetList() []*DeviceEventResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListDeviceEventResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AddDeviceEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint64                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventLevel    string                 `protobuf:"bytes,3,opt,name=event_level,json=eventLevel,proto3" json:"event_level,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	ExtraData     string                 `protobuf:"bytes,7,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDeviceEventReq) Reset() {
	*x = AddDeviceEventReq{}
	mi := &file_device_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeviceEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceEventReq) ProtoMessage() {}

func (x *AddDeviceEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeviceEventReq.ProtoReflect.Descriptor instead.
func (*AddDeviceEventReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{20}
}

func (x *AddDeviceEventReq) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *AddDeviceEventReq) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AddDeviceEventReq) GetEventLevel() string {
	if x != nil {
		return x.EventLevel
	}
	return ""
}

func (x *AddDeviceEventReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddDeviceEventReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddDeviceEventReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AddDeviceEventReq) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

type GetDeviceStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStatsReq) Reset() {
	*x = GetDeviceStatsReq{}
	mi := &file_device_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStatsReq) ProtoMessage() {}

func (x *GetDeviceStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStatsReq.ProtoReflect.Descriptor instead.
func (*GetDeviceStatsReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{21}
}

type DeviceStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Online        int64                  `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	Offline       int64                  `protobuf:"varint,3,opt,name=offline,proto3" json:"offline,omitempty"`
	Warning       int64                  `protobuf:"varint,4,opt,name=warning,proto3" json:"warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatsResp) Reset() {
	*x = DeviceStatsResp{}
	mi := &file_device_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatsResp) ProtoMessage() {}

func (x *DeviceStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatsResp.ProtoReflect.Descriptor instead.
func (*DeviceStatsResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{22}
}

func (x *DeviceStatsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DeviceStatsResp) GetOnline() int64 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *DeviceStatsResp) GetOffline() int64 {
	if x != nil {
		return x.Offline
	}
	return 0
}

func (x *DeviceStatsResp) GetWarning() int64 {
	if x != nil {
		return x.Warning
	}
	return 0
}

// ==================== Firmware ====================
type AddFirmwareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	DeviceType    string                 `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	FileUrl       string                 `protobuf:"bytes,4,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Md5           string                 `protobuf:"bytes,6,opt,name=md5,proto3" json:"md5,omitempty"`
	Changelog     string                 `protobuf:"bytes,7,opt,name=changelog,proto3" json:"changelog,omitempty"`
	IsForce       int64                  `protobuf:"varint,8,opt,name=is_force,json=isForce,proto3" json:"is_force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFirmwareReq) Reset() {
	*x = AddFirmwareReq{}
	mi := &file_device_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFirmwareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFirmwareReq) ProtoMessage() {}

func (x *AddFirmwareReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFirmwareReq.ProtoReflect.Descriptor instead.
func (*AddFirmwareReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{23}
}

func (x *AddFirmwareReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddFirmwareReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AddFirmwareReq) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *AddFirmwareReq) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *AddFirmwareReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *AddFirmwareReq) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *AddFirmwareReq) GetChangelog() string {
	if x != nil {
		return x.Changelog
	}
	return ""
}

func (x *AddFirmwareReq) GetIsForce() int64 {
	if x != nil {
		return x.IsForce
	}
	return 0
}

type FirmwareResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirmwareId    uint64                 `protobuf:"varint,1,opt,name=firmware_id,json=firmwareId,proto3" json:"firmware_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	DeviceType    string                 `protobuf:"bytes,4,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	FileUrl       string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileSize      int64                  `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Md5           string                 `protobuf:"bytes,7,opt,name=md5,proto3" json:"md5,omitempty"`
	Changelog     string                 `protobuf:"bytes,8,opt,name=changelog,proto3" json:"changelog,omitempty"`
	IsForce       int64                  `protobuf:"varint,9,opt,name=is_force,json=isForce,proto3" json:"is_force,omitempty"`
	IsDelete      int64                  `protobuf:"varint,10,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	CreateTime    uint64                 `protobuf:"varint,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    uint64                 `protobuf:"varint,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareResp) Reset() {
	*x = FirmwareResp{}
	mi := &file_device_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareResp) ProtoMessage() {}

func (x *FirmwareResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareResp.ProtoReflect.Descriptor instead.
func (*FirmwareResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{24}
}

func (x *FirmwareResp) GetFirmwareId() uint64 {
	if x != nil {
		return x.FirmwareId
	}
	return 0
}

func (x *FirmwareResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FirmwareResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FirmwareResp) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *FirmwareResp) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *FirmwareResp) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FirmwareResp) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *FirmwareResp) GetChangelog() string {
	if x != nil {
		return x.Changelog
	}
	return ""
}

func (x *FirmwareResp) GetIsForce() int64 {
	if x != nil {
		return x.IsForce
	}
	return 0
}

func (x *FirmwareResp) GetIsDelete() int64 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

func (x *FirmwareResp) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FirmwareResp) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type GetFirmwareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirmwareId    uint64                 `protobuf:"varint,1,opt,name=firmware_id,json=firmwareId,proto3" json:"firmware_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFirmwareReq) Reset() {
	*x = GetFirmwareReq{}
	mi := &file_device_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFirmwareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFirmwareReq) ProtoMessage() {}

func (x *GetFirmwareReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFirmwareReq.ProtoReflect.Descriptor instead.
func (*GetFirmwareReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{25}
}

func (x *GetFirmwareReq) GetFirmwareId() uint64 {
	if x != nil {
		return x.FirmwareId
	}
	return 0
}

type DeleteFirmwareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirmwareId    uint64                 `protobuf:"varint,1,opt,name=firmware_id,json=firmwareId,proto3" json:"firmware_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFirmwareReq) Reset() {
	*x = DeleteFirmwareReq{}
	mi := &file_device_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFirmwareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFirmwareReq) ProtoMessage() {}

func (x *DeleteFirmwareReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFirmwareReq.ProtoReflect.Descriptor instead.
func (*DeleteFirmwareReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteFirmwareReq) GetFirmwareId() uint64 {
	if x != nil {
		return x.FirmwareId
	}
	return 0
}

type DeleteFirmwareResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFirmwareResp) Reset() {
	*x = DeleteFirmwareResp{}
	mi := &file_device_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFirmwareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFirmwareResp) ProtoMessage() {}

func (x *DeleteFirmwareResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFirmwareResp.ProtoReflect.Descriptor instead.
func (*DeleteFirmwareResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteFirmwareResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListFirmwareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	DeviceType    string                 `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	IsForce       int64                  `protobuf:"varint,6,opt,name=is_force,json=isForce,proto3" json:"is_force,omitempty"`
	IsDelete      int64                  `protobuf:"varint,7,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFirmwareReq) Reset() {
	*x = ListFirmwareReq{}
	mi := &file_device_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFirmwareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFirmwareReq) ProtoMessage() {}

func (x *ListFirmwareReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFirmwareReq.ProtoReflect.Descriptor instead.
func (*ListFirmwareReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{28}
}

func (x *ListFirmwareReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFirmwareReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFirmwareReq) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *ListFirmwareReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ListFirmwareReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListFirmwareReq) GetIsForce() int64 {
	if x != nil {
		return x.IsForce
	}
	return 0
}

func (x *ListFirmwareReq) GetIsDelete() int64 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

type ListFirmwareResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*FirmwareResp        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFirmwareResp) Reset() {
	*x = ListFirmwareResp{}
	mi := &file_device_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFirmwareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFirmwareResp) ProtoMessage() {}

func (x *ListFirmwareResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFirmwareResp.ProtoReflect.Descriptor instead.
func (*ListFirmwareResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{29}
}

func (x *ListFirmwareResp) GetList() []*FirmwareResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListFirmwareResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ==================== FirmwareTask ====================
type PushFirmwareTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirmwareId    uint64                 `protobuf:"varint,1,opt,name=firmware_id,json=firmwareId,proto3" json:"firmware_id,omitempty"`
	DeviceIds     []uint64               `protobuf:"varint,2,rep,packed,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFirmwareTaskReq) Reset() {
	*x = PushFirmwareTaskReq{}
	mi := &file_device_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFirmwareTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFirmwareTaskReq) ProtoMessage() {}

func (x *PushFirmwareTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFirmwareTaskReq.ProtoReflect.Descriptor instead.
func (*PushFirmwareTaskReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{30}
}

func (x *PushFirmwareTaskReq) GetFirmwareId() uint64 {
	if x != nil {
		return x.FirmwareId
	}
	return 0
}

func (x *PushFirmwareTaskReq) GetDeviceIds() []uint64 {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

type FirmwareTaskResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FirmwareTaskId uint64                 `protobuf:"varint,1,opt,name=firmware_task_id,json=firmwareTaskId,proto3" json:"firmware_task_id,omitempty"`
	FirmwareId     uint64                 `protobuf:"varint,2,opt,name=firmware_id,json=firmwareId,proto3" json:"firmware_id,omitempty"`
	DeviceId       uint64                 `protobuf:"varint,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status         int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Progress       int64                  `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	ErrorMsg       string                 `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	StartedAt      uint64                 `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    uint64                 `protobuf:"varint,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreateTime     uint64                 `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime     uint64                 `protobuf:"varint,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FirmwareTaskResp) Reset() {
	*x = FirmwareTaskResp{}
	mi := &file_device_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareTaskResp) ProtoMessage() {}

func (x *FirmwareTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareTaskResp.ProtoReflect.Descriptor instead.
func (*FirmwareTaskResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{31}
}

func (x *FirmwareTaskResp) GetFirmwareTaskId() uint64 {
	if x != nil {
		return x.FirmwareTaskId
	}
	return 0
}

func (x *FirmwareTaskResp) GetFirmwareId() uint64 {
	if x != nil {
		return x.FirmwareId
	}
	return 0
}

func (x *FirmwareTaskResp) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *FirmwareTaskResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FirmwareTaskResp) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *FirmwareTaskResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *FirmwareTaskResp) GetStartedAt() uint64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *FirmwareTaskResp) GetCompletedAt() uint64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *FirmwareTaskResp) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FirmwareTaskResp) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type GetFirmwareTaskReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FirmwareTaskId uint64                 `protobuf:"varint,1,opt,name=firmware_task_id,json=firmwareTaskId,proto3" json:"firmware_task_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFirmwareTaskReq) Reset() {
	*x = GetFirmwareTaskReq{}
	mi := &file_device_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFirmwareTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFirmwareTaskReq) ProtoMessage() {}

func (x *GetFirmwareTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFirmwareTaskReq.ProtoReflect.Descriptor instead.
func (*GetFirmwareTaskReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{32}
}

func (x *GetFirmwareTaskReq) GetFirmwareTaskId() uint64 {
	if x != nil {
		return x.FirmwareTaskId
	}
	return 0
}

type ListFirmwareTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	FirmwareId    uint64                 `protobuf:"varint,3,opt,name=firmware_id,json=firmwareId,proto3" json:"firmware_id,omitempty"`
	DeviceId      uint64                 `protobuf:"varint,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFirmwareTaskReq) Reset() {
	*x = ListFirmwareTaskReq{}
	mi := &file_device_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFirmwareTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFirmwareTaskReq) ProtoMessage() {}

func (x *ListFirmwareTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFirmwareTaskReq.ProtoReflect.Descriptor instead.
func (*ListFirmwareTaskReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{33}
}

func (x *ListFirmwareTaskReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFirmwareTaskReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFirmwareTaskReq) GetFirmwareId() uint64 {
	if x != nil {
		return x.FirmwareId
	}
	return 0
}

func (x *ListFirmwareTaskReq) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ListFirmwareTaskReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListFirmwareTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*FirmwareTaskResp    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFirmwareTaskResp) Reset() {
	*x = ListFirmwareTaskResp{}
	mi := &file_device_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFirmwareTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFirmwareTaskResp) ProtoMessage() {}

func (x *ListFirmwareTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFirmwareTaskResp.ProtoReflect.Descriptor instead.
func (*ListFirmwareTaskResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{34}
}

func (x *ListFirmwareTaskResp) GetList() []*FirmwareTaskResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListFirmwareTaskResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_device_proto protoreflect.FileDescriptor

const file_device_proto_rawDesc = "" +
	"\n" +
	"\fdevice.proto\x12\x06device\"\x97\x02\n" +
	"\fAddDeviceReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12\x1f\n" +
	"\vinternal_ip\x18\x04 \x01(\tR\n" +
	"internalIp\x12\x1b\n" +
	"\tbmp_image\x18\x05 \x01(\tR\bbmpImage\x12\x1d\n" +
	"\n" +
	"is_running\x18\x06 \x01(\x03R\tisRunning\x12\x1d\n" +
	"\n" +
	"extra_data\x18\a \x01(\tR\textraData\x12\x1a\n" +
	"\bfirmware\x18\b \x01(\tR\bfirmware\x12!\n" +
	"\fdevice_group\x18\t \x01(\tR\vdeviceGroup\"\x91\x03\n" +
	"\n" +
	"DeviceResp\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x04R\bdeviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\x12\x1f\n" +
	"\vinternal_ip\x18\x05 \x01(\tR\n" +
	"internalIp\x12\x1b\n" +
	"\tbmp_image\x18\x06 \x01(\tR\bbmpImage\x12\x1d\n" +
	"\n" +
	"is_running\x18\a \x01(\x03R\tisRunning\x12\x1d\n" +
	"\n" +
	"extra_data\x18\b \x01(\tR\textraData\x12\x1b\n" +
	"\tis_delete\x18\t \x01(\x03R\bisDelete\x12\x1f\n" +
	"\vcreate_time\x18\n" +
	" \x01(\x04R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\v \x01(\x04R\n" +
	"updateTime\x12\x1a\n" +
	"\bfirmware\x18\f \x01(\tR\bfirmware\x12!\n" +
	"\fdevice_group\x18\r \x01(\tR\vdeviceGroup\"L\n" +
	"\fGetDeviceReq\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x04R\bdeviceId\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\"O\n" +
	"\x0fDeleteDeviceReq\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x04R\bdeviceId\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\",\n" +
	"\x10DeleteDeviceResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xaa\x02\n" +
	"\rListDeviceReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vmac_address\x18\x05 \x01(\tR\n" +
	"macAddress\x12\x1f\n" +
	"\vinternal_ip\x18\x06 \x01(\tR\n" +
	"internalIp\x12\x1d\n" +
	"\n" +
	"is_running\x18\a \x01(\x03R\tisRunning\x12\x1b\n" +
	"\tis_delete\x18\b \x01(\x03R\bisDelete\x12\x1a\n" +
	"\bfirmware\x18\t \x01(\tR\bfirmware\x12!\n" +
	"\fdevice_group\x18\n" +
	" \x01(\tR\vdeviceGroup\"N\n" +
	"\x0eListDeviceResp\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.device.DeviceRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xbf\x02\n" +
	"\tAddAppReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\aapp_key\x18\x02 \x01(\tR\x06appKey\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06vendor\x18\x05 \x01(\tR\x06vendor\x12\x17\n" +
	"\aicon_bg\x18\x06 \x01(\tR\x06iconBg\x12\x1d\n" +
	"\n" +
	"icon_color\x18\a \x01(\tR\ticonColor\x12\x1d\n" +
	"\n" +
	"icon_label\x18\b \x01(\tR\ticonLabel\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1f\n" +
	"\vsensor_type\x18\n" +
	" \x01(\tR\n" +
	"sensorType\x12\x1d\n" +
	"\n" +
	"extra_data\x18\v \x01(\tR\textraData\"\xb3\x03\n" +
	"\aAppResp\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x04R\x05appId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aapp_key\x18\x03 \x01(\tR\x06appKey\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x16\n" +
	"\x06vendor\x18\x06 \x01(\tR\x06vendor\x12\x17\n" +
	"\aicon_bg\x18\a \x01(\tR\x06iconBg\x12\x1d\n" +
	"\n" +
	"icon_color\x18\b \x01(\tR\ticonColor\x12\x1d\n" +
	"\n" +
	"icon_label\x18\t \x01(\tR\ticonLabel\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x1f\n" +
	"\vsensor_type\x18\v \x01(\tR\n" +
	"sensorType\x12\x1d\n" +
	"\n" +
	"extra_data\x18\f \x01(\tR\textraData\x12\x1b\n" +
	"\tis_delete\x18\r \x01(\x03R\bisDelete\x12\x1f\n" +
	"\vcreate_time\x18\x0e \x01(\x04R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x0f \x01(\x04R\n" +
	"updateTime\";\n" +
	"\tGetAppReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x04R\x05appId\x12\x17\n" +
	"\aapp_key\x18\x02 \x01(\tR\x06appKey\">\n" +
	"\fDeleteAppReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x04R\x05appId\x12\x17\n" +
	"\aapp_key\x18\x02 \x01(\tR\x06appKey\")\n" +
	"\rDeleteAppResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc4\x01\n" +
	"\n" +
	"ListAppReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\aapp_key\x18\x04 \x01(\tR\x06appKey\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1f\n" +
	"\vsensor_type\x18\x06 \x01(\tR\n" +
	"sensorType\x12\x1b\n" +
	"\tis_delete\x18\a \x01(\x03R\bisDelete\"H\n" +
	"\vListAppResp\x12#\n" +
	"\x04list\x18\x01 \x03(\v2\x0f.device.AppRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xc3\x02\n" +
	"\x0fDeviceEventResp\x12&\n" +
	"\x0fdevice_event_id\x18\x01 \x01(\x04R\rdeviceEventId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\x04R\bdeviceId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1f\n" +
	"\vevent_level\x18\x04 \x01(\tR\n" +
	"eventLevel\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"extra_data\x18\b \x01(\tR\textraData\x12\x1b\n" +
	"\tis_delete\x18\t \x01(\x03R\bisDelete\x12\x1f\n" +
	"\vcreate_time\x18\n" +
	" \x01(\x04R\n" +
	"createTime\";\n" +
	"\x11GetDeviceEventReq\x12&\n" +
	"\x0fdevice_event_id\x18\x01 \x01(\x04R\rdeviceEventId\"[\n" +
	"\x14DeleteDeviceEventReq\x12&\n" +
	"\x0fdevice_event_id\x18\x01 \x01(\x04R\rdeviceEventId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\x04R\bdeviceId\"1\n" +
	"\x15DeleteDeviceEventResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd7\x01\n" +
	"\x12ListDeviceEventReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\x04R\bdeviceId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x1f\n" +
	"\vevent_level\x18\x05 \x01(\tR\n" +
	"eventLevel\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1b\n" +
	"\tis_delete\x18\a \x01(\x03R\bisDelete\"X\n" +
	"\x13ListDeviceEventResp\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.device.DeviceEventRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xdf\x01\n" +
	"\x11AddDeviceEventReq\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x04R\bdeviceId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1f\n" +
	"\vevent_level\x18\x03 \x01(\tR\n" +
	"eventLevel\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"extra_data\x18\a \x01(\tR\textraData\"\x13\n" +
	"\x11GetDeviceStatsReq\"s\n" +
	"\x0fDeviceStatsResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x16\n" +
	"\x06online\x18\x02 \x01(\x03R\x06online\x12\x18\n" +
	"\aoffline\x18\x03 \x01(\x03R\aoffline\x12\x18\n" +
	"\awarning\x18\x04 \x01(\x03R\awarning\"\xe2\x01\n" +
	"\x0eAddFirmwareReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x19\n" +
	"\bfile_url\x18\x04 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\x12\x10\n" +
	"\x03md5\x18\x06 \x01(\tR\x03md5\x12\x1c\n" +
	"\tchangelog\x18\a \x01(\tR\tchangelog\x12\x19\n" +
	"\bis_force\x18\b \x01(\x03R\aisForce\"\xe0\x02\n" +
	"\fFirmwareResp\x12\x1f\n" +
	"\vfirmware_id\x18\x01 \x01(\x04R\n" +
	"firmwareId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vdevice_type\x18\x04 \x01(\tR\n" +
	"deviceType\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\x03R\bfileSize\x12\x10\n" +
	"\x03md5\x18\a \x01(\tR\x03md5\x12\x1c\n" +
	"\tchangelog\x18\b \x01(\tR\tchangelog\x12\x19\n" +
	"\bis_force\x18\t \x01(\x03R\aisForce\x12\x1b\n" +
	"\tis_delete\x18\n" +
	" \x01(\x03R\bisDelete\x12\x1f\n" +
	"\vcreate_time\x18\v \x01(\x04R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\f \x01(\x04R\n" +
	"updateTime\"1\n" +
	"\x0eGetFirmwareReq\x12\x1f\n" +
	"\vfirmware_id\x18\x01 \x01(\x04R\n" +
	"firmwareId\"4\n" +
	"\x11DeleteFirmwareReq\x12\x1f\n" +
	"\vfirmware_id\x18\x01 \x01(\x04R\n" +
	"firmwareId\".\n" +
	"\x12DeleteFirmwareResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc9\x01\n" +
	"\x0fListFirmwareReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x19\n" +
	"\bis_force\x18\x06 \x01(\x03R\aisForce\x12\x1b\n" +
	"\tis_delete\x18\a \x01(\x03R\bisDelete\"R\n" +
	"\x10ListFirmwareResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.device.FirmwareRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"U\n" +
	"\x13PushFirmwareTaskReq\x12\x1f\n" +
	"\vfirmware_id\x18\x01 \x01(\x04R\n" +
	"firmwareId\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x02 \x03(\x04R\tdeviceIds\"\xcf\x02\n" +
	"\x10FirmwareTaskResp\x12(\n" +
	"\x10firmware_task_id\x18\x01 \x01(\x04R\x0efirmwareTaskId\x12\x1f\n" +
	"\vfirmware_id\x18\x02 \x01(\x04R\n" +
	"firmwareId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\x04R\bdeviceId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x03R\bprogress\x12\x1b\n" +
	"\terror_msg\x18\x06 \x01(\tR\berrorMsg\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x04R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\x04R\vcompletedAt\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\x04R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\n" +
	" \x01(\x04R\n" +
	"updateTime\">\n" +
	"\x12GetFirmwareTaskReq\x12(\n" +
	"\x10firmware_task_id\x18\x01 \x01(\x04R\x0efirmwareTaskId\"\x9c\x01\n" +
	"\x13ListFirmwareTaskReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1f\n" +
	"\vfirmware_id\x18\x03 \x01(\x04R\n" +
	"firmwareId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\x04R\bdeviceId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\"Z\n" +
	"\x14ListFirmwareTaskResp\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.device.FirmwareTaskRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xbe\v\n" +
	"\x06Device\x125\n" +
	"\tAddDevice\x12\x14.device.AddDeviceReq\x1a\x12.device.DeviceResp\x126\n" +
	"\fUpdateDevice\x12\x12.device.DeviceResp\x1a\x12.device.DeviceResp\x125\n" +
	"\tGetDevice\x12\x14.device.GetDeviceReq\x1a\x12.device.DeviceResp\x12A\n" +
	"\fDeleteDevice\x12\x17.device.DeleteDeviceReq\x1a\x18.device.DeleteDeviceResp\x12;\n" +
	"\n" +
	"ListDevice\x12\x15.device.ListDeviceReq\x1a\x16.device.ListDeviceResp\x12,\n" +
	"\x06AddApp\x12\x11.device.AddAppReq\x1a\x0f.device.AppResp\x12-\n" +
	"\tUpdateApp\x12\x0f.device.AppResp\x1a\x0f.device.AppResp\x12,\n" +
	"\x06GetApp\x12\x11.device.GetAppReq\x1a\x0f.device.AppResp\x128\n" +
	"\tDeleteApp\x12\x14.device.DeleteAppReq\x1a\x15.device.DeleteAppResp\x122\n" +
	"\aListApp\x12\x12.device.ListAppReq\x1a\x13.device.ListAppResp\x12D\n" +
	"\x0eAddDeviceEvent\x12\x19.device.AddDeviceEventReq\x1a\x17.device.DeviceEventResp\x12P\n" +
	"\x11DeleteDeviceEvent\x12\x1c.device.DeleteDeviceEventReq\x1a\x1d.device.DeleteDeviceEventResp\x12D\n" +
	"\x0eGetDeviceEvent\x12\x19.device.GetDeviceEventReq\x1a\x17.device.DeviceEventResp\x12J\n" +
	"\x0fListDeviceEvent\x12\x1a.device.ListDeviceEventReq\x1a\x1b.device.ListDeviceEventResp\x12D\n" +
	"\x0eGetDeviceStats\x12\x19.device.GetDeviceStatsReq\x1a\x17.device.DeviceStatsResp\x12;\n" +
	"\vAddFirmware\x12\x16.device.AddFirmwareReq\x1a\x14.device.FirmwareResp\x12<\n" +
	"\x0eUpdateFirmware\x12\x14.device.FirmwareResp\x1a\x14.device.FirmwareResp\x12;\n" +
	"\vGetFirmware\x12\x16.device.GetFirmwareReq\x1a\x14.device.FirmwareResp\x12G\n" +
	"\x0eDeleteFirmware\x12\x19.device.DeleteFirmwareReq\x1a\x1a.device.DeleteFirmwareResp\x12A\n" +
	"\fListFirmware\x12\x17.device.ListFirmwareReq\x1a\x18.device.ListFirmwareResp\x12I\n" +
	"\x10PushFirmwareTask\x12\x1b.device.PushFirmwareTaskReq\x1a\x18.device.FirmwareTaskResp\x12G\n" +
	"\x0fGetFirmwareTask\x12\x1a.device.GetFirmwareTaskReq\x1a\x18.device.FirmwareTaskResp\x12M\n" +
	"\x10ListFirmwareTask\x12\x1b.device.ListFirmwareTaskReq\x1a\x1c.device.ListFirmwareTaskRespB\x06Z\x04./pbb\x06proto3"

var (
	file_device_proto_rawDescOnce sync.Once
	file_device_proto_rawDescData []byte
)

func file_device_proto_rawDescGZIP() []byte {
	file_device_proto_rawDescOnce.Do(func() {
		file_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)))
	})
	return file_device_proto_rawDescData
}

var file_device_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_device_proto_goTypes = []any{
	(*AddDeviceReq)(nil),          // 0: device.AddDeviceReq
	(*DeviceResp)(nil),            // 1: device.DeviceResp
	(*GetDeviceReq)(nil),          // 2: device.GetDeviceReq
	(*DeleteDeviceReq)(nil),       // 3: device.DeleteDeviceReq
	(*DeleteDeviceResp)(nil),      // 4: device.DeleteDeviceResp
	(*ListDeviceReq)(nil),         // 5: device.ListDeviceReq
	(*ListDeviceResp)(nil),        // 6: device.ListDeviceResp
	(*AddAppReq)(nil),             // 7: device.AddAppReq
	(*AppResp)(nil),               // 8: device.AppResp
	(*GetAppReq)(nil),             // 9: device.GetAppReq
	(*DeleteAppReq)(nil),          // 10: device.DeleteAppReq
	(*DeleteAppResp)(nil),         // 11: device.DeleteAppResp
	(*ListAppReq)(nil),            // 12: device.ListAppReq
	(*ListAppResp)(nil),           // 13: device.ListAppResp
	(*DeviceEventResp)(nil),       // 14: device.DeviceEventResp
	(*GetDeviceEventReq)(nil),     // 15: device.GetDeviceEventReq
	(*DeleteDeviceEventReq)(nil),  // 16: device.DeleteDeviceEventReq
	(*DeleteDeviceEventResp)(nil), // 17: device.DeleteDeviceEventResp
	(*ListDeviceEventReq)(nil),    // 18: device.ListDeviceEventReq
	(*ListDeviceEventResp)(nil),   // 19: device.ListDeviceEventResp
	(*AddDeviceEventReq)(nil),     // 20: device.AddDeviceEventReq
	(*GetDeviceStatsReq)(nil),     // 21: device.GetDeviceStatsReq
	(*DeviceStatsResp)(nil),       // 22: device.DeviceStatsResp
	(*AddFirmwareReq)(nil),        // 23: device.AddFirmwareReq
	(*FirmwareResp)(nil),          // 24: device.FirmwareResp
	(*GetFirmwareReq)(nil),        // 25: device.GetFirmwareReq
	(*DeleteFirmwareReq)(nil),     // 26: device.DeleteFirmwareReq
	(*DeleteFirmwareResp)(nil),    // 27: device.DeleteFirmwareResp
	(*ListFirmwareReq)(nil),       // 28: device.ListFirmwareReq
	(*ListFirmwareResp)(nil),      // 29: device.ListFirmwareResp
	(*PushFirmwareTaskReq)(nil),   // 30: device.PushFirmwareTaskReq
	(*FirmwareTaskResp)(nil),      // 31: device.FirmwareTaskResp
	(*GetFirmwareTaskReq)(nil),    // 32: device.GetFirmwareTaskReq
	(*ListFirmwareTaskReq)(nil),   // 33: device.ListFirmwareTaskReq
	(*ListFirmwareTaskResp)(nil),  // 34: device.ListFirmwareTaskResp
}
var file_device_proto_depIdxs = []int32{
	1,  // 0: device.ListDeviceResp.list:type_name -> device.DeviceResp
	8,  // 1: device.ListAppResp.list:type_name -> device.AppResp
	14, // 2: device.ListDeviceEventResp.list:type_name -> device.DeviceEventResp
	24, // 3: device.ListFirmwareResp.list:type_name -> device.FirmwareResp
	31, // 4: device.ListFirmwareTaskResp.list:type_name -> device.FirmwareTaskResp
	0,  // 5: device.Device.AddDevice:input_type -> device.AddDeviceReq
	1,  // 6: device.Device.UpdateDevice:input_type -> device.DeviceResp
	2,  // 7: device.Device.GetDevice:input_type -> device.GetDeviceReq
	3,  // 8: device.Device.DeleteDevice:input_type -> device.DeleteDeviceReq
	5,  // 9: device.Device.ListDevice:input_type -> device.ListDeviceReq
	7,  // 10: device.Device.AddApp:input_type -> device.AddAppReq
	8,  // 11: device.Device.UpdateApp:input_type -> device.AppResp
	9,  // 12: device.Device.GetApp:input_type -> device.GetAppReq
	10, // 13: device.Device.DeleteApp:input_type -> device.DeleteAppReq
	12, // 14: device.Device.ListApp:input_type -> device.ListAppReq
	20, // 15: device.Device.AddDeviceEvent:input_type -> device.AddDeviceEventReq
	16, // 16: device.Device.DeleteDeviceEvent:input_type -> device.DeleteDeviceEventReq
	15, // 17: device.Device.GetDeviceEvent:input_type -> device.GetDeviceEventReq
	18, // 18: device.Device.ListDeviceEvent:input_type -> device.ListDeviceEventReq
	21, // 19: device.Device.GetDeviceStats:input_type -> device.GetDeviceStatsReq
	23, // 20: device.Device.AddFirmware:input_type -> device.AddFirmwareReq
	24, // 21: device.Device.UpdateFirmware:input_type -> device.FirmwareResp
	25, // 22: device.Device.GetFirmware:input_type -> device.GetFirmwareReq
	26, // 23: device.Device.DeleteFirmware:input_type -> device.DeleteFirmwareReq
	28, // 24: device.Device.ListFirmware:input_type -> device.ListFirmwareReq
	30, // 25: device.Device.PushFirmwareTask:input_type -> device.PushFirmwareTaskReq
	32, // 26: device.Device.GetFirmwareTask:input_type -> device.GetFirmwareTaskReq
	33, // 27: device.Device.ListFirmwareTask:input_type -> device.ListFirmwareTaskReq
	1,  // 28: device.Device.AddDevice:output_type -> device.DeviceResp
	1,  // 29: device.Device.UpdateDevice:output_type -> device.DeviceResp
	1,  // 30: device.Device.GetDevice:output_type -> device.DeviceResp
	4,  // 31: device.Device.DeleteDevice:output_type -> device.DeleteDeviceResp
	6,  // 32: device.Device.ListDevice:output_type -> device.ListDeviceResp
	8,  // 33: device.Device.AddApp:output_type -> device.AppResp
	8,  // 34: device.Device.UpdateApp:output_type -> device.AppResp
	8,  // 35: device.Device.GetApp:output_type -> device.AppResp
	11, // 36: device.Device.DeleteApp:output_type -> device.DeleteAppResp
	13, // 37: device.Device.ListApp:output_type -> device.ListAppResp
	14, // 38: device.Device.AddDeviceEvent:output_type -> device.DeviceEventResp
	17, // 39: device.Device.DeleteDeviceEvent:output_type -> device.DeleteDeviceEventResp
	14, // 40: device.Device.GetDeviceEvent:output_type -> device.DeviceEventResp
	19, // 41: device.Device.ListDeviceEvent:output_type -> device.ListDeviceEventResp
	22, // 42: device.Device.GetDeviceStats:output_type -> device.DeviceStatsResp
	24, // 43: device.Device.AddFirmware:output_type -> device.FirmwareResp
	24, // 44: device.Device.UpdateFirmware:output_type -> device.FirmwareResp
	24, // 45: device.Device.GetFirmware:output_type -> device.FirmwareResp
	27, // 46: device.Device.DeleteFirmware:output_type -> device.DeleteFirmwareResp
	29, // 47: device.Device.ListFirmware:output_type -> device.ListFirmwareResp
	31, // 48: device.Device.PushFirmwareTask:output_type -> device.FirmwareTaskResp
	31, // 49: device.Device.GetFirmwareTask:output_type -> device.FirmwareTaskResp
	34, // 50: device.Device.ListFirmwareTask:output_type -> device.ListFirmwareTaskResp
	28, // [28:51] is the sub-list for method output_type
	5,  // [5:28] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_device_proto_init() }
func file_device_proto_init() {
	if File_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_proto_goTypes,
		DependencyIndexes: file_device_proto_depIdxs,
		MessageInfos:      file_device_proto_msgTypes,
	}.Build()
	File_device_proto = out.File
	file_device_proto_goTypes = nil
	file_device_proto_depIdxs = nil
}
