// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: device.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Device_AddDevice_FullMethodName         = "/device.Device/AddDevice"
	Device_UpdateDevice_FullMethodName      = "/device.Device/UpdateDevice"
	Device_GetDevice_FullMethodName         = "/device.Device/GetDevice"
	Device_DeleteDevice_FullMethodName      = "/device.Device/DeleteDevice"
	Device_ListDevice_FullMethodName        = "/device.Device/ListDevice"
	Device_AddApp_FullMethodName            = "/device.Device/AddApp"
	Device_UpdateApp_FullMethodName         = "/device.Device/UpdateApp"
	Device_GetApp_FullMethodName            = "/device.Device/GetApp"
	Device_DeleteApp_FullMethodName         = "/device.Device/DeleteApp"
	Device_ListApp_FullMethodName           = "/device.Device/ListApp"
	Device_AddDeviceEvent_FullMethodName    = "/device.Device/AddDeviceEvent"
	Device_DeleteDeviceEvent_FullMethodName = "/device.Device/DeleteDeviceEvent"
	Device_GetDeviceEvent_FullMethodName    = "/device.Device/GetDeviceEvent"
	Device_ListDeviceEvent_FullMethodName   = "/device.Device/ListDeviceEvent"
)

// DeviceClient is the client API for Device service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceClient interface {
	AddDevice(ctx context.Context, in *AddDeviceReq, opts ...grpc.CallOption) (*DeviceResp, error)
	UpdateDevice(ctx context.Context, in *DeviceResp, opts ...grpc.CallOption) (*DeviceResp, error)
	GetDevice(ctx context.Context, in *GetDeviceReq, opts ...grpc.CallOption) (*DeviceResp, error)
	DeleteDevice(ctx context.Context, in *DeleteDeviceReq, opts ...grpc.CallOption) (*DeleteDeviceResp, error)
	ListDevice(ctx context.Context, in *ListDeviceReq, opts ...grpc.CallOption) (*ListDeviceResp, error)
	AddApp(ctx context.Context, in *AddAppReq, opts ...grpc.CallOption) (*AppResp, error)
	UpdateApp(ctx context.Context, in *AppResp, opts ...grpc.CallOption) (*AppResp, error)
	GetApp(ctx context.Context, in *GetAppReq, opts ...grpc.CallOption) (*AppResp, error)
	DeleteApp(ctx context.Context, in *DeleteAppReq, opts ...grpc.CallOption) (*DeleteAppResp, error)
	ListApp(ctx context.Context, in *ListAppReq, opts ...grpc.CallOption) (*ListAppResp, error)
	AddDeviceEvent(ctx context.Context, in *AddDeviceEventReq, opts ...grpc.CallOption) (*DeviceEventResp, error)
	DeleteDeviceEvent(ctx context.Context, in *DeleteDeviceEventReq, opts ...grpc.CallOption) (*DeleteDeviceEventResp, error)
	GetDeviceEvent(ctx context.Context, in *GetDeviceEventReq, opts ...grpc.CallOption) (*DeviceEventResp, error)
	ListDeviceEvent(ctx context.Context, in *ListDeviceEventReq, opts ...grpc.CallOption) (*ListDeviceEventResp, error)
}

type deviceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceClient(cc grpc.ClientConnInterface) DeviceClient {
	return &deviceClient{cc}
}

func (c *deviceClient) AddDevice(ctx context.Context, in *AddDeviceReq, opts ...grpc.CallOption) (*DeviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceResp)
	err := c.cc.Invoke(ctx, Device_AddDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) UpdateDevice(ctx context.Context, in *DeviceResp, opts ...grpc.CallOption) (*DeviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceResp)
	err := c.cc.Invoke(ctx, Device_UpdateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) GetDevice(ctx context.Context, in *GetDeviceReq, opts ...grpc.CallOption) (*DeviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceResp)
	err := c.cc.Invoke(ctx, Device_GetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) DeleteDevice(ctx context.Context, in *DeleteDeviceReq, opts ...grpc.CallOption) (*DeleteDeviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeviceResp)
	err := c.cc.Invoke(ctx, Device_DeleteDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) ListDevice(ctx context.Context, in *ListDeviceReq, opts ...grpc.CallOption) (*ListDeviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeviceResp)
	err := c.cc.Invoke(ctx, Device_ListDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) AddApp(ctx context.Context, in *AddAppReq, opts ...grpc.CallOption) (*AppResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppResp)
	err := c.cc.Invoke(ctx, Device_AddApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) UpdateApp(ctx context.Context, in *AppResp, opts ...grpc.CallOption) (*AppResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppResp)
	err := c.cc.Invoke(ctx, Device_UpdateApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) GetApp(ctx context.Context, in *GetAppReq, opts ...grpc.CallOption) (*AppResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppResp)
	err := c.cc.Invoke(ctx, Device_GetApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) DeleteApp(ctx context.Context, in *DeleteAppReq, opts ...grpc.CallOption) (*DeleteAppResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAppResp)
	err := c.cc.Invoke(ctx, Device_DeleteApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) ListApp(ctx context.Context, in *ListAppReq, opts ...grpc.CallOption) (*ListAppResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppResp)
	err := c.cc.Invoke(ctx, Device_ListApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) AddDeviceEvent(ctx context.Context, in *AddDeviceEventReq, opts ...grpc.CallOption) (*DeviceEventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceEventResp)
	err := c.cc.Invoke(ctx, Device_AddDeviceEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) DeleteDeviceEvent(ctx context.Context, in *DeleteDeviceEventReq, opts ...grpc.CallOption) (*DeleteDeviceEventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeviceEventResp)
	err := c.cc.Invoke(ctx, Device_DeleteDeviceEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) GetDeviceEvent(ctx context.Context, in *GetDeviceEventReq, opts ...grpc.CallOption) (*DeviceEventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceEventResp)
	err := c.cc.Invoke(ctx, Device_GetDeviceEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) ListDeviceEvent(ctx context.Context, in *ListDeviceEventReq, opts ...grpc.CallOption) (*ListDeviceEventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeviceEventResp)
	err := c.cc.Invoke(ctx, Device_ListDeviceEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServer is the server API for Device service.
// All implementations must embed UnimplementedDeviceServer
// for forward compatibility.
type DeviceServer interface {
	AddDevice(context.Context, *AddDeviceReq) (*DeviceResp, error)
	UpdateDevice(context.Context, *DeviceResp) (*DeviceResp, error)
	GetDevice(context.Context, *GetDeviceReq) (*DeviceResp, error)
	DeleteDevice(context.Context, *DeleteDeviceReq) (*DeleteDeviceResp, error)
	ListDevice(context.Context, *ListDeviceReq) (*ListDeviceResp, error)
	AddApp(context.Context, *AddAppReq) (*AppResp, error)
	UpdateApp(context.Context, *AppResp) (*AppResp, error)
	GetApp(context.Context, *GetAppReq) (*AppResp, error)
	DeleteApp(context.Context, *DeleteAppReq) (*DeleteAppResp, error)
	ListApp(context.Context, *ListAppReq) (*ListAppResp, error)
	AddDeviceEvent(context.Context, *AddDeviceEventReq) (*DeviceEventResp, error)
	DeleteDeviceEvent(context.Context, *DeleteDeviceEventReq) (*DeleteDeviceEventResp, error)
	GetDeviceEvent(context.Context, *GetDeviceEventReq) (*DeviceEventResp, error)
	ListDeviceEvent(context.Context, *ListDeviceEventReq) (*ListDeviceEventResp, error)
	mustEmbedUnimplementedDeviceServer()
}

// UnimplementedDeviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceServer struct{}

func (UnimplementedDeviceServer) AddDevice(context.Context, *AddDeviceReq) (*DeviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDevice not implemented")
}
func (UnimplementedDeviceServer) UpdateDevice(context.Context, *DeviceResp) (*DeviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDevice not implemented")
}
func (UnimplementedDeviceServer) GetDevice(context.Context, *GetDeviceReq) (*DeviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedDeviceServer) DeleteDevice(context.Context, *DeleteDeviceReq) (*DeleteDeviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDevice not implemented")
}
func (UnimplementedDeviceServer) ListDevice(context.Context, *ListDeviceReq) (*ListDeviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevice not implemented")
}
func (UnimplementedDeviceServer) AddApp(context.Context, *AddAppReq) (*AppResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddApp not implemented")
}
func (UnimplementedDeviceServer) UpdateApp(context.Context, *AppResp) (*AppResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateApp not implemented")
}
func (UnimplementedDeviceServer) GetApp(context.Context, *GetAppReq) (*AppResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApp not implemented")
}
func (UnimplementedDeviceServer) DeleteApp(context.Context, *DeleteAppReq) (*DeleteAppResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteApp not implemented")
}
func (UnimplementedDeviceServer) ListApp(context.Context, *ListAppReq) (*ListAppResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApp not implemented")
}
func (UnimplementedDeviceServer) AddDeviceEvent(context.Context, *AddDeviceEventReq) (*DeviceEventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDeviceEvent not implemented")
}
func (UnimplementedDeviceServer) DeleteDeviceEvent(context.Context, *DeleteDeviceEventReq) (*DeleteDeviceEventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDeviceEvent not implemented")
}
func (UnimplementedDeviceServer) GetDeviceEvent(context.Context, *GetDeviceEventReq) (*DeviceEventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceEvent not implemented")
}
func (UnimplementedDeviceServer) ListDeviceEvent(context.Context, *ListDeviceEventReq) (*ListDeviceEventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeviceEvent not implemented")
}
func (UnimplementedDeviceServer) mustEmbedUnimplementedDeviceServer() {}
func (UnimplementedDeviceServer) testEmbeddedByValue()                {}

// UnsafeDeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServer will
// result in compilation errors.
type UnsafeDeviceServer interface {
	mustEmbedUnimplementedDeviceServer()
}

func RegisterDeviceServer(s grpc.ServiceRegistrar, srv DeviceServer) {
	// If the following call panics, it indicates UnimplementedDeviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Device_ServiceDesc, srv)
}

func _Device_AddDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).AddDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_AddDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).AddDevice(ctx, req.(*AddDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_UpdateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).UpdateDevice(ctx, req.(*DeviceResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_GetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).GetDevice(ctx, req.(*GetDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_DeleteDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).DeleteDevice(ctx, req.(*DeleteDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_ListDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).ListDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_ListDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).ListDevice(ctx, req.(*ListDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_AddApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).AddApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_AddApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).AddApp(ctx, req.(*AddAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_UpdateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).UpdateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_UpdateApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).UpdateApp(ctx, req.(*AppResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_GetApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).GetApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_GetApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).GetApp(ctx, req.(*GetAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_DeleteApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).DeleteApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_DeleteApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).DeleteApp(ctx, req.(*DeleteAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_ListApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).ListApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_ListApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).ListApp(ctx, req.(*ListAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_AddDeviceEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeviceEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).AddDeviceEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_AddDeviceEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).AddDeviceEvent(ctx, req.(*AddDeviceEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_DeleteDeviceEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).DeleteDeviceEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_DeleteDeviceEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).DeleteDeviceEvent(ctx, req.(*DeleteDeviceEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_GetDeviceEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).GetDeviceEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_GetDeviceEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).GetDeviceEvent(ctx, req.(*GetDeviceEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_ListDeviceEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeviceEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).ListDeviceEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Device_ListDeviceEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).ListDeviceEvent(ctx, req.(*ListDeviceEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Device_ServiceDesc is the grpc.ServiceDesc for Device service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Device_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "device.Device",
	HandlerType: (*DeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDevice",
			Handler:    _Device_AddDevice_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _Device_UpdateDevice_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _Device_GetDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _Device_DeleteDevice_Handler,
		},
		{
			MethodName: "ListDevice",
			Handler:    _Device_ListDevice_Handler,
		},
		{
			MethodName: "AddApp",
			Handler:    _Device_AddApp_Handler,
		},
		{
			MethodName: "UpdateApp",
			Handler:    _Device_UpdateApp_Handler,
		},
		{
			MethodName: "GetApp",
			Handler:    _Device_GetApp_Handler,
		},
		{
			MethodName: "DeleteApp",
			Handler:    _Device_DeleteApp_Handler,
		},
		{
			MethodName: "ListApp",
			Handler:    _Device_ListApp_Handler,
		},
		{
			MethodName: "AddDeviceEvent",
			Handler:    _Device_AddDeviceEvent_Handler,
		},
		{
			MethodName: "DeleteDeviceEvent",
			Handler:    _Device_DeleteDeviceEvent_Handler,
		},
		{
			MethodName: "GetDeviceEvent",
			Handler:    _Device_GetDeviceEvent_Handler,
		},
		{
			MethodName: "ListDeviceEvent",
			Handler:    _Device_ListDeviceEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device.proto",
}
