// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: sdk.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	SendType      string                 `protobuf:"bytes,2,opt,name=send_type,json=sendType,proto3" json:"send_type,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeReq) Reset() {
	*x = SendCodeReq{}
	mi := &file_sdk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeReq) ProtoMessage() {}

func (x *SendCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeReq.ProtoReflect.Descriptor instead.
func (*SendCodeReq) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{0}
}

func (x *SendCodeReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SendCodeReq) GetSendType() string {
	if x != nil {
		return x.SendType
	}
	return ""
}

func (x *SendCodeReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type SendCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeResp) Reset() {
	*x = SendCodeResp{}
	mi := &file_sdk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeResp) ProtoMessage() {}

func (x *SendCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeResp.ProtoReflect.Descriptor instead.
func (*SendCodeResp) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *SendCodeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	SendType      string                 `protobuf:"bytes,2,opt,name=send_type,json=sendType,proto3" json:"send_type,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCodeReq) Reset() {
	*x = CheckCodeReq{}
	mi := &file_sdk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCodeReq) ProtoMessage() {}

func (x *CheckCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCodeReq.ProtoReflect.Descriptor instead.
func (*CheckCodeReq) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{2}
}

func (x *CheckCodeReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CheckCodeReq) GetSendType() string {
	if x != nil {
		return x.SendType
	}
	return ""
}

func (x *CheckCodeReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CheckCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CheckCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCodeResp) Reset() {
	*x = CheckCodeResp{}
	mi := &file_sdk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCodeResp) ProtoMessage() {}

func (x *CheckCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCodeResp.ProtoReflect.Descriptor instead.
func (*CheckCodeResp) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{3}
}

func (x *CheckCodeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IpToAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpToAddressReq) Reset() {
	*x = IpToAddressReq{}
	mi := &file_sdk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpToAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpToAddressReq) ProtoMessage() {}

func (x *IpToAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpToAddressReq.ProtoReflect.Descriptor instead.
func (*IpToAddressReq) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{4}
}

func (x *IpToAddressReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type IpToAddressResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Province      string                 `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Area          string                 `protobuf:"bytes,4,opt,name=area,proto3" json:"area,omitempty"`
	Isp           string                 `protobuf:"bytes,5,opt,name=isp,proto3" json:"isp,omitempty"`
	Lat           string                 `protobuf:"bytes,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           string                 `protobuf:"bytes,7,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpToAddressResp) Reset() {
	*x = IpToAddressResp{}
	mi := &file_sdk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpToAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpToAddressResp) ProtoMessage() {}

func (x *IpToAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpToAddressResp.ProtoReflect.Descriptor instead.
func (*IpToAddressResp) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{5}
}

func (x *IpToAddressResp) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *IpToAddressResp) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *IpToAddressResp) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *IpToAddressResp) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *IpToAddressResp) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *IpToAddressResp) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *IpToAddressResp) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

type GetCourierReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogisticCode  string                 `protobuf:"bytes,1,opt,name=logistic_code,json=logisticCode,proto3" json:"logistic_code,omitempty"`
	CustomerName  string                 `protobuf:"bytes,2,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourierReq) Reset() {
	*x = GetCourierReq{}
	mi := &file_sdk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourierReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourierReq) ProtoMessage() {}

func (x *GetCourierReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourierReq.ProtoReflect.Descriptor instead.
func (*GetCourierReq) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{6}
}

func (x *GetCourierReq) GetLogisticCode() string {
	if x != nil {
		return x.LogisticCode
	}
	return ""
}

func (x *GetCourierReq) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

type GetCourierResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourierResp) Reset() {
	*x = GetCourierResp{}
	mi := &file_sdk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourierResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourierResp) ProtoMessage() {}

func (x *GetCourierResp) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourierResp.ProtoReflect.Descriptor instead.
func (*GetCourierResp) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{7}
}

type ChatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResp) Reset() {
	*x = ChatResp{}
	mi := &file_sdk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResp) ProtoMessage() {}

func (x *ChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResp.ProtoReflect.Descriptor instead.
func (*ChatResp) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{8}
}

func (x *ChatResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	mi := &file_sdk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{9}
}

func (x *ChatReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetWeatherReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherReq) Reset() {
	*x = GetWeatherReq{}
	mi := &file_sdk_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherReq) ProtoMessage() {}

func (x *GetWeatherReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherReq.ProtoReflect.Descriptor instead.
func (*GetWeatherReq) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{10}
}

func (x *GetWeatherReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetWeatherReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetWeatherItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Week          string                 `protobuf:"bytes,2,opt,name=week,proto3" json:"week,omitempty"`
	Weather       string                 `protobuf:"bytes,3,opt,name=weather,proto3" json:"weather,omitempty"`
	Temp          string                 `protobuf:"bytes,4,opt,name=temp,proto3" json:"temp,omitempty"`
	Wind          string                 `protobuf:"bytes,5,opt,name=wind,proto3" json:"wind,omitempty"`
	WeatherIcon   string                 `protobuf:"bytes,6,opt,name=weather_icon,json=weatherIcon,proto3" json:"weather_icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherItem) Reset() {
	*x = GetWeatherItem{}
	mi := &file_sdk_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherItem) ProtoMessage() {}

func (x *GetWeatherItem) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherItem.ProtoReflect.Descriptor instead.
func (*GetWeatherItem) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{11}
}

func (x *GetWeatherItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetWeatherItem) GetWeek() string {
	if x != nil {
		return x.Week
	}
	return ""
}

func (x *GetWeatherItem) GetWeather() string {
	if x != nil {
		return x.Weather
	}
	return ""
}

func (x *GetWeatherItem) GetTemp() string {
	if x != nil {
		return x.Temp
	}
	return ""
}

func (x *GetWeatherItem) GetWind() string {
	if x != nil {
		return x.Wind
	}
	return ""
}

func (x *GetWeatherItem) GetWeatherIcon() string {
	if x != nil {
		return x.WeatherIcon
	}
	return ""
}

type GetWeatherResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetWeatherItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Week          string                 `protobuf:"bytes,3,opt,name=week,proto3" json:"week,omitempty"`
	Weather       string                 `protobuf:"bytes,4,opt,name=weather,proto3" json:"weather,omitempty"`
	Temp          string                 `protobuf:"bytes,5,opt,name=temp,proto3" json:"temp,omitempty"`
	Wind          string                 `protobuf:"bytes,6,opt,name=wind,proto3" json:"wind,omitempty"`
	WeatherIcon   string                 `protobuf:"bytes,7,opt,name=weather_icon,json=weatherIcon,proto3" json:"weather_icon,omitempty"`
	Humidity      string                 `protobuf:"bytes,8,opt,name=humidity,proto3" json:"humidity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherResp) Reset() {
	*x = GetWeatherResp{}
	mi := &file_sdk_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherResp) ProtoMessage() {}

func (x *GetWeatherResp) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherResp.ProtoReflect.Descriptor instead.
func (*GetWeatherResp) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{12}
}

func (x *GetWeatherResp) GetItems() []*GetWeatherItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetWeatherResp) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetWeatherResp) GetWeek() string {
	if x != nil {
		return x.Week
	}
	return ""
}

func (x *GetWeatherResp) GetWeather() string {
	if x != nil {
		return x.Weather
	}
	return ""
}

func (x *GetWeatherResp) GetTemp() string {
	if x != nil {
		return x.Temp
	}
	return ""
}

func (x *GetWeatherResp) GetWind() string {
	if x != nil {
		return x.Wind
	}
	return ""
}

func (x *GetWeatherResp) GetWeatherIcon() string {
	if x != nil {
		return x.WeatherIcon
	}
	return ""
}

func (x *GetWeatherResp) GetHumidity() string {
	if x != nil {
		return x.Humidity
	}
	return ""
}

type UploadFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	File          []byte                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileReq) Reset() {
	*x = UploadFileReq{}
	mi := &file_sdk_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileReq) ProtoMessage() {}

func (x *UploadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileReq.ProtoReflect.Descriptor instead.
func (*UploadFileReq) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{13}
}

func (x *UploadFileReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileReq) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type UploadFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResp) Reset() {
	*x = UploadFileResp{}
	mi := &file_sdk_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResp) ProtoMessage() {}

func (x *UploadFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResp.ProtoReflect.Descriptor instead.
func (*UploadFileResp) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{14}
}

func (x *UploadFileResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UploadUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadUrlReq) Reset() {
	*x = UploadUrlReq{}
	mi := &file_sdk_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadUrlReq) ProtoMessage() {}

func (x *UploadUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadUrlReq.ProtoReflect.Descriptor instead.
func (*UploadUrlReq) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{15}
}

func (x *UploadUrlReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadUrlReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UploadUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadUrlResp) Reset() {
	*x = UploadUrlResp{}
	mi := &file_sdk_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadUrlResp) ProtoMessage() {}

func (x *UploadUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadUrlResp.ProtoReflect.Descriptor instead.
func (*UploadUrlResp) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{16}
}

func (x *UploadUrlResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetUploadTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadTokenReq) Reset() {
	*x = GetUploadTokenReq{}
	mi := &file_sdk_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadTokenReq) ProtoMessage() {}

func (x *GetUploadTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadTokenReq.ProtoReflect.Descriptor instead.
func (*GetUploadTokenReq) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{17}
}

func (x *GetUploadTokenReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetUploadTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Expire        int64                  `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadTokenResp) Reset() {
	*x = GetUploadTokenResp{}
	mi := &file_sdk_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadTokenResp) ProtoMessage() {}

func (x *GetUploadTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadTokenResp.ProtoReflect.Descriptor instead.
func (*GetUploadTokenResp) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{18}
}

func (x *GetUploadTokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetUploadTokenResp) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type PngToElnkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PngToElnkReq) Reset() {
	*x = PngToElnkReq{}
	mi := &file_sdk_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PngToElnkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PngToElnkReq) ProtoMessage() {}

func (x *PngToElnkReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PngToElnkReq.ProtoReflect.Descriptor instead.
func (*PngToElnkReq) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{19}
}

func (x *PngToElnkReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PngToElnkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PngToElnkResp) Reset() {
	*x = PngToElnkResp{}
	mi := &file_sdk_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PngToElnkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PngToElnkResp) ProtoMessage() {}

func (x *PngToElnkResp) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PngToElnkResp.ProtoReflect.Descriptor instead.
func (*PngToElnkResp) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{20}
}

func (x *PngToElnkResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type BaseAiReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseAiReq) Reset() {
	*x = BaseAiReq{}
	mi := &file_sdk_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseAiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseAiReq) ProtoMessage() {}

func (x *BaseAiReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseAiReq.ProtoReflect.Descriptor instead.
func (*BaseAiReq) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{21}
}

func (x *BaseAiReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BaseAiReq) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type AiImageGenerationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiImageGenerationResp) Reset() {
	*x = AiImageGenerationResp{}
	mi := &file_sdk_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiImageGenerationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiImageGenerationResp) ProtoMessage() {}

func (x *AiImageGenerationResp) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiImageGenerationResp.ProtoReflect.Descriptor instead.
func (*AiImageGenerationResp) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{22}
}

func (x *AiImageGenerationResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_sdk_proto protoreflect.FileDescriptor

const file_sdk_proto_rawDesc = "" +
	"\n" +
	"\tsdk.proto\x12\x03sdk\"^\n" +
	"\vSendCodeReq\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1b\n" +
	"\tsend_type\x18\x02 \x01(\tR\bsendType\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\"(\n" +
	"\fSendCodeResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"s\n" +
	"\fCheckCodeReq\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1b\n" +
	"\tsend_type\x18\x02 \x01(\tR\bsendType\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\")\n" +
	"\rCheckCodeResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\" \n" +
	"\x0eIpToAddressReq\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\xa5\x01\n" +
	"\x0fIpToAddressResp\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x1a\n" +
	"\bprovince\x18\x02 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x12\n" +
	"\x04area\x18\x04 \x01(\tR\x04area\x12\x10\n" +
	"\x03isp\x18\x05 \x01(\tR\x03isp\x12\x10\n" +
	"\x03lat\x18\x06 \x01(\tR\x03lat\x12\x10\n" +
	"\x03lng\x18\a \x01(\tR\x03lng\"Y\n" +
	"\rGetCourierReq\x12#\n" +
	"\rlogistic_code\x18\x01 \x01(\tR\flogisticCode\x12#\n" +
	"\rcustomer_name\x18\x02 \x01(\tR\fcustomerName\"\x10\n" +
	"\x0eGetCourierResp\"$\n" +
	"\bChatResp\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"#\n" +
	"\aChatReq\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"7\n" +
	"\rGetWeatherReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x9d\x01\n" +
	"\x0eGetWeatherItem\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04week\x18\x02 \x01(\tR\x04week\x12\x18\n" +
	"\aweather\x18\x03 \x01(\tR\aweather\x12\x12\n" +
	"\x04temp\x18\x04 \x01(\tR\x04temp\x12\x12\n" +
	"\x04wind\x18\x05 \x01(\tR\x04wind\x12!\n" +
	"\fweather_icon\x18\x06 \x01(\tR\vweatherIcon\"\xe4\x01\n" +
	"\x0eGetWeatherResp\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.sdk.GetWeatherItemR\x05items\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x12\n" +
	"\x04week\x18\x03 \x01(\tR\x04week\x12\x18\n" +
	"\aweather\x18\x04 \x01(\tR\aweather\x12\x12\n" +
	"\x04temp\x18\x05 \x01(\tR\x04temp\x12\x12\n" +
	"\x04wind\x18\x06 \x01(\tR\x04wind\x12!\n" +
	"\fweather_icon\x18\a \x01(\tR\vweatherIcon\x12\x1a\n" +
	"\bhumidity\x18\b \x01(\tR\bhumidity\"@\n" +
	"\rUploadFileReq\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04file\x18\x02 \x01(\fR\x04file\"\"\n" +
	"\x0eUploadFileResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"=\n" +
	"\fUploadUrlReq\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"!\n" +
	"\rUploadUrlResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"0\n" +
	"\x11GetUploadTokenReq\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\"B\n" +
	"\x12GetUploadTokenResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06expire\x18\x02 \x01(\x03R\x06expire\" \n" +
	"\fPngToElnkReq\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"!\n" +
	"\rPngToElnkResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"7\n" +
	"\tBaseAiReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\")\n" +
	"\x15AiImageGenerationResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xd8\x04\n" +
	"\x03Sdk\x12/\n" +
	"\bSendCode\x12\x10.sdk.SendCodeReq\x1a\x11.sdk.SendCodeResp\x122\n" +
	"\tCheckCode\x12\x11.sdk.CheckCodeReq\x1a\x12.sdk.CheckCodeResp\x128\n" +
	"\vIpToAddress\x12\x13.sdk.IpToAddressReq\x1a\x14.sdk.IpToAddressResp\x125\n" +
	"\n" +
	"GetCourier\x12\x12.sdk.GetCourierReq\x1a\x13.sdk.GetCourierResp\x12#\n" +
	"\x04Chat\x12\f.sdk.ChatReq\x1a\r.sdk.ChatResp\x125\n" +
	"\n" +
	"GetWeather\x12\x12.sdk.GetWeatherReq\x1a\x13.sdk.GetWeatherResp\x125\n" +
	"\n" +
	"UploadFile\x12\x12.sdk.UploadFileReq\x1a\x13.sdk.UploadFileResp\x122\n" +
	"\tUploadUrl\x12\x11.sdk.UploadUrlReq\x1a\x12.sdk.UploadUrlResp\x12A\n" +
	"\x0eGetUploadToken\x12\x16.sdk.GetUploadTokenReq\x1a\x17.sdk.GetUploadTokenResp\x122\n" +
	"\tPngToElnk\x12\x11.sdk.PngToElnkReq\x1a\x12.sdk.PngToElnkResp\x12=\n" +
	"\x0fImageGeneration\x12\x0e.sdk.BaseAiReq\x1a\x1a.sdk.AiImageGenerationRespB\x06Z\x04./pbb\x06proto3"

var (
	file_sdk_proto_rawDescOnce sync.Once
	file_sdk_proto_rawDescData []byte
)

func file_sdk_proto_rawDescGZIP() []byte {
	file_sdk_proto_rawDescOnce.Do(func() {
		file_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_proto_rawDesc), len(file_sdk_proto_rawDesc)))
	})
	return file_sdk_proto_rawDescData
}

var file_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_sdk_proto_goTypes = []any{
	(*SendCodeReq)(nil),           // 0: sdk.SendCodeReq
	(*SendCodeResp)(nil),          // 1: sdk.SendCodeResp
	(*CheckCodeReq)(nil),          // 2: sdk.CheckCodeReq
	(*CheckCodeResp)(nil),         // 3: sdk.CheckCodeResp
	(*IpToAddressReq)(nil),        // 4: sdk.IpToAddressReq
	(*IpToAddressResp)(nil),       // 5: sdk.IpToAddressResp
	(*GetCourierReq)(nil),         // 6: sdk.GetCourierReq
	(*GetCourierResp)(nil),        // 7: sdk.GetCourierResp
	(*ChatResp)(nil),              // 8: sdk.ChatResp
	(*ChatReq)(nil),               // 9: sdk.ChatReq
	(*GetWeatherReq)(nil),         // 10: sdk.GetWeatherReq
	(*GetWeatherItem)(nil),        // 11: sdk.GetWeatherItem
	(*GetWeatherResp)(nil),        // 12: sdk.GetWeatherResp
	(*UploadFileReq)(nil),         // 13: sdk.UploadFileReq
	(*UploadFileResp)(nil),        // 14: sdk.UploadFileResp
	(*UploadUrlReq)(nil),          // 15: sdk.UploadUrlReq
	(*UploadUrlResp)(nil),         // 16: sdk.UploadUrlResp
	(*GetUploadTokenReq)(nil),     // 17: sdk.GetUploadTokenReq
	(*GetUploadTokenResp)(nil),    // 18: sdk.GetUploadTokenResp
	(*PngToElnkReq)(nil),          // 19: sdk.PngToElnkReq
	(*PngToElnkResp)(nil),         // 20: sdk.PngToElnkResp
	(*BaseAiReq)(nil),             // 21: sdk.BaseAiReq
	(*AiImageGenerationResp)(nil), // 22: sdk.AiImageGenerationResp
}
var file_sdk_proto_depIdxs = []int32{
	11, // 0: sdk.GetWeatherResp.items:type_name -> sdk.GetWeatherItem
	0,  // 1: sdk.Sdk.SendCode:input_type -> sdk.SendCodeReq
	2,  // 2: sdk.Sdk.CheckCode:input_type -> sdk.CheckCodeReq
	4,  // 3: sdk.Sdk.IpToAddress:input_type -> sdk.IpToAddressReq
	6,  // 4: sdk.Sdk.GetCourier:input_type -> sdk.GetCourierReq
	9,  // 5: sdk.Sdk.Chat:input_type -> sdk.ChatReq
	10, // 6: sdk.Sdk.GetWeather:input_type -> sdk.GetWeatherReq
	13, // 7: sdk.Sdk.UploadFile:input_type -> sdk.UploadFileReq
	15, // 8: sdk.Sdk.UploadUrl:input_type -> sdk.UploadUrlReq
	17, // 9: sdk.Sdk.GetUploadToken:input_type -> sdk.GetUploadTokenReq
	19, // 10: sdk.Sdk.PngToElnk:input_type -> sdk.PngToElnkReq
	21, // 11: sdk.Sdk.ImageGeneration:input_type -> sdk.BaseAiReq
	1,  // 12: sdk.Sdk.SendCode:output_type -> sdk.SendCodeResp
	3,  // 13: sdk.Sdk.CheckCode:output_type -> sdk.CheckCodeResp
	5,  // 14: sdk.Sdk.IpToAddress:output_type -> sdk.IpToAddressResp
	7,  // 15: sdk.Sdk.GetCourier:output_type -> sdk.GetCourierResp
	8,  // 16: sdk.Sdk.Chat:output_type -> sdk.ChatResp
	12, // 17: sdk.Sdk.GetWeather:output_type -> sdk.GetWeatherResp
	14, // 18: sdk.Sdk.UploadFile:output_type -> sdk.UploadFileResp
	16, // 19: sdk.Sdk.UploadUrl:output_type -> sdk.UploadUrlResp
	18, // 20: sdk.Sdk.GetUploadToken:output_type -> sdk.GetUploadTokenResp
	20, // 21: sdk.Sdk.PngToElnk:output_type -> sdk.PngToElnkResp
	22, // 22: sdk.Sdk.ImageGeneration:output_type -> sdk.AiImageGenerationResp
	12, // [12:23] is the sub-list for method output_type
	1,  // [1:12] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_sdk_proto_init() }
func file_sdk_proto_init() {
	if File_sdk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_proto_rawDesc), len(file_sdk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_proto_goTypes,
		DependencyIndexes: file_sdk_proto_depIdxs,
		MessageInfos:      file_sdk_proto_msgTypes,
	}.Build()
	File_sdk_proto = out.File
	file_sdk_proto_goTypes = nil
	file_sdk_proto_depIdxs = nil
}
