// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: sdk.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sdk_SendCode_FullMethodName       = "/sdk.Sdk/SendCode"
	Sdk_CheckCode_FullMethodName      = "/sdk.Sdk/CheckCode"
	Sdk_IpToAddress_FullMethodName    = "/sdk.Sdk/IpToAddress"
	Sdk_GetCourier_FullMethodName     = "/sdk.Sdk/GetCourier"
	Sdk_Chat_FullMethodName           = "/sdk.Sdk/Chat"
	Sdk_GetWeather_FullMethodName     = "/sdk.Sdk/GetWeather"
	Sdk_UploadFile_FullMethodName     = "/sdk.Sdk/UploadFile"
	Sdk_UploadUrl_FullMethodName      = "/sdk.Sdk/UploadUrl"
	Sdk_GetUploadToken_FullMethodName = "/sdk.Sdk/GetUploadToken"
	Sdk_PngToElnk_FullMethodName      = "/sdk.Sdk/PngToElnk"
)

// SdkClient is the client API for Sdk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SdkClient interface {
	SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error)
	CheckCode(ctx context.Context, in *CheckCodeReq, opts ...grpc.CallOption) (*CheckCodeResp, error)
	IpToAddress(ctx context.Context, in *IpToAddressReq, opts ...grpc.CallOption) (*IpToAddressResp, error)
	GetCourier(ctx context.Context, in *GetCourierReq, opts ...grpc.CallOption) (*GetCourierResp, error)
	Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error)
	GetWeather(ctx context.Context, in *GetWeatherReq, opts ...grpc.CallOption) (*GetWeatherResp, error)
	UploadFile(ctx context.Context, in *UploadFileReq, opts ...grpc.CallOption) (*UploadFileResp, error)
	UploadUrl(ctx context.Context, in *UploadUrlReq, opts ...grpc.CallOption) (*UploadUrlResp, error)
	GetUploadToken(ctx context.Context, in *GetUploadTokenReq, opts ...grpc.CallOption) (*GetUploadTokenResp, error)
	PngToElnk(ctx context.Context, in *PngToElnkReq, opts ...grpc.CallOption) (*PngToElnkResp, error)
}

type sdkClient struct {
	cc grpc.ClientConnInterface
}

func NewSdkClient(cc grpc.ClientConnInterface) SdkClient {
	return &sdkClient{cc}
}

func (c *sdkClient) SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCodeResp)
	err := c.cc.Invoke(ctx, Sdk_SendCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkClient) CheckCode(ctx context.Context, in *CheckCodeReq, opts ...grpc.CallOption) (*CheckCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCodeResp)
	err := c.cc.Invoke(ctx, Sdk_CheckCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkClient) IpToAddress(ctx context.Context, in *IpToAddressReq, opts ...grpc.CallOption) (*IpToAddressResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IpToAddressResp)
	err := c.cc.Invoke(ctx, Sdk_IpToAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkClient) GetCourier(ctx context.Context, in *GetCourierReq, opts ...grpc.CallOption) (*GetCourierResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourierResp)
	err := c.cc.Invoke(ctx, Sdk_GetCourier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkClient) Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResp)
	err := c.cc.Invoke(ctx, Sdk_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkClient) GetWeather(ctx context.Context, in *GetWeatherReq, opts ...grpc.CallOption) (*GetWeatherResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeatherResp)
	err := c.cc.Invoke(ctx, Sdk_GetWeather_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkClient) UploadFile(ctx context.Context, in *UploadFileReq, opts ...grpc.CallOption) (*UploadFileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResp)
	err := c.cc.Invoke(ctx, Sdk_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkClient) UploadUrl(ctx context.Context, in *UploadUrlReq, opts ...grpc.CallOption) (*UploadUrlResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadUrlResp)
	err := c.cc.Invoke(ctx, Sdk_UploadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkClient) GetUploadToken(ctx context.Context, in *GetUploadTokenReq, opts ...grpc.CallOption) (*GetUploadTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUploadTokenResp)
	err := c.cc.Invoke(ctx, Sdk_GetUploadToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkClient) PngToElnk(ctx context.Context, in *PngToElnkReq, opts ...grpc.CallOption) (*PngToElnkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PngToElnkResp)
	err := c.cc.Invoke(ctx, Sdk_PngToElnk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SdkServer is the server API for Sdk service.
// All implementations must embed UnimplementedSdkServer
// for forward compatibility.
type SdkServer interface {
	SendCode(context.Context, *SendCodeReq) (*SendCodeResp, error)
	CheckCode(context.Context, *CheckCodeReq) (*CheckCodeResp, error)
	IpToAddress(context.Context, *IpToAddressReq) (*IpToAddressResp, error)
	GetCourier(context.Context, *GetCourierReq) (*GetCourierResp, error)
	Chat(context.Context, *ChatReq) (*ChatResp, error)
	GetWeather(context.Context, *GetWeatherReq) (*GetWeatherResp, error)
	UploadFile(context.Context, *UploadFileReq) (*UploadFileResp, error)
	UploadUrl(context.Context, *UploadUrlReq) (*UploadUrlResp, error)
	GetUploadToken(context.Context, *GetUploadTokenReq) (*GetUploadTokenResp, error)
	PngToElnk(context.Context, *PngToElnkReq) (*PngToElnkResp, error)
	mustEmbedUnimplementedSdkServer()
}

// UnimplementedSdkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSdkServer struct{}

func (UnimplementedSdkServer) SendCode(context.Context, *SendCodeReq) (*SendCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCode not implemented")
}
func (UnimplementedSdkServer) CheckCode(context.Context, *CheckCodeReq) (*CheckCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCode not implemented")
}
func (UnimplementedSdkServer) IpToAddress(context.Context, *IpToAddressReq) (*IpToAddressResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IpToAddress not implemented")
}
func (UnimplementedSdkServer) GetCourier(context.Context, *GetCourierReq) (*GetCourierResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourier not implemented")
}
func (UnimplementedSdkServer) Chat(context.Context, *ChatReq) (*ChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedSdkServer) GetWeather(context.Context, *GetWeatherReq) (*GetWeatherResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeather not implemented")
}
func (UnimplementedSdkServer) UploadFile(context.Context, *UploadFileReq) (*UploadFileResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedSdkServer) UploadUrl(context.Context, *UploadUrlReq) (*UploadUrlResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadUrl not implemented")
}
func (UnimplementedSdkServer) GetUploadToken(context.Context, *GetUploadTokenReq) (*GetUploadTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadToken not implemented")
}
func (UnimplementedSdkServer) PngToElnk(context.Context, *PngToElnkReq) (*PngToElnkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PngToElnk not implemented")
}
func (UnimplementedSdkServer) mustEmbedUnimplementedSdkServer() {}
func (UnimplementedSdkServer) testEmbeddedByValue()             {}

// UnsafeSdkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SdkServer will
// result in compilation errors.
type UnsafeSdkServer interface {
	mustEmbedUnimplementedSdkServer()
}

func RegisterSdkServer(s grpc.ServiceRegistrar, srv SdkServer) {
	// If the following call pancis, it indicates UnimplementedSdkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sdk_ServiceDesc, srv)
}

func _Sdk_SendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).SendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sdk_SendCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).SendCode(ctx, req.(*SendCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sdk_CheckCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).CheckCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sdk_CheckCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).CheckCode(ctx, req.(*CheckCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sdk_IpToAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IpToAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).IpToAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sdk_IpToAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).IpToAddress(ctx, req.(*IpToAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sdk_GetCourier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourierReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).GetCourier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sdk_GetCourier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).GetCourier(ctx, req.(*GetCourierReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sdk_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sdk_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).Chat(ctx, req.(*ChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sdk_GetWeather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeatherReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).GetWeather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sdk_GetWeather_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).GetWeather(ctx, req.(*GetWeatherReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sdk_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sdk_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).UploadFile(ctx, req.(*UploadFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sdk_UploadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).UploadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sdk_UploadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).UploadUrl(ctx, req.(*UploadUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sdk_GetUploadToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).GetUploadToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sdk_GetUploadToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).GetUploadToken(ctx, req.(*GetUploadTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sdk_PngToElnk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PngToElnkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).PngToElnk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sdk_PngToElnk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).PngToElnk(ctx, req.(*PngToElnkReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Sdk_ServiceDesc is the grpc.ServiceDesc for Sdk service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sdk_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sdk.Sdk",
	HandlerType: (*SdkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCode",
			Handler:    _Sdk_SendCode_Handler,
		},
		{
			MethodName: "CheckCode",
			Handler:    _Sdk_CheckCode_Handler,
		},
		{
			MethodName: "IpToAddress",
			Handler:    _Sdk_IpToAddress_Handler,
		},
		{
			MethodName: "GetCourier",
			Handler:    _Sdk_GetCourier_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _Sdk_Chat_Handler,
		},
		{
			MethodName: "GetWeather",
			Handler:    _Sdk_GetWeather_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _Sdk_UploadFile_Handler,
		},
		{
			MethodName: "UploadUrl",
			Handler:    _Sdk_UploadUrl_Handler,
		},
		{
			MethodName: "GetUploadToken",
			Handler:    _Sdk_GetUploadToken_Handler,
		},
		{
			MethodName: "PngToElnk",
			Handler:    _Sdk_PngToElnk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk.proto",
}
