// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuccessResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessResp) Reset() {
	*x = SuccessResp{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResp) ProtoMessage() {}

func (x *SuccessResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResp.ProtoReflect.Descriptor instead.
func (*SuccessResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *SuccessResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// -------------------user-------------------
type AddUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserReq) Reset() {
	*x = AddUserReq{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserReq) ProtoMessage() {}

func (x *AddUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserReq.ProtoReflect.Descriptor instead.
func (*AddUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddUserReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AddUserReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AddUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	IsDelete      int64                  `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	CreateTime    uint64                 `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    uint64                 `protobuf:"varint,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResp) Reset() {
	*x = UserResp{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResp) ProtoMessage() {}

func (x *UserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResp.ProtoReflect.Descriptor instead.
func (*UserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResp) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserResp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserResp) GetIsDelete() int64 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

func (x *UserResp) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserResp) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type DeleteUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReq) Reset() {
	*x = DeleteUserReq{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReq) ProtoMessage() {}

func (x *DeleteUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReq.ProtoReflect.Descriptor instead.
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResp) Reset() {
	*x = DeleteUserResp{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResp) ProtoMessage() {}

func (x *DeleteUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResp.ProtoReflect.Descriptor instead.
func (*DeleteUserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	IsDelete      int64                  `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UpdateUserReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserReq) GetIsDelete() int64 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *GetUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReq) Reset() {
	*x = ListUserReq{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReq) ProtoMessage() {}

func (x *ListUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReq.ProtoReflect.Descriptor instead.
func (*ListUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListUserReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ListUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserResp            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserResp) Reset() {
	*x = ListUserResp{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserResp) ProtoMessage() {}

func (x *ListUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserResp.ProtoReflect.Descriptor instead.
func (*ListUserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserResp) GetList() []*UserResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListUserResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UserThirdLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppType       string                 `protobuf:"bytes,1,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserThirdLoginReq) Reset() {
	*x = UserThirdLoginReq{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserThirdLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserThirdLoginReq) ProtoMessage() {}

func (x *UserThirdLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserThirdLoginReq.ProtoReflect.Descriptor instead.
func (*UserThirdLoginReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserThirdLoginReq) GetAppType() string {
	if x != nil {
		return x.AppType
	}
	return ""
}

func (x *UserThirdLoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginSuccessResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginSuccessResp) Reset() {
	*x = LoginSuccessResp{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginSuccessResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSuccessResp) ProtoMessage() {}

func (x *LoginSuccessResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSuccessResp.ProtoReflect.Descriptor instead.
func (*LoginSuccessResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *LoginSuccessResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginSuccessResp) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginSuccessResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginSuccessResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *LoginSuccessResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// -------------------admin-------------------
type AddAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAdminReq) Reset() {
	*x = AddAdminReq{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAdminReq) ProtoMessage() {}

func (x *AddAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAdminReq.ProtoReflect.Descriptor instead.
func (*AddAdminReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *AddAdminReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AddAdminReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AddAdminReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddAdminReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       uint64                 `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	IsDelete      int64                  `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	CreateTime    uint64                 `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    uint64                 `protobuf:"varint,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminResp) Reset() {
	*x = AdminResp{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResp) ProtoMessage() {}

func (x *AdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResp.ProtoReflect.Descriptor instead.
func (*AdminResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *AdminResp) GetAdminId() uint64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *AdminResp) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AdminResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AdminResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminResp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminResp) GetIsDelete() int64 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

func (x *AdminResp) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AdminResp) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type UpdateAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       uint64                 `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	IsDelete      int64                  `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminReq) Reset() {
	*x = UpdateAdminReq{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminReq) ProtoMessage() {}

func (x *UpdateAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminReq.ProtoReflect.Descriptor instead.
func (*UpdateAdminReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateAdminReq) GetAdminId() uint64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *UpdateAdminReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UpdateAdminReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateAdminReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateAdminReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateAdminReq) GetIsDelete() int64 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

type GetAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       uint64                 `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminReq) Reset() {
	*x = GetAdminReq{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminReq) ProtoMessage() {}

func (x *GetAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminReq.ProtoReflect.Descriptor instead.
func (*GetAdminReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetAdminReq) GetAdminId() uint64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *GetAdminReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *GetAdminReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type DeleteAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       uint64                 `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminReq) Reset() {
	*x = DeleteAdminReq{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminReq) ProtoMessage() {}

func (x *DeleteAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminReq.ProtoReflect.Descriptor instead.
func (*DeleteAdminReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteAdminReq) GetAdminId() uint64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type DeleteAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminResp) Reset() {
	*x = DeleteAdminResp{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminResp) ProtoMessage() {}

func (x *DeleteAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminResp.ProtoReflect.Descriptor instead.
func (*DeleteAdminResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteAdminResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	AdminId       string                 `protobuf:"bytes,5,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminReq) Reset() {
	*x = ListAdminReq{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminReq) ProtoMessage() {}

func (x *ListAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminReq.ProtoReflect.Descriptor instead.
func (*ListAdminReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *ListAdminReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdminReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdminReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListAdminReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ListAdminReq) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type ListAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AdminResp           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminResp) Reset() {
	*x = ListAdminResp{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminResp) ProtoMessage() {}

func (x *ListAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminResp.ProtoReflect.Descriptor instead.
func (*ListAdminResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *ListAdminResp) GetList() []*AdminResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListAdminResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// -------------------rule--------------------
type BaseRoleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	AdminId       string                 `protobuf:"bytes,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRoleItem) Reset() {
	*x = BaseRoleItem{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRoleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRoleItem) ProtoMessage() {}

func (x *BaseRoleItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRoleItem.ProtoReflect.Descriptor instead.
func (*BaseRoleItem) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *BaseRoleItem) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *BaseRoleItem) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *BaseRoleItem) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type BasePolicyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Policy        string                 `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasePolicyItem) Reset() {
	*x = BasePolicyItem{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasePolicyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasePolicyItem) ProtoMessage() {}

func (x *BasePolicyItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasePolicyItem.ProtoReflect.Descriptor instead.
func (*BasePolicyItem) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *BasePolicyItem) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *BasePolicyItem) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *BasePolicyItem) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *BasePolicyItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type GetAllDomainReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDomainReq) Reset() {
	*x = GetAllDomainReq{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDomainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDomainReq) ProtoMessage() {}

func (x *GetAllDomainReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDomainReq.ProtoReflect.Descriptor instead.
func (*GetAllDomainReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

type GetAllDomainResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []string               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDomainResp) Reset() {
	*x = GetAllDomainResp{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDomainResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDomainResp) ProtoMessage() {}

func (x *GetAllDomainResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDomainResp.ProtoReflect.Descriptor instead.
func (*GetAllDomainResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *GetAllDomainResp) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

type GetRoleListeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*BaseRoleItem        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleListeResp) Reset() {
	*x = GetRoleListeResp{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleListeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleListeResp) ProtoMessage() {}

func (x *GetRoleListeResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleListeResp.ProtoReflect.Descriptor instead.
func (*GetRoleListeResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *GetRoleListeResp) GetList() []*BaseRoleItem {
	if x != nil {
		return x.List
	}
	return nil
}

type GetPolicyListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*BasePolicyItem      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyListResp) Reset() {
	*x = GetPolicyListResp{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyListResp) ProtoMessage() {}

func (x *GetPolicyListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyListResp.ProtoReflect.Descriptor instead.
func (*GetPolicyListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *GetPolicyListResp) GetList() []*BasePolicyItem {
	if x != nil {
		return x.List
	}
	return nil
}

type CheckAdminPermissionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	AdminId       string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Policy        string                 `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAdminPermissionReq) Reset() {
	*x = CheckAdminPermissionReq{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAdminPermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAdminPermissionReq) ProtoMessage() {}

func (x *CheckAdminPermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAdminPermissionReq.ProtoReflect.Descriptor instead.
func (*CheckAdminPermissionReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

func (x *CheckAdminPermissionReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CheckAdminPermissionReq) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *CheckAdminPermissionReq) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *CheckAdminPermissionReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// -------------------miniapp-------------------
type MiniappCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppType       string                 `protobuf:"bytes,1,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniappCodeReq) Reset() {
	*x = MiniappCodeReq{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniappCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniappCodeReq) ProtoMessage() {}

func (x *MiniappCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniappCodeReq.ProtoReflect.Descriptor instead.
func (*MiniappCodeReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

func (x *MiniappCodeReq) GetAppType() string {
	if x != nil {
		return x.AppType
	}
	return ""
}

func (x *MiniappCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type MiniappCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openid        string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	SessionKey    string                 `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Unionid       string                 `protobuf:"bytes,3,opt,name=unionid,proto3" json:"unionid,omitempty"`
	Errcode       int64                  `protobuf:"varint,4,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Errmsg        string                 `protobuf:"bytes,5,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniappCodeResp) Reset() {
	*x = MiniappCodeResp{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniappCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniappCodeResp) ProtoMessage() {}

func (x *MiniappCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniappCodeResp.ProtoReflect.Descriptor instead.
func (*MiniappCodeResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

func (x *MiniappCodeResp) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *MiniappCodeResp) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *MiniappCodeResp) GetUnionid() string {
	if x != nil {
		return x.Unionid
	}
	return ""
}

func (x *MiniappCodeResp) GetErrcode() int64 {
	if x != nil {
		return x.Errcode
	}
	return 0
}

func (x *MiniappCodeResp) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"'\n" +
	"\vSuccessResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"t\n" +
	"\n" +
	"AddUserReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\xea\x01\n" +
	"\bUserResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1b\n" +
	"\tis_delete\x18\x06 \x01(\x03R\bisDelete\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x04R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\b \x01(\x04R\n" +
	"updateTime\"(\n" +
	"\rDeleteUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"*\n" +
	"\x0eDeleteUserResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xad\x01\n" +
	"\rUpdateUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1b\n" +
	"\tis_delete\x18\x06 \x01(\x03R\bisDelete\"Y\n" +
	"\n" +
	"GetUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"\x8b\x01\n" +
	"\vListUserReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"H\n" +
	"\fListUserResp\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.user.UserRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"B\n" +
	"\x11UserThirdLoginReq\x12\x19\n" +
	"\bapp_type\x18\x01 \x01(\tR\aappType\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x8d\x01\n" +
	"\x10LoginSuccessResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\"u\n" +
	"\vAddAdminReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\xed\x01\n" +
	"\tAdminResp\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x04R\aadminId\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1b\n" +
	"\tis_delete\x18\x06 \x01(\x03R\bisDelete\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x04R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\b \x01(\x04R\n" +
	"updateTime\"\xb0\x01\n" +
	"\x0eUpdateAdminReq\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x04R\aadminId\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1b\n" +
	"\tis_delete\x18\x06 \x01(\x03R\bisDelete\"\\\n" +
	"\vGetAdminReq\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x04R\aadminId\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"+\n" +
	"\x0eDeleteAdminReq\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x04R\aadminId\"+\n" +
	"\x0fDeleteAdminResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x01\n" +
	"\fListAdminReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x19\n" +
	"\badmin_id\x18\x05 \x01(\tR\aadminId\"J\n" +
	"\rListAdminResp\x12#\n" +
	"\x04list\x18\x01 \x03(\v2\x0f.user.AdminRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"U\n" +
	"\fBaseRoleItem\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\tR\aadminId\"l\n" +
	"\x0eBasePolicyItem\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06policy\x18\x03 \x01(\tR\x06policy\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"\x11\n" +
	"\x0fGetAllDomainReq\"&\n" +
	"\x10GetAllDomainResp\x12\x12\n" +
	"\x04list\x18\x01 \x03(\tR\x04list\":\n" +
	"\x10GetRoleListeResp\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.user.BaseRoleItemR\x04list\"=\n" +
	"\x11GetPolicyListResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.user.BasePolicyItemR\x04list\"|\n" +
	"\x17CheckAdminPermissionReq\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\x12\x16\n" +
	"\x06policy\x18\x03 \x01(\tR\x06policy\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"?\n" +
	"\x0eMiniappCodeReq\x12\x19\n" +
	"\bapp_type\x18\x01 \x01(\tR\aappType\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x96\x01\n" +
	"\x0fMiniappCodeResp\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\x12\x1f\n" +
	"\vsession_key\x18\x02 \x01(\tR\n" +
	"sessionKey\x12\x18\n" +
	"\aunionid\x18\x03 \x01(\tR\aunionid\x12\x18\n" +
	"\aerrcode\x18\x04 \x01(\x03R\aerrcode\x12\x16\n" +
	"\x06errmsg\x18\x05 \x01(\tR\x06errmsg2\xc2\n" +
	"\n" +
	"\x04User\x123\n" +
	"\aAddUser\x12\x10.user.AddUserReq\x1a\x16.user.LoginSuccessResp\x124\n" +
	"\n" +
	"DeleteUser\x12\x13.user.DeleteUserReq\x1a\x11.user.SuccessResp\x124\n" +
	"\n" +
	"UpdateUser\x12\x13.user.UpdateUserReq\x1a\x11.user.SuccessResp\x12+\n" +
	"\aGetUser\x12\x10.user.GetUserReq\x1a\x0e.user.UserResp\x121\n" +
	"\bListUser\x12\x11.user.ListUserReq\x1a\x12.user.ListUserResp\x12A\n" +
	"\x0eUserThirdLogin\x12\x17.user.UserThirdLoginReq\x1a\x16.user.LoginSuccessResp\x120\n" +
	"\bAddAdmin\x12\x11.user.AddAdminReq\x1a\x11.user.SuccessResp\x126\n" +
	"\vUpdateAdmin\x12\x14.user.UpdateAdminReq\x1a\x11.user.SuccessResp\x12.\n" +
	"\bGetAdmin\x12\x11.user.GetAdminReq\x1a\x0f.user.AdminResp\x124\n" +
	"\tListAdmin\x12\x12.user.ListAdminReq\x1a\x13.user.ListAdminResp\x126\n" +
	"\vDeleteAdmin\x12\x14.user.DeleteAdminReq\x1a\x11.user.SuccessResp\x12=\n" +
	"\fGetAllDomain\x12\x15.user.GetAllDomainReq\x1a\x16.user.GetAllDomainResp\x120\n" +
	"\aGetRole\x12\x12.user.BaseRoleItem\x1a\x11.user.SuccessResp\x129\n" +
	"\vGetRoleList\x12\x12.user.BaseRoleItem\x1a\x16.user.GetRoleListeResp\x120\n" +
	"\aAddRole\x12\x12.user.BaseRoleItem\x1a\x11.user.SuccessResp\x123\n" +
	"\n" +
	"DeleteRole\x12\x12.user.BaseRoleItem\x1a\x11.user.SuccessResp\x124\n" +
	"\tGetPolicy\x12\x14.user.BasePolicyItem\x1a\x11.user.SuccessResp\x12>\n" +
	"\rGetPolicyList\x12\x14.user.BasePolicyItem\x1a\x17.user.GetPolicyListResp\x124\n" +
	"\tAddPolicy\x12\x14.user.BasePolicyItem\x1a\x11.user.SuccessResp\x127\n" +
	"\fDeletePolicy\x12\x14.user.BasePolicyItem\x1a\x11.user.SuccessResp\x12H\n" +
	"\x14CheckAdminPermission\x12\x1d.user.CheckAdminPermissionReq\x1a\x11.user.SuccessResp\x127\n" +
	"\x0eLoadUserPolicy\x12\x12.user.BaseRoleItem\x1a\x11.user.SuccessResp\x127\n" +
	"\x0eLoadRolePolicy\x12\x12.user.BaseRoleItem\x1a\x11.user.SuccessResp\x12:\n" +
	"\vMiniappCode\x12\x14.user.MiniappCodeReq\x1a\x15.user.MiniappCodeRespB\x06Z\x04./pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_user_proto_goTypes = []any{
	(*SuccessResp)(nil),             // 0: user.SuccessResp
	(*AddUserReq)(nil),              // 1: user.AddUserReq
	(*UserResp)(nil),                // 2: user.UserResp
	(*DeleteUserReq)(nil),           // 3: user.DeleteUserReq
	(*DeleteUserResp)(nil),          // 4: user.DeleteUserResp
	(*UpdateUserReq)(nil),           // 5: user.UpdateUserReq
	(*GetUserReq)(nil),              // 6: user.GetUserReq
	(*ListUserReq)(nil),             // 7: user.ListUserReq
	(*ListUserResp)(nil),            // 8: user.ListUserResp
	(*UserThirdLoginReq)(nil),       // 9: user.UserThirdLoginReq
	(*LoginSuccessResp)(nil),        // 10: user.LoginSuccessResp
	(*AddAdminReq)(nil),             // 11: user.AddAdminReq
	(*AdminResp)(nil),               // 12: user.AdminResp
	(*UpdateAdminReq)(nil),          // 13: user.UpdateAdminReq
	(*GetAdminReq)(nil),             // 14: user.GetAdminReq
	(*DeleteAdminReq)(nil),          // 15: user.DeleteAdminReq
	(*DeleteAdminResp)(nil),         // 16: user.DeleteAdminResp
	(*ListAdminReq)(nil),            // 17: user.ListAdminReq
	(*ListAdminResp)(nil),           // 18: user.ListAdminResp
	(*BaseRoleItem)(nil),            // 19: user.BaseRoleItem
	(*BasePolicyItem)(nil),          // 20: user.BasePolicyItem
	(*GetAllDomainReq)(nil),         // 21: user.GetAllDomainReq
	(*GetAllDomainResp)(nil),        // 22: user.GetAllDomainResp
	(*GetRoleListeResp)(nil),        // 23: user.GetRoleListeResp
	(*GetPolicyListResp)(nil),       // 24: user.GetPolicyListResp
	(*CheckAdminPermissionReq)(nil), // 25: user.CheckAdminPermissionReq
	(*MiniappCodeReq)(nil),          // 26: user.MiniappCodeReq
	(*MiniappCodeResp)(nil),         // 27: user.MiniappCodeResp
}
var file_user_proto_depIdxs = []int32{
	2,  // 0: user.ListUserResp.list:type_name -> user.UserResp
	12, // 1: user.ListAdminResp.list:type_name -> user.AdminResp
	19, // 2: user.GetRoleListeResp.list:type_name -> user.BaseRoleItem
	20, // 3: user.GetPolicyListResp.list:type_name -> user.BasePolicyItem
	1,  // 4: user.User.AddUser:input_type -> user.AddUserReq
	3,  // 5: user.User.DeleteUser:input_type -> user.DeleteUserReq
	5,  // 6: user.User.UpdateUser:input_type -> user.UpdateUserReq
	6,  // 7: user.User.GetUser:input_type -> user.GetUserReq
	7,  // 8: user.User.ListUser:input_type -> user.ListUserReq
	9,  // 9: user.User.UserThirdLogin:input_type -> user.UserThirdLoginReq
	11, // 10: user.User.AddAdmin:input_type -> user.AddAdminReq
	13, // 11: user.User.UpdateAdmin:input_type -> user.UpdateAdminReq
	14, // 12: user.User.GetAdmin:input_type -> user.GetAdminReq
	17, // 13: user.User.ListAdmin:input_type -> user.ListAdminReq
	15, // 14: user.User.DeleteAdmin:input_type -> user.DeleteAdminReq
	21, // 15: user.User.GetAllDomain:input_type -> user.GetAllDomainReq
	19, // 16: user.User.GetRole:input_type -> user.BaseRoleItem
	19, // 17: user.User.GetRoleList:input_type -> user.BaseRoleItem
	19, // 18: user.User.AddRole:input_type -> user.BaseRoleItem
	19, // 19: user.User.DeleteRole:input_type -> user.BaseRoleItem
	20, // 20: user.User.GetPolicy:input_type -> user.BasePolicyItem
	20, // 21: user.User.GetPolicyList:input_type -> user.BasePolicyItem
	20, // 22: user.User.AddPolicy:input_type -> user.BasePolicyItem
	20, // 23: user.User.DeletePolicy:input_type -> user.BasePolicyItem
	25, // 24: user.User.CheckAdminPermission:input_type -> user.CheckAdminPermissionReq
	19, // 25: user.User.LoadUserPolicy:input_type -> user.BaseRoleItem
	19, // 26: user.User.LoadRolePolicy:input_type -> user.BaseRoleItem
	26, // 27: user.User.MiniappCode:input_type -> user.MiniappCodeReq
	10, // 28: user.User.AddUser:output_type -> user.LoginSuccessResp
	0,  // 29: user.User.DeleteUser:output_type -> user.SuccessResp
	0,  // 30: user.User.UpdateUser:output_type -> user.SuccessResp
	2,  // 31: user.User.GetUser:output_type -> user.UserResp
	8,  // 32: user.User.ListUser:output_type -> user.ListUserResp
	10, // 33: user.User.UserThirdLogin:output_type -> user.LoginSuccessResp
	0,  // 34: user.User.AddAdmin:output_type -> user.SuccessResp
	0,  // 35: user.User.UpdateAdmin:output_type -> user.SuccessResp
	12, // 36: user.User.GetAdmin:output_type -> user.AdminResp
	18, // 37: user.User.ListAdmin:output_type -> user.ListAdminResp
	0,  // 38: user.User.DeleteAdmin:output_type -> user.SuccessResp
	22, // 39: user.User.GetAllDomain:output_type -> user.GetAllDomainResp
	0,  // 40: user.User.GetRole:output_type -> user.SuccessResp
	23, // 41: user.User.GetRoleList:output_type -> user.GetRoleListeResp
	0,  // 42: user.User.AddRole:output_type -> user.SuccessResp
	0,  // 43: user.User.DeleteRole:output_type -> user.SuccessResp
	0,  // 44: user.User.GetPolicy:output_type -> user.SuccessResp
	24, // 45: user.User.GetPolicyList:output_type -> user.GetPolicyListResp
	0,  // 46: user.User.AddPolicy:output_type -> user.SuccessResp
	0,  // 47: user.User.DeletePolicy:output_type -> user.SuccessResp
	0,  // 48: user.User.CheckAdminPermission:output_type -> user.SuccessResp
	0,  // 49: user.User.LoadUserPolicy:output_type -> user.SuccessResp
	0,  // 50: user.User.LoadRolePolicy:output_type -> user.SuccessResp
	27, // 51: user.User.MiniappCode:output_type -> user.MiniappCodeResp
	28, // [28:52] is the sub-list for method output_type
	4,  // [4:28] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
