services: # 网关服务
  gateway:
    image: registry.cn-hangzhou.aliyuncs.com/theacheapp/gateway:20260702153709
    container_name: gateway
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
    networks:
      - app-network
    depends_on:
      - basecode-api
      - sdk-api
      - user-api
      - device-api
      - mqueue-job
        #      - ai-api
    restart: unless-stopped

  # BaseCode 服务
  basecode-rpc:
    image: registry.cn-hangzhou.aliyuncs.com/theacheapp/basecode-rpc:20260702153709
    container_name: basecode-rpc
    expose:
      - "8090"
    environment:
      - PORT=8090
    networks:
      - app-network
    restart: unless-stopped

  basecode-api:
    image: registry.cn-hangzhou.aliyuncs.com/theacheapp/basecode-api:20260702153709
    container_name: basecode-api
    expose:
      - "9090"
    environment:
      - PORT=9090
    networks:
      - app-network
    depends_on:
      - basecode-rpc
    restart: unless-stopped

  # SDK 服务
  sdk-rpc:
    image: registry.cn-hangzhou.aliyuncs.com/theacheapp/sdk-rpc:20260702153709
    container_name: sdk-rpc
    expose:
      - "8091"
    environment:
      - PORT=8091
    networks:
      - app-network
    restart: unless-stopped

  sdk-api:
    image: registry.cn-hangzhou.aliyuncs.com/theacheapp/sdk-api:20260702153709
    container_name: sdk-api
    expose:
      - "9091"
    environment:
      - PORT=9091
    networks:
      - app-network
    depends_on:
      - sdk-rpc
    restart: unless-stopped

  # User 服务
  user-rpc:
    image: registry.cn-hangzhou.aliyuncs.com/theacheapp/user-rpc:20260702153709
    container_name: user-rpc
    expose:
      - "8092"
    environment:
      - PORT=8092
    networks:
      - app-network
    restart: unless-stopped

  user-api:
    image: registry.cn-hangzhou.aliyuncs.com/theacheapp/user-api:20260702153709
    container_name: user-api
    expose:
      - "9092"
    environment:
      - PORT=9092
      - RPC_USER_HOST=user-rpc
      - RPC_USER_PORT=8092
    networks:
      - app-network
    depends_on:
      - user-rpc
    restart: unless-stopped

  # Device 服务
  device-rpc:
    image: registry.cn-hangzhou.aliyuncs.com/theacheapp/device-rpc:20260702153709
    container_name: device-rpc
    expose:
      - "8093"
    environment:
      - PORT=8093
    networks:
      - app-network
    restart: unless-stopped

  device-api:
    image: registry.cn-hangzhou.aliyuncs.com/theacheapp/device-api:20260702153709
    container_name: device-api
    expose:
      - "9093"
    environment:
      - PORT=9093
    networks:
      - app-network
    depends_on:
      - device-rpc
    restart: unless-stopped

      # # ai 服务
      # ai-rpc:
      # image: registry.cn-hangzhou.aliyuncs.com/theacheapp/ai-rpc:20260702153709
      # container_name: ai-rpc
      # expose:
      # - "8094"
      # environment:
      # - PORT=8094
      # networks:
      # - app-network
      # restart: unless-stopped
      #
      # ai-api:
      # image: registry.cn-hangzhou.aliyuncs.com/theacheapp/ai-api:20260702153709
      # container_name: ai-api
      # expose:
      # - "9094"
      # environment:
      # - PORT=9094
      # networks:
      # - app-network
      # depends_on:
      # - ai-rpc
      # restart: unless-stopped

  mqueue-job:
    image: registry.cn-hangzhou.aliyuncs.com/theacheapp/mqueue-job:20260702153709
    container_name: mqueue-job
    expose:
      - "7001"
    environment:
      - PORT=7001
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge