// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: sdk.proto

package sdk

import (
	"context"

	"amigo-api/common/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AiImageGenerationResp = pb.AiImageGenerationResp
	BaseAiReq             = pb.BaseAiReq
	ChatReq               = pb.ChatReq
	ChatResp              = pb.ChatResp
	CheckCodeReq          = pb.CheckCodeReq
	CheckCodeResp         = pb.CheckCodeResp
	GetCourierReq         = pb.GetCourierReq
	GetCourierResp        = pb.GetCourierResp
	GetUploadTokenReq     = pb.GetUploadTokenReq
	GetUploadTokenResp    = pb.GetUploadTokenResp
	GetWeatherItem        = pb.GetWeatherItem
	GetWeatherReq         = pb.GetWeatherReq
	GetWeatherResp        = pb.GetWeatherResp
	IpToAddressReq        = pb.IpToAddressReq
	IpToAddressResp       = pb.IpToAddressResp
	PngToElnkReq          = pb.PngToElnkReq
	PngToElnkResp         = pb.PngToElnkResp
	SendCodeReq           = pb.SendCodeReq
	SendCodeResp          = pb.SendCodeResp
	UploadFileReq         = pb.UploadFileReq
	UploadFileResp        = pb.UploadFileResp
	UploadUrlReq          = pb.UploadUrlReq
	UploadUrlResp         = pb.UploadUrlResp

	Sdk interface {
		SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error)
		CheckCode(ctx context.Context, in *CheckCodeReq, opts ...grpc.CallOption) (*CheckCodeResp, error)
		IpToAddress(ctx context.Context, in *IpToAddressReq, opts ...grpc.CallOption) (*IpToAddressResp, error)
		GetCourier(ctx context.Context, in *GetCourierReq, opts ...grpc.CallOption) (*GetCourierResp, error)
		Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error)
		GetWeather(ctx context.Context, in *GetWeatherReq, opts ...grpc.CallOption) (*GetWeatherResp, error)
		UploadFile(ctx context.Context, in *UploadFileReq, opts ...grpc.CallOption) (*UploadFileResp, error)
		UploadUrl(ctx context.Context, in *UploadUrlReq, opts ...grpc.CallOption) (*UploadUrlResp, error)
		GetUploadToken(ctx context.Context, in *GetUploadTokenReq, opts ...grpc.CallOption) (*GetUploadTokenResp, error)
		PngToElnk(ctx context.Context, in *PngToElnkReq, opts ...grpc.CallOption) (*PngToElnkResp, error)
		ImageGeneration(ctx context.Context, in *BaseAiReq, opts ...grpc.CallOption) (*AiImageGenerationResp, error)
	}

	defaultSdk struct {
		cli zrpc.Client
	}
)

func NewSdk(cli zrpc.Client) Sdk {
	return &defaultSdk{
		cli: cli,
	}
}

func (m *defaultSdk) SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error) {
	client := pb.NewSdkClient(m.cli.Conn())
	return client.SendCode(ctx, in, opts...)
}

func (m *defaultSdk) CheckCode(ctx context.Context, in *CheckCodeReq, opts ...grpc.CallOption) (*CheckCodeResp, error) {
	client := pb.NewSdkClient(m.cli.Conn())
	return client.CheckCode(ctx, in, opts...)
}

func (m *defaultSdk) IpToAddress(ctx context.Context, in *IpToAddressReq, opts ...grpc.CallOption) (*IpToAddressResp, error) {
	client := pb.NewSdkClient(m.cli.Conn())
	return client.IpToAddress(ctx, in, opts...)
}

func (m *defaultSdk) GetCourier(ctx context.Context, in *GetCourierReq, opts ...grpc.CallOption) (*GetCourierResp, error) {
	client := pb.NewSdkClient(m.cli.Conn())
	return client.GetCourier(ctx, in, opts...)
}

func (m *defaultSdk) Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error) {
	client := pb.NewSdkClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}

func (m *defaultSdk) GetWeather(ctx context.Context, in *GetWeatherReq, opts ...grpc.CallOption) (*GetWeatherResp, error) {
	client := pb.NewSdkClient(m.cli.Conn())
	return client.GetWeather(ctx, in, opts...)
}

func (m *defaultSdk) UploadFile(ctx context.Context, in *UploadFileReq, opts ...grpc.CallOption) (*UploadFileResp, error) {
	client := pb.NewSdkClient(m.cli.Conn())
	return client.UploadFile(ctx, in, opts...)
}

func (m *defaultSdk) UploadUrl(ctx context.Context, in *UploadUrlReq, opts ...grpc.CallOption) (*UploadUrlResp, error) {
	client := pb.NewSdkClient(m.cli.Conn())
	return client.UploadUrl(ctx, in, opts...)
}

func (m *defaultSdk) GetUploadToken(ctx context.Context, in *GetUploadTokenReq, opts ...grpc.CallOption) (*GetUploadTokenResp, error) {
	client := pb.NewSdkClient(m.cli.Conn())
	return client.GetUploadToken(ctx, in, opts...)
}

func (m *defaultSdk) PngToElnk(ctx context.Context, in *PngToElnkReq, opts ...grpc.CallOption) (*PngToElnkResp, error) {
	client := pb.NewSdkClient(m.cli.Conn())
	return client.PngToElnk(ctx, in, opts...)
}

func (m *defaultSdk) ImageGeneration(ctx context.Context, in *BaseAiReq, opts ...grpc.CallOption) (*AiImageGenerationResp, error) {
	client := pb.NewSdkClient(m.cli.Conn())
	return client.ImageGeneration(ctx, in, opts...)
}
