// Code generated by goctl. DO NOT EDIT.

package handler

import (
	"net/http"

	"amigo-api/app/job/mqueue/internal/svc"
	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/mqueue/enqueue",
				Handler: EnqueueHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/mqueue/enqueue-delayed",
				Handler: EnqueueDelayedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/mqueue/result/:task_id",
				Handler: TaskResultHandler(serverCtx),
			},
		},
	)
}
