// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddAppReq struct {
	Name        string `json:"name"`
	AppKey      string `json:"app_key"`
	Category    string `json:"category,optional,default="`
	Version     string `json:"version,optional,default="`
	Vendor      string `json:"vendor,optional,default="`
	IconBg      string `json:"icon_bg,optional,default="`
	IconColor   string `json:"icon_color,optional,default="`
	IconLabel   string `json:"icon_label,optional,default="`
	Description string `json:"description,optional,default="`
	SensorType  string `json:"sensor_type,optional,default="`
	ExtraData   string `json:"extra_data,optional,default="`
}

type AddDeviceEventReq struct {
	DeviceId    uint64 `json:"device_id"`
	EventType   string `json:"event_type,optional,default="`
	EventLevel  string `json:"event_level,optional,default=info"`
	Title       string `json:"title"`
	Description string `json:"description,optional,default="`
	Source      string `json:"source,optional,default=device"`
	ExtraData   string `json:"extra_data,optional,default="`
}

type AddDeviceReq struct {
	Name        string `json:"name"`
	UserId      uint64 `json:"user_id"`
	MacAddress  string `json:"mac_address"`
	InternalIp  string `json:"internal_ip"`
	BmpImage    string `json:"bmp_image,optional,default="`
	IsRunning   int64  `json:"is_running,optional,default=2"`
	ExtraData   string `json:"extra_data,optional,default="`
	Firmware    string `json:"firmware,optional,default="`
	DeviceGroup string `json:"device_group,optional,default="`
}

type CommonResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type DeleteAppReq struct {
	AppId  uint64 `json:"app_id,default=0,optional"`
	AppKey string `json:"app_key,default=,optional"`
}

type DeleteDeviceEventReq struct {
	DeviceEventId uint64 `json:"device_event_id,default=0,optional"`
	DeviceId      uint64 `json:"device_id,default=0,optional"`
}

type DeleteDeviceReq struct {
	DeviceId   uint64 `json:"device_id,default=0,optional"`
	MacAddress string `json:"mac_address,default=,optional"`
}

type EmptyResp struct {
}

type GetAppReq struct {
	AppId  uint64 `form:"app_id,default=0,optional"`
	AppKey string `form:"app_key,default=,optional"`
}

type GetAppResp struct {
	AppId       uint64 `json:"app_id"`
	Name        string `json:"name"`
	AppKey      string `json:"app_key"`
	Category    string `json:"category"`
	Version     string `json:"version"`
	Vendor      string `json:"vendor"`
	IconBg      string `json:"icon_bg"`
	IconColor   string `json:"icon_color"`
	IconLabel   string `json:"icon_label"`
	Description string `json:"description"`
	SensorType  string `json:"sensor_type"`
	ExtraData   string `json:"extra_data"`
	IsDelete    int64  `json:"is_delete"`
	CreateTime  uint64 `json:"create_time"`
	UpdateTime  uint64 `json:"update_time"`
}

type GetDeviceEventReq struct {
	DeviceEventId uint64 `form:"device_event_id,default=0,optional"`
}

type GetDeviceEventResp struct {
	DeviceEventId uint64 `json:"device_event_id"`
	DeviceId      uint64 `json:"device_id"`
	EventType     string `json:"event_type"`
	EventLevel    string `json:"event_level"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	Source        string `json:"source"`
	ExtraData     string `json:"extra_data"`
	IsDelete      int64  `json:"is_delete"`
	CreateTime    uint64 `json:"create_time"`
}

type GetDeviceReq struct {
	DeviceId   uint64 `form:"device_id,default=0,optional"`
	MacAddress string `form:"mac_address,default=,optional"`
}

type GetDeviceResp struct {
	DeviceId    uint64 `json:"device_id"`
	Name        string `json:"name"`
	UserId      uint64 `json:"user_id"`
	MacAddress  string `json:"mac_address"`
	InternalIp  string `json:"internal_ip"`
	BmpImage    string `json:"bmp_image"`
	IsRunning   int64  `json:"is_running"`
	ExtraData   string `json:"extra_data"`
	IsDelete    int64  `json:"is_delete"`
	CreateTime  uint64 `json:"create_time"`
	UpdateTime  uint64 `json:"update_time"`
	Firmware    string `json:"firmware"`
	DeviceGroup string `json:"device_group"`
}

type ListAppReq struct {
	Name       string `form:"name,default=,optional"`
	AppKey     string `form:"app_key,default=,optional"`
	Category   string `form:"category,default=,optional"`
	SensorType string `form:"sensor_type,default=,optional"`
	IsDelete   int64  `form:"is_delete,default=2,optional"`
	Page       int64  `form:"page,default=1,optional"`
	PageSize   int64  `form:"page_size,default=10,optional"`
}

type ListAppResp struct {
	List  []GetAppResp `json:"list"`
	Total int64        `json:"total"`
}

type ListDeviceEventReq struct {
	DeviceId   uint64 `form:"device_id,default=0,optional"`
	EventType  string `form:"event_type,default=,optional"`
	EventLevel string `form:"event_level,default=,optional"`
	Source     string `form:"source,default=,optional"`
	IsDelete   int64  `form:"is_delete,default=2,optional"`
	Page       int64  `form:"page,default=1,optional"`
	PageSize   int64  `form:"page_size,default=10,optional"`
}

type ListDeviceEventResp struct {
	List  []GetDeviceEventResp `json:"list"`
	Total int64                `json:"total"`
}

type ListDeviceReq struct {
	Name        string `form:"name,default=,optional"`
	UserId      uint64 `form:"user_id,default=0,optional"`
	MacAddress  string `form:"mac_address,default=,optional"`
	InternalIp  string `form:"internal_ip,default=,optional"`
	IsRunning   int64  `form:"is_running,default=0,optional"`
	IsDelete    int64  `form:"is_delete,default=2,optional"`
	Firmware    string `form:"firmware,default=,optional"`
	DeviceGroup string `form:"device_group,default=,optional"`
	Page        int64  `form:"page,default=1,optional"`
	PageSize    int64  `form:"page_size,default=10,optional"`
}

type ListDeviceResp struct {
	List  []GetDeviceResp `json:"list"`
	Total int64           `json:"total"`
}

type UpdateAppReq struct {
	AppId       uint64 `json:"app_id"`
	Name        string `json:"name"`
	AppKey      string `json:"app_key"`
	Category    string `json:"category,optional,default="`
	Version     string `json:"version,optional,default="`
	Vendor      string `json:"vendor,optional,default="`
	IconBg      string `json:"icon_bg,optional,default="`
	IconColor   string `json:"icon_color,optional,default="`
	IconLabel   string `json:"icon_label,optional,default="`
	Description string `json:"description,optional,default="`
	SensorType  string `json:"sensor_type,optional,default="`
	ExtraData   string `json:"extra_data,optional,default="`
	IsDelete    int64  `json:"is_delete,default=2"`
}

type UpdateDeviceReq struct {
	DeviceId    uint64 `json:"device_id"`
	Name        string `json:"name"`
	UserId      uint64 `json:"user_id"`
	MacAddress  string `json:"mac_address"`
	InternalIp  string `json:"internal_ip"`
	BmpImage    string `json:"bmp_image,optional,default="`
	IsRunning   int64  `json:"is_running,optional,default=2"`
	ExtraData   string `json:"extra_data,optional,default="`
	Firmware    string `json:"firmware,optional,default="`
	DeviceGroup string `json:"device_group,optional,default="`
	IsDelete    int64  `json:"is_delete"`
}
