#!/bin/sh

REGISTRY="registry.cn-hangzhou.aliyuncs.com"
NAMESPACE="theacheapp"
APP="gateway"
if [ -n "$2" ]; then
  tag="$2"
else
  tag=$(date "+%Y%m%d%H%M%S")
fi

docker build --platform linux/amd64 -f deploy/DockerFile/gatewayDockerfile -t $REGISTRY/$NAMESPACE/$APP:$tag .
docker push $REGISTRY/$NAMESPACE/$APP:$tag
