#!/bin/sh

REGISTRY="registry.cn-hangzhou.aliyuncs.com"
NAMESPACE="theacheapp"
APP="queue-job"
DOCKERFILE="queueJobDockerFile"
if [ -n "$1" ]; then
  tag="$1"
else
  tag=$(date "+%Y%m%d%H%M%S")
fi

rm -rf deploy/simpleDockerFile/cmd/queue
CGO_ENABLED=0 go build -ldflags="-s -w" -o deploy/simpleDockerFile/cmd/queue app/job/queue/queue.go
docker build --platform linux/amd64 -f deploy/simpleDockerFile/$DOCKERFILE -t $REGISTRY/$NAMESPACE/$APP:$tag .
docker push $REGISTRY/$NAMESPACE/$APP:$tag

