#!/bin/sh

tag=$(date "+%Y%m%d%H%M%S")
REGISTRY="registry.cn-hangzhou.aliyuncs.com"
NAMESPACE="theacheapp"
APP=$(echo "$1" | tr '[:upper:]' '[:lower:]')
APP+="-rpc"
DOCKERFILE="${1}RpcDockerFile"

docker build --platform linux/amd64 -f deploy/DockerFile/$DOCKERFILE -t $REGISTRY/$NAMESPACE/$APP:$tag .
docker push $REGISTRY/$NAMESPACE/$APP:$tag
