#!/bin/sh

REGISTRY="registry.cn-hangzhou.aliyuncs.com"
NAMESPACE="theacheapp"
APP=$(echo "$1" | tr '[:upper:]' '[:lower:]')
APP+="-rpc"
DOCKERFILE="${1}RpcDockerFile"
if [ -n "$2" ]; then
  tag="$2"
else
  tag=$(date "+%Y%m%d%H%M%S")
fi

rm -rf deploy/simpleDockerFile/cmd/rpc/$1
CGO_ENABLED=0 go build -ldflags="-s -w" -o deploy/simpleDockerFile/cmd/rpc/$1 app/$1/rpc/$1.go
docker build --platform linux/amd64 -f deploy/simpleDockerFile/$DOCKERFILE -t $REGISTRY/$NAMESPACE/$APP:$tag .
docker push $REGISTRY/$NAMESPACE/$APP:$tag
