#!/bin/sh

REGISTRY="registry.cn-hangzhou.aliyuncs.com"
NAMESPACE="theacheapp"
APP="gateway"
if [ -n "$1" ]; then
  tag="$1"
else
  tag=$(date "+%Y%m%d%H%M%S")
fi

rm -rf deploy/simpleDockerFile/cmd/gateway
CGO_ENABLED=0 go build -ldflags="-s -w" -o deploy/simpleDockerFile/cmd/gateway app/gateway/gateway.go
docker build --platform linux/amd64 -f deploy/simpleDockerFile/gatewayDockerfile -t $REGISTRY/$NAMESPACE/$APP:$tag .
docker push $REGISTRY/$NAMESPACE/$APP:$tag

