Name: device
Host: 0.0.0.0
Port: 9093

DeviceRpcConf:
  Target: device-rpc:8093

Auth:
  AccessSecret: "amigoProject"
  AccessExpire: 7200

Telemetry:
  Name: device-api
  EndpointType: otlpgrpc
  Sampler: 1.0
  Endpoint: "81.69.160.35:4317"
  Timeout: 5000
