// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type AdminAddReq struct {
	Mobile     string `json:"mobile"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
}

type AdminDeleteReq struct {
	AdminId uint64 `json:"admin_id"`
}

type AdminLoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type AdminLoginResp struct {
	AdminId      uint64 `json:"admin_id"`
	Mobile       string `json:"mobile"`
	Username     string `json:"username"`
	Avatar       string `json:"avatar"`
	CreateTime   int64  `json:"create_time"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type AdminLoginSmsReq struct {
	Mobile string `json:"mobile"`
	Code   string `json:"code"`
}

type AdminUpdateMobileReq struct {
	AdminId uint64 `json:"admin_id"`
	Mobile  string `json:"mobile"`
}

type AdminUpdatePasswordReq struct {
	AdminId    uint64 `json:"admin_id"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
}

type AdminUpdateReq struct {
	AdminId  uint64 `json:"admin_id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type CommonResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type DomainListResp struct {
	List []string `json:"list"`
}

type EmptyResp struct {
}

type GetAdminResp struct {
	AdminId    uint64 `json:"admin_id"`
	Mobile     string `json:"mobile"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"create_time"`
}

type GetUserResp struct {
	UserId     uint64 `json:"user_id"`
	Mobile     string `json:"mobile"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"create_time"`
}

type ListAdminReq struct {
	Page     int64  `form:"page,default=1,optional"`
	PageSize int64  `form:"page_size,default=10,optional"`
	AdminId  string `form:"admin_id,default=,optional"`
	Username string `form:"username,default=,optional"`
	Mobile   string `form:"mobile,default=,optional"`
}

type ListAdminResp struct {
	List  []GetAdminResp `json:"list"`
	Total int64          `json:"total"`
}

type ListUserReq struct {
	Page     int64  `form:"page,default=1,optional"`
	PageSize int64  `form:"page_size,default=10,optional"`
	UserId   string `form:"user_id,default=,optional"`
	Username string `form:"username,default=,optional"`
	Mobile   string `form:"mobile,default=,optional"`
}

type ListUserResp struct {
	List  []GetUserResp `json:"list"`
	Total int64         `json:"total"`
}

type PolicyItem struct {
	Domain string `json:"domain,default=,optional" form:"domain,default=,optional"`
	Role   string `json:"role,default=,optional" form:"role,default=,optional"`
	Policy string `json:"policy,default=,optional" form:"policy,default=,optional"`
	Action string `json:"action,default=,optional" form:"action,default=,optional"`
}

type PolicyListResp struct {
	List []PolicyItem `json:"list"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type RoleItem struct {
	Domain  string `json:"domain,default=,optional" form:"domain,default=,optional"`
	Role    string `json:"role,default=,optional" form:"role,default=,optional"`
	AdminId string `json:"admin_id,default=,optional" form:"admin_id,default=,optional"`
}

type RoleListResp struct {
	List []RoleItem `json:"list"`
}

type UserAddReq struct {
	Mobile     string `json:"mobile"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
}

type UserDeleteReq struct {
	UserId uint64 `json:"user_id"`
}

type UserLoginReq struct {
	Mobile   string `json:"mobile,optional"`
	Username string `json:"username,optional"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	UserId     uint64 `json:"user_id"`
	Mobile     string `json:"mobile"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"create_time"`
	Token      string `json:"token"`
}

type UserThirdLoginReq struct {
	Code    string `json:"code"`
	AppType string `json:"app_type"`
}

type UserUpdateMobileReq struct {
	UserId uint64 `json:"user_id"`
	Mobile string `json:"mobile"`
}

type UserUpdatePasswordReq struct {
	UserId     uint64 `json:"user_id"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
}

type UserUpdateReq struct {
	UserId   uint64 `json:"user_id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}
