// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type AdminAddReq struct {
	Mobile     string `json:"mobile"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
}

type AdminDeleteReq struct {
	AdminId uint64 `json:"admin_id"`
}

type AdminLoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type AdminLoginResp struct {
	AdminId    uint64 `json:"admin_id"`
	Mobile     string `json:"mobile"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"create_time"`
	Token      string `json:"token"`
}

type AdminLoginSmsReq struct {
	Mobile string `json:"mobile"`
	Code   string `json:"code"`
}

type AdminUpdateMobileReq struct {
	AdminId uint64 `json:"admin_id"`
	Mobile  string `json:"mobile"`
}

type AdminUpdatePasswordReq struct {
	AdminId    uint64 `json:"admin_id"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
}

type AdminUpdateReq struct {
	AdminId  uint64 `json:"admin_id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type CommonResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type DomainListResp struct {
	List []string `json:"list"`
}

type EmptyResp struct {
}

type GetAdminResp struct {
	AdminId    uint64 `json:"admin_id"`
	Mobile     string `json:"mobile"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"create_time"`
}

type GetUserResp struct {
	UserId     uint64 `json:"user_id"`
	Mobile     string `json:"mobile"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"create_time"`
}

type PolicyItem struct {
	Domain string `json:"domain,default=,optional"`
	Role   string `json:"role,default=,optional"`
	Policy string `json:"policy,default=,optional"`
	Action string `json:"action,default=,optional"`
}

type PolicyListResp struct {
	List []PolicyItem `json:"list"`
}

type RoleItem struct {
	Domain  string `json:"domain,default=,optional"`
	Role    string `json:"role,default=,optional"`
	AdminId string `json:"admin_id,default=,optional"`
}

type RoleListResp struct {
	List []RoleItem `json:"list"`
}

type UserAddReq struct {
	Mobile     string `json:"mobile"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
}

type UserDeleteReq struct {
	UserId uint64 `json:"user_id"`
}

type UserLoginReq struct {
	Mobile   string `json:"mobile,optional"`
	Username string `json:"username,optional"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	UserId     uint64 `json:"user_id"`
	Mobile     string `json:"mobile"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"create_time"`
	Token      string `json:"token"`
}

type UserThirdLoginReq struct {
	Code    string `json:"code"`
	AppType string `json:"app_type"`
}

type UserUpdateMobileReq struct {
	UserId uint64 `json:"user_id"`
	Mobile string `json:"mobile"`
}

type UserUpdatePasswordReq struct {
	UserId     uint64 `json:"user_id"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
}

type UserUpdateReq struct {
	UserId   uint64 `json:"user_id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}
