// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	baseCode "amigo-api/app/baseCode/api/internal/handler/baseCode"
	baseCodeItem "amigo-api/app/baseCode/api/internal/handler/baseCodeItem"
	baseCodeSort "amigo-api/app/baseCode/api/internal/handler/baseCodeSort"
	"amigo-api/app/baseCode/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: baseCode.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: baseCode.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/base_code"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add_sort",
				Handler: baseCode.AddSortHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete_sort",
				Handler: baseCode.DeleteSortHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update_sort",
				Handler: baseCode.UpdateSortHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/base_code"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: baseCode.AddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: baseCode.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: baseCode.UpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/base_code"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: baseCodeItem.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: baseCodeItem.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/base_code_item"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: baseCodeItem.AddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: baseCodeItem.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: baseCodeItem.UpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/base_code_item"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: baseCodeSort.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: baseCodeSort.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/base_code_sort"),
	)
}
