// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: user.proto

package user

import (
	"context"

	"amigo-api/common/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAdminReq             = pb.AddAdminReq
	AddUserReq              = pb.AddUserReq
	AdminLoginSuccessResp   = pb.AdminLoginSuccessResp
	AdminResp               = pb.AdminResp
	BasePolicyItem          = pb.BasePolicyItem
	BaseRoleItem            = pb.BaseRoleItem
	CheckAdminPermissionReq = pb.CheckAdminPermissionReq
	DeleteAdminReq          = pb.DeleteAdminReq
	DeleteAdminResp         = pb.DeleteAdminResp
	DeleteUserReq           = pb.DeleteUserReq
	DeleteUserResp          = pb.DeleteUserResp
	GetAdminReq             = pb.GetAdminReq
	GetAllDomainReq         = pb.GetAllDomainReq
	GetAllDomainResp        = pb.GetAllDomainResp
	GetPolicyListResp       = pb.GetPolicyListResp
	GetRoleListeResp        = pb.GetRoleListeResp
	GetUserReq              = pb.GetUserReq
	ListAdminReq            = pb.ListAdminReq
	ListAdminResp           = pb.ListAdminResp
	ListUserReq             = pb.ListUserReq
	ListUserResp            = pb.ListUserResp
	LoginAdminReq           = pb.LoginAdminReq
	LoginSuccessResp        = pb.LoginSuccessResp
	MiniappCodeReq          = pb.MiniappCodeReq
	MiniappCodeResp         = pb.MiniappCodeResp
	SuccessResp             = pb.SuccessResp
	UpdateAdminReq          = pb.UpdateAdminReq
	UpdateUserReq           = pb.UpdateUserReq
	UserResp                = pb.UserResp
	UserThirdLoginReq       = pb.UserThirdLoginReq

	User interface {
		AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*LoginSuccessResp, error)
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*SuccessResp, error)
		UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*SuccessResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserResp, error)
		ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error)
		UserThirdLogin(ctx context.Context, in *UserThirdLoginReq, opts ...grpc.CallOption) (*LoginSuccessResp, error)
		AddAdmin(ctx context.Context, in *AddAdminReq, opts ...grpc.CallOption) (*SuccessResp, error)
		UpdateAdmin(ctx context.Context, in *UpdateAdminReq, opts ...grpc.CallOption) (*SuccessResp, error)
		GetAdmin(ctx context.Context, in *GetAdminReq, opts ...grpc.CallOption) (*AdminResp, error)
		ListAdmin(ctx context.Context, in *ListAdminReq, opts ...grpc.CallOption) (*ListAdminResp, error)
		DeleteAdmin(ctx context.Context, in *DeleteAdminReq, opts ...grpc.CallOption) (*SuccessResp, error)
		LoginAdmin(ctx context.Context, in *LoginAdminReq, opts ...grpc.CallOption) (*AdminLoginSuccessResp, error)
		GetAllDomain(ctx context.Context, in *GetAllDomainReq, opts ...grpc.CallOption) (*GetAllDomainResp, error)
		GetRole(ctx context.Context, in *BaseRoleItem, opts ...grpc.CallOption) (*SuccessResp, error)
		GetRoleList(ctx context.Context, in *BaseRoleItem, opts ...grpc.CallOption) (*GetRoleListeResp, error)
		AddRole(ctx context.Context, in *BaseRoleItem, opts ...grpc.CallOption) (*SuccessResp, error)
		DeleteRole(ctx context.Context, in *BaseRoleItem, opts ...grpc.CallOption) (*SuccessResp, error)
		GetPolicy(ctx context.Context, in *BasePolicyItem, opts ...grpc.CallOption) (*SuccessResp, error)
		GetPolicyList(ctx context.Context, in *BasePolicyItem, opts ...grpc.CallOption) (*GetPolicyListResp, error)
		AddPolicy(ctx context.Context, in *BasePolicyItem, opts ...grpc.CallOption) (*SuccessResp, error)
		DeletePolicy(ctx context.Context, in *BasePolicyItem, opts ...grpc.CallOption) (*SuccessResp, error)
		CheckAdminPermission(ctx context.Context, in *CheckAdminPermissionReq, opts ...grpc.CallOption) (*SuccessResp, error)
		LoadUserPolicy(ctx context.Context, in *BaseRoleItem, opts ...grpc.CallOption) (*SuccessResp, error)
		LoadRolePolicy(ctx context.Context, in *BaseRoleItem, opts ...grpc.CallOption) (*SuccessResp, error)
		MiniappCode(ctx context.Context, in *MiniappCodeReq, opts ...grpc.CallOption) (*MiniappCodeResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*LoginSuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.AddUser(ctx, in, opts...)
}

func (m *defaultUser) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultUser) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUser) ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.ListUser(ctx, in, opts...)
}

func (m *defaultUser) UserThirdLogin(ctx context.Context, in *UserThirdLoginReq, opts ...grpc.CallOption) (*LoginSuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.UserThirdLogin(ctx, in, opts...)
}

func (m *defaultUser) AddAdmin(ctx context.Context, in *AddAdminReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.AddAdmin(ctx, in, opts...)
}

func (m *defaultUser) UpdateAdmin(ctx context.Context, in *UpdateAdminReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.UpdateAdmin(ctx, in, opts...)
}

func (m *defaultUser) GetAdmin(ctx context.Context, in *GetAdminReq, opts ...grpc.CallOption) (*AdminResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetAdmin(ctx, in, opts...)
}

func (m *defaultUser) ListAdmin(ctx context.Context, in *ListAdminReq, opts ...grpc.CallOption) (*ListAdminResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.ListAdmin(ctx, in, opts...)
}

func (m *defaultUser) DeleteAdmin(ctx context.Context, in *DeleteAdminReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.DeleteAdmin(ctx, in, opts...)
}

func (m *defaultUser) LoginAdmin(ctx context.Context, in *LoginAdminReq, opts ...grpc.CallOption) (*AdminLoginSuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.LoginAdmin(ctx, in, opts...)
}

func (m *defaultUser) GetAllDomain(ctx context.Context, in *GetAllDomainReq, opts ...grpc.CallOption) (*GetAllDomainResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetAllDomain(ctx, in, opts...)
}

func (m *defaultUser) GetRole(ctx context.Context, in *BaseRoleItem, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

func (m *defaultUser) GetRoleList(ctx context.Context, in *BaseRoleItem, opts ...grpc.CallOption) (*GetRoleListeResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetRoleList(ctx, in, opts...)
}

func (m *defaultUser) AddRole(ctx context.Context, in *BaseRoleItem, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.AddRole(ctx, in, opts...)
}

func (m *defaultUser) DeleteRole(ctx context.Context, in *BaseRoleItem, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultUser) GetPolicy(ctx context.Context, in *BasePolicyItem, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetPolicy(ctx, in, opts...)
}

func (m *defaultUser) GetPolicyList(ctx context.Context, in *BasePolicyItem, opts ...grpc.CallOption) (*GetPolicyListResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetPolicyList(ctx, in, opts...)
}

func (m *defaultUser) AddPolicy(ctx context.Context, in *BasePolicyItem, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.AddPolicy(ctx, in, opts...)
}

func (m *defaultUser) DeletePolicy(ctx context.Context, in *BasePolicyItem, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.DeletePolicy(ctx, in, opts...)
}

func (m *defaultUser) CheckAdminPermission(ctx context.Context, in *CheckAdminPermissionReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.CheckAdminPermission(ctx, in, opts...)
}

func (m *defaultUser) LoadUserPolicy(ctx context.Context, in *BaseRoleItem, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.LoadUserPolicy(ctx, in, opts...)
}

func (m *defaultUser) LoadRolePolicy(ctx context.Context, in *BaseRoleItem, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.LoadRolePolicy(ctx, in, opts...)
}

func (m *defaultUser) MiniappCode(ctx context.Context, in *MiniappCodeReq, opts ...grpc.CallOption) (*MiniappCodeResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.MiniappCode(ctx, in, opts...)
}
